### ISSUE TITLE
Comma separated list of primary keys not working for field comparison.

### ISSUE THREAD

**Issue by mayanksroy01** [GoogleCloudPlatform/professional-services-data-validator#1002]
data-validation validate row \
  -sc BQ_CONN \
  -tc BQ_CONN \
  -tbls $PROJECT_ID.$DATASET_ID.Employees=$PROJECT_ID.$DATASET_ID.Employees1 \
  --primary-keys 'employee_id' \
  -comp-fields first_name,last_name,hire_date,department
  
  The above command works. But when I pass comma separated list in primary_keys. 
  
  data-validation validate row \
  -sc BQ_CONN \
  -tc BQ_CONN \
  -tbls $PROJECT_ID.$DATASET_ID.Employees=$PROJECT_ID.$DATASET_ID.Employees1 \
  --primary-keys 'employee_id,first_name,last_name,hire_date,department' \
  -comp-fields first_name,last_name,hire_date,department
  
  Getting this error : raise IntegrityError(f'Duplicate column name(s): {duplicate_names}')
ibis.common.exceptions.IntegrityError: Duplicate column name(s): ['first_name', 'last_name', 'hire_date', 'department']

**Comment by nehanene15** [comment]
This is happening because your comparison fields are the same as your primary keys. We treat primary keys as comparison fields already, so this results in a query with duplicate column names. (See the query with the `--verbose` option)

The fix for this is to use a config file (`-c config.yaml`) and edit the PK values to have an alias to avoid duplicate column names like so:
```
primary_keys:
  - cast: null
    field_alias: first_name_pk
    source_column: first_name
    target_column: first_name
```

**Comment by mayanksroy01** [comment]
> This is happening because your comparison fields are the same as your primary keys. We treat primary keys as comparison fields already, so this results in a query with duplicate column names. (See the query with the `--verbose` option)
> 
> The fix for this is to use a config file (`-c config.yaml`) and edit the PK values to have an alias to avoid duplicate column names like so:
> 
> ```
> primary_keys:
>   - cast: null
>     field_alias: first_name_pk
>     source_column: first_name
>     target_column: first_name
> ```

So if have to use multiple columns as primary keys, should config file be like this ?

primary_keys:
  - cast: null
    field_alias: first_name_pk
    source_column: first_name
    target_column: first_name
  - cast: null
    field_alias: last_name_pk
    source_column: last_name
    target_column: last_name
  - cast: null
    field_alias: hire_date_pk
    source_column: hire_date
    target_column: hire_date

and so on...

**Comment by mayanksroy01** [comment]
So if have to use multiple columns as primary keys, should config file be like this ?

primary_keys:

cast: null
field_alias: first_name_pk
source_column: first_name
target_column: first_name
cast: null
field_alias: last_name_pk
source_column: last_name
target_column: last_name
cast: null
field_alias: hire_date_pk
source_column: hire_date
target_column: hire_date
and so on...

**Comment by nehanene15** [comment]
This isn't due to multiple PKs - it's because your PK columns overlap with your comparison field columns. For example, 
'first_name,last_name,hire_date,department' are **both** PKs and comparison-fields.

If you have an overlap, you need to provide an alias for your PKs like the config you suggested above.

**Comment by helensilva14** [comment]
Hi @mayanksroy01! Were you able to solve your problem? 

Please let us know so we can either further assess it or close the issue, thank you!

**Comment by mayanksroy01** [comment]
Yes, it was resolved. Thank You.

**Comment by helensilva14** [comment]
Thanks for the update!

**Comment by mayanksroy01** [comment]
Hi @helensilva14 
If any column in the comma separated list provided in primary keys is null, will DVT still produce correct results.
I'm getting some incorrect results for my use case when one column is null.
