### ISSUE TITLE
DB2 Row Validation : Random rows not supported for DB2 row validation with Custom Query

### ISSUE THREAD

**Issue by madhu-jain** [GoogleCloudPlatform/professional-services-data-validator#1020]
We've DB2 on ZOS for which we're running row validation using Custom query and random rows. Seems RANDOM function is not recognised in DB2. 
Please find below yaml generated and error received : 

**yaml :** 

result_handler:
  project_id: <project_id>
  table_id: <dataset>.results
  type: BigQuery
source: DB2_CONN_02
target: BQ_CONN
validations:
- calculated_fields: []
  comparison_fields: 
  - cast: null
    field_alias: rxcod_opp_id
    source_column: rxcod_opp_id
    target_column: rxcod_opp_id
  - cast: null
    field_alias: rxcod_des
    source_column: rxcod_des
    target_column: rxcod_des
  - cast: null
    field_alias: rxcod_prty
    source_column: rxcod_prty
    target_column: rxcod_prty
  - cast: null
    field_alias: rxcod_pgm_id
    source_column: rxcod_pgm_id
    target_column: rxcod_pgm_id
  - cast: null
    field_alias: rxcod_sup_val
    source_column: rxcod_sup_val
    target_column: rxcod_sup_val
  - cast: null
    field_alias: rxcod_lst_opr_id
    source_column: rxcod_lst_opr_id
    target_column: rxcod_lst_opr_id
  - cast: null
    field_alias: rxcod_lst_mnt_tsmp
    source_column: rxcod_lst_mnt_tsmp
    target_column: rxcod_lst_mnt_tsmp
  custom_query_type: row
  filter_status: null
  filters: []
  format: table
  labels:
  - !!python/tuple
    - category
    - source_to_landing_validation
  - !!python/tuple
    - validation_name
    - row_attribute_check
  - !!python/tuple
    - load_dt
    - '2023-10-11'
  - !!python/tuple
    - dag_id
    - manual
  - !!python/tuple
    - dag_run_id
    - manual
  - !!python/tuple
    - dag_execution_date
    - '2023-10-11T00:00:00'
  primary_keys:
  - cast: null
    field_alias: pk
    source_column: pk
    target_column: pk
  random_row_batch_size: "1000"
  schema_name: null
  source_query: "SELECT rxcod_opp_id as pk, RXCOD_OPP_ID, translate(translate(RXCOD_DES,'',chr(10)),'',chr(13)) RXCOD_DES, RXCOD_PRTY, RXCOD_PGM_ID, replace(replace(RXCOD_SUP_VAL,chr(10),''),chr(13),'') RXCOD_SUP_VAL, replace(replace(RXCOD_LST_OPR_ID,chr(10),''),chr(13),'') RXCOD_LST_OPR_ID, to_char(RXCOD_LST_MNT_TSMP,'YYYY-MM-DD HH24:MI:SS.FF6') RXCOD_LST_MNT_TSMP FROM SYSADM.<source_table>"
  table_name: null
  target_query: "SELECT rxcod_opp_id as pk, * FROM `<project_id>.<dataset>.table_id` where edw_file_ingested_date='2023-10-11'"
  target_schema_name: null
  target_table_name: null
  threshold: 0.0
  type: Custom-query
  use_random_rows: true

**Error :** 

AM-ERROR: Error (ibm_db_dbi.ProgrammingError) ibm_db_dbi::ProgrammingError: Statement Execute Failed: [IBM][CLI Driver][DB2] SQL0440N  No authorized routine named "RANDOM" of type "" having compatible arguments was found.  

SQLSTATE=42884 SQLCODE=-440

**Query generated :** 

[SQL: 

WITH t0 AS 
(SELECT [t2.pk](http://t2.pk/) AS pk, t2.rxcod_opp_id AS rxcod_opp_id, t2.rxcod_des AS rxcod_des, t2.rxcod_prty AS rxcod_prty, t2.rxcod_pgm_id AS rxcod_pgm_id, t2.rxcod_sup_val AS rxcod_sup_val, t2.rxcod_lst_opr_id AS rxcod_lst_opr_id, t2.rxcod_lst_mnt_tsmp AS rxcod_lst_mnt_tsmp 
FROM (SELECT rxcod_opp_id as pk, RXCOD_OPP_ID, translate(translate(RXCOD_DES,'',chr(10)),'',chr(13)) RXCOD_DES, RXCOD_PRTY, RXCOD_PGM_ID, replace(replace(RXCOD_SUP_VAL,chr(10),''),chr(13),'') RXCOD_SUP_VAL, replace(replace(RXCOD_LST_OPR_ID,chr(10),''),chr(13),'') RXCOD_LST_OPR_ID, to_char(RXCOD_LST_MNT_TSMP,'YYYY-MM-DD HH24:MI:SS.FF6') RXCOD_LST_MNT_TSMP FROM SYSADM.<source_table>) AS t2)
 SELECT [t1.pk](http://t1.pk/) 
FROM (SELECT [t2.pk](http://t2.pk/) AS pk 
FROM (SELECT [t0.pk](http://t0.pk/) AS pk 
FROM t0) AS t2 ORDER BY random() ASC FETCH FIRST 1000 ROWS ONLY) AS t1]

**Comment by nehanene15** [comment]
Random row isn't supported for custom query row validations. When doing random row with regular row validations, DVT issues a query before to get 1000 primary keys from the source and target tables to use as a filter (`WHERE pk IN (a, b, c, ...)`). With custom query, this isn't possible since DVT doesn't connect to a table, but instead builds a nested query.

We recommend using filters within your custom query itself to limit the data that's validated.

**Comment by piyushsarraf** [comment]
Hi @nehanene15 

With this [commit](https://github.com/GoogleCloudPlatform/professional-services-data-validator/commit/fc42c6181a73f79d55dc74ddd383d462a0ca4e7a), currently we are supporting random-row in custom-query validation(I have attached the sample ss for reference). 

I think, the issue is the random function we are using [here](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/feb2829d0f0e8d502aa1e4f10091efc73028a315/third_party/ibis/ibis_db2/registry.py#L450), is not supported for Z/OS version of DB2.

![image](https://github.com/GoogleCloudPlatform/professional-services-data-validator/assets/47020544/5eb951de-6356-45ef-a9c6-183294edf7ec)

**Comment by madhu-jain** [comment]
Row validation with custom query and random rows is supported for SQL Server and DB2(LUW). Seems random rows is not supported for DB2(ZOS). While running it for DB2(ZOS), it throws below error : 

AM-ERROR: Error (ibm_db_dbi.ProgrammingError) ibm_db_dbi::ProgrammingError: Statement Execute Failed: [IBM][CLI Driver][DB2] SQL0440N **No authorized routine named "RANDOM" of type** "" having compatible arguments was found.

Instead of using random() function, we tried running the query as : 
select rxcod_opp_id , rand() as idx from SYSADM.RXCOD_OPP_DEFN_TBL order by idx asc fetch first 10 rows only ;

This is working fine. Please find screenshot below : 

<img width="1380" alt="Screenshot 2023-11-01 at 3 40 31 PM" src="https://github.com/GoogleCloudPlatform/professional-services-data-validator/assets/124554976/16514b2c-af2e-4149-a637-147e923d850a">

Is it possible to modify DB2 code as per above format so that DB2(zos) start supporting random rows with custom query.

**Comment by nehanene15** [comment]
We don't support DB2 ZOS, but you can update [this line](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/feb2829d0f0e8d502aa1e4f10091efc73028a315/third_party/ibis/ibis_db2/registry.py#L450) in your environment to the following to fix this error:
```
return sa.func.rand()
```

We can't make this change on our side since there is no way of detecting which DB2 version a user is validating and LUW is more commonly used.

**Comment by helensilva14** [comment]
@nehanene15 probably we should update our docs stating the support for these versions, right now is just saying DB2 without specifications, what do you think?

**Comment by manojredward** [comment]
Hello @madhu-jain 
We are also facing the same error. Could you please share me detail how you resolved this error? Did you made the recommended changes from the Google team?

**Comment by manojredward** [comment]
@nehanene15 @helensilva14 
We are using LUW DB2 and still facing the same error.08/22/2024 05:13:45 PM-ERROR: Error (ibm_db_dbi.ProgrammingError) ibm_db_dbi::ProgrammingError: Statement Execute Failed: [IBM][CLI Driver][DB2] SQL0440N  No authorized routine named "RANDOM" of type "" having compatible arguments was found.  SQLSTATE=42884 SQLCODE=-440

**Comment by nehanene15** [comment]
> @nehanene15 @helensilva14 We are using LUW DB2 and still facing the same error.08/22/2024 05:13:45 PM-ERROR: Error (ibm_db_dbi.ProgrammingError) ibm_db_dbi::ProgrammingError: Statement Execute Failed: [IBM][CLI Driver][DB2] SQL0440N No authorized routine named "RANDOM" of type "" having compatible arguments was found. SQLSTATE=42884 SQLCODE=-440

Is the RANDOM() function supported in your DB2 instance? It should be for LUW DB2...

**Comment by helensilva14** [comment]
> We don't support DB2 ZOS, but you can update [this line](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/feb2829d0f0e8d502aa1e4f10091efc73028a315/third_party/ibis/ibis_db2/registry.py#L450) in your environment to the following to fix this error:
> 
> ```
> return sa.func.rand()
> ```
> 
> We can't make this change on our side since there is no way of detecting which DB2 version a user is validating and LUW is more commonly used.

Reopened because the same error is still happening as reported in issue #1239 even though it is a LUW version that is supported by DVT. We'll be changing the implementation to be using `RAND()` as default since the method is always available in all DB2 versions.
