### ISSUE TITLE
Teradata-BigQuery validation with json config

### ISSUE THREAD

**Issue by elena-gottardi-nttdata** [GoogleCloudPlatform/professional-services-data-validator#1021]
I am trying to compare a Teradata table (source) with a BigQuery table (target) using a json file as configuration.

Json used is the following:
`{
    "type": "Schema",
    "source_conn": 
        {
            "source_type": "Teradata",
            "host": "<host>",
            "port": "<port>",
            "user_name": "<user_name>",
            "password": "<psw>"
        },
    "target_conn": {
        "source_type": "BigQuery",
        "project_id": "<project_id>",
        "google_service_account_key_path": null
    },
    "schema_name":"<source_schema>",
    "table_name":"<source_table>",
    "target_schema_name":"<target_schema>",
    "target_table_name":"<target_table>",
    "result_handler":{
        "type":"BigQuery",
        "project_id":"<project_id>",
        "table_id":"<table_id>"
    },
    "exclusion_columns": [<list_of_columns_to_exclude>]
}`

For BigQuery tables, we have set as target_schema_name "project_id.dataset" and as target_table_name "table_id".

For Teradata, we have set as schema_name the teradata dataset name and as table_name the table name.

Unfortunately, I got the following error:
`pandas.errors.DatabaseError: Execution failed on sql '
HELP COLUMN **_table_name_**.*;
    ': [Version 17.20.0.31] [Session 676412] [Teradata Database] [Error 3807] Object '**_table_name_**' does not exist.`

NB: bold and italic words are our hidden table names.

How can we add the Teradata dataset name in a json as configuration?

Thank you.

**Comment by sundar-mudupalli-work** [comment]
Elena,

Not a direct answer to your question - since I am not familiar with the json config capability myself. However, this might be useful. We recently (Oct 16!) implemented a capability to pass JSON parameters which are directly passed along to the [teradatasql](https://pypi.org/project/teradatasql/#ConnectionParameters) library.

Check the documentation [here](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/docs/connections.md#teradata) and see if you can use that to pass parameters to the library.

If this is useful please download the latest develop branch to try this feature.

Thank you for using DVT.

Sundar Mudupalli

**Comment by helensilva14** [comment]
Hi @elena-gottardi-nttdata! You did it correctly actually, below I show you an example of it. 

So I'd recommend you to make sure you're passing the Teradata's database name in the right capitalization (lower/uppercase), if no line break is being added by mistake, as well as making sure the database you're passing really contains the table name you're listing.

Regardless, let us know if even after checking all of it you still have problems, so can further investigate!

`$ data-validation validate column -sc teradata -tc teradata -tbls Sys_Calendar.CALENDAR`

```json5
{
    "type": "Column",
    "source_conn_name": "teradata",
    "target_conn_name": "teradata",
    "table_name": "CALENDAR",
    "schema_name": "Sys_Calendar",
    "target_schema_name": "Sys_Calendar",
    "target_table_name": "CALENDAR",
    "labels": [],
    "threshold": 0.0,
    "format": "table",
    "result_handler": None,
    "filters": [],
    "use_random_rows": False,
    "random_row_batch_size": None,
    "filter_status": None,
    "aggregates": [
        {
            "source_column": None,
            "target_column": None,
            "field_alias": "count",
            "type": "count"
        }
    ]
}
```

And thanks @sundar-mudupalli-work for mentioning the new feature!
