### ISSUE TITLE
DVT using a proxy

### ISSUE THREAD

**Issue by elena-gottardi-nttdata** [GoogleCloudPlatform/professional-services-data-validator#1022]
I am trying to compare a Teradata table (source) with a BigQuery table (target) using a json file as configuration.

DVT doesn't reach BigQuery from the machine where DVT is run.

Is there any way to use a proxy with DVT?
Maybe from the configuration file or an environment variable such as HTTPS_PROXY?

Thank you.

**Comment by sundar-mudupalli-work** [comment]
Elena,

DVT uses Google Cloud BigQuery Client library - you can check that in [here](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/setup.py)

According to this [stackoverflow post](https://stackoverflow.com/questions/51038887/python-access-google-cloud-storage-using-proxy-server) the user was able to set up an environment variable for the https proxy and it worked.

I have not tried it myself (requires me to set up a proxy server). Will this work for you ?

Sundar Mudupalli

**Comment by helensilva14** [comment]
Thanks for the suggestion, @sundar-mudupalli-work!

@elena-gottardi-nttdata could you please share what is the error you're facing? It can help us understand and investigate your problem better.

And assuming it's for the same case as #1021, I'd check the role and permissions for the given Service Account as well if the key file is correctly configured.
