### ISSUE TITLE
connect DVT from one VM to the airflow dag in another VM

### ISSUE THREAD

**Issue by Dhivya-K** [GoogleCloudPlatform/professional-services-data-validator#1027]
Is there a way to start the DVT as service ? and connect this particular DVT from one instance to another . 
Basically I install , DVT in a machine A . From Machine B ,  I need to access this . 
is there any configuration to  increase the performance ? 

What I could I sense is when I import the dependencies and call the dvtConnection , I presume it is running a local instance . 
I need it in a scaled set up . How could we achieve this ? Kindly help here

**Comment by helensilva14** [comment]
Hi @Dhivya-K, thanks for reaching out! We currently have these options, please take a look to check if they can help you:

- Cloud Run: https://github.com/GoogleCloudPlatform/professional-services-data-validator/tree/develop/samples/run#data-validation-on-cloud-run 
- Cloud Functions: https://github.com/GoogleCloudPlatform/professional-services-data-validator/tree/develop/samples/functions#data-validation-on-cloud-functions
- Airflow/Composer: https://github.com/GoogleCloudPlatform/professional-services-data-validator/tree/develop/samples/airflow#data-validation-on-airflow-ideally-cloud-composer

**Comment by Dhivya-K** [comment]
Will try and let you know . Thanks for the response @helensilva14

**Comment by Dhivya-K** [comment]
Hi @helensilva14  and Team , 
Hi Team , 

  Say I want to run this dag https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/samples/airflow/dvt_airflow_dag.py  and I wanted to install the DVT in a data proc cluster , and use those configurations in the airflow vm . Basically I wanted to do a one to one comparison of data . I understand DVT uses inmemory . But my use case is to compare one to one data validation .  I could see there is a extras "pyspark"  in setup.py . Is there a way to start a spark session ? I wanted to compare petabytes of data. What would be the approach or config or set up needed to run this ?  with airflow , I could see 6 minutes for validating millions of records but cloud function takes a day . 

with ibis , we can send a spark session .  since DVT internally uses , ibis , is there a way similar ? 


Kindly help in this .

**Comment by helensilva14** [comment]
Hi @Dhivya-K!

We're understanding that you are looking for a distributed option to run DVT and that's how Spark/Dataproc was brought to the conversation. We don't support PySpark right now, but we are working on Apache Beam/Dataflow support.

Does it answer your main question? Let me know what else we can help with!

**Comment by nehanene15** [comment]
We also support [distributing DVT with GKE](https://github.com/GoogleCloudPlatform/professional-services-data-validator?tab=readme-ov-file#scaling-dvt-to-run-10s-to-1000s-of-validations-concurrently) now. Are you still seeing an issue with the airflow DAGs?
