### ISSUE TITLE
validate custom-query row: cannot validate a decimal column from Oracle source

### ISSUE THREAD

**Issue by dominikhron** [GoogleCloudPlatform/professional-services-data-validator#1033]
Please help me find a data validation command using the custom query row which would successfully validate a decimal column from an Oracle source with a BigQuery target. For the commands I've tried so far, the decimal number was returned with a comma separator from Oracle, resulting in a validation failure. Below are the tables and data I am using together with the commands I have tried so far:

**Oracle source** table:
```sql
CREATE TABLE EDWCDC_OWN.DVT_TEST_DECIMAL
(
	ROW_ID VARCHAR2(50),
	DECIMAL_COL NUMBER(22, 7)
);

INSERT INTO EDWCDC_OWN.DVT_TEST_DECIMAL
VALUES ('1-1ROW-ID', 3123.75);
```

**BigQuery target** table:
```sql
create table vfcz_dh_edw_adhoc_dev_01_s.dvt_test_decimal
(
	row_id string,
	decimal_col numeric,
);

insert into vfcz_dh_edw_adhoc_dev_01_s.dvt_test_decimal
values ('1-1ROW-ID', 3123.75);
```

First, I verified the column is interpreted correctly by itself with an **ad-hoc query**:
```
data-validation query -c MY_OC_CONN -q "SELECT row_id, CAST(decimal_col AS FLOAT) AS decimal_col FROM EDWCDC_OWN.DVT_TEST_DECIMAL WHERE  ROW_ID = '1-1ROW-ID'"
```
```
[('1-1ROW-ID', 3123.75)]
```

Then, I ran the data validation **custom-query row** command which fails due to the decimal in Oracle being replaced by a comma:
```
data-validation validate custom-query row -sc MY_OC_CONN -tc MY_BQ_CONN --source-query "SELECT row_id, decimal_col FROM EDWCDC_OWN.DVT_TEST_DECIMAL WHERE ROW_ID = '1-1ROW-ID'" --target-query "SELECT row_id AS row_id, CAST(decimal_col AS NUMERIC) AS decimal_col FROM vfcz_dh_edw_adhoc_dev_01_s.dvt_test_decimal WHERE ROW_ID = '1-1ROW-ID'" -pk row_id --concat *
```
```
╒═══════════════════╤═══════════════════╤═════════════════════╤══════════════════════╤════════════════════╤════════════════════╤══════════════════╤═════════════════════╤══════════════════════════════════════╕
│ validation_name   │ validation_type   │ source_table_name   │ source_column_name   │ source_agg_value   │ target_agg_value   │ pct_difference   │ validation_status   │ run_id                               │
╞═══════════════════╪═══════════════════╪═════════════════════╪══════════════════════╪════════════════════╪════════════════════╪══════════════════╪═════════════════════╪══════════════════════════════════════╡
│ concat__all       │ Custom-query      │                     │ concat__all          │ 1-1ROW-ID3123,75   │ 1-1ROW-ID3123.75   │                  │ fail                │ 56dcd874-539d-4610-aec0-f06708644ae7 │
╘═══════════════════╧═══════════════════╧═════════════════════╧══════════════════════╧════════════════════╧════════════════════╧══════════════════╧═════════════════════╧══════════════════════════════════════╛
```

Next, I tried **casting the column to NUMBER in Oracle**, which also fails:
```
data-validation validate custom-query row -sc MY_OC_CONN -tc MY_BQ_CONN --source-query "SELECT row_id, CAST(decimal_col AS NUMBER) AS decimal_col FROM EDWCDC_OWN.DVT_TEST_DECIMAL WHERE ROW_ID = '1-1ROW-ID'" --target-query "SELECT row_id AS row_id, CAST(decimal_col AS NUMERIC) AS decimal_col FROM vfcz_dh_edw_adhoc_dev_01_s.dvt_test_decimal WHERE ROW_ID = '1-1ROW-ID'" -pk row_id --concat *
```
```
╒═══════════════════╤═══════════════════╤═════════════════════╤══════════════════════╤════════════════════╤════════════════════╤══════════════════╤═════════════════════╤══════════════════════════════════════╕
│ validation_name   │ validation_type   │ source_table_name   │ source_column_name   │ source_agg_value   │ target_agg_value   │ pct_difference   │ validation_status   │ run_id                               │
╞═══════════════════╪═══════════════════╪═════════════════════╪══════════════════════╪════════════════════╪════════════════════╪══════════════════╪═════════════════════╪══════════════════════════════════════╡
│ concat__all       │ Custom-query      │                     │ concat__all          │ 1-1ROW-ID3123,75   │ 1-1ROW-ID3123.75   │                  │ fail                │ a8c1ae3b-4e3d-4c6e-819b-0dcdf445c56c │
╘═══════════════════╧═══════════════════╧═════════════════════╧══════════════════════╧════════════════════╧════════════════════╧══════════════════╧═════════════════════╧══════════════════════════════════════╛
```

Finally, I tired **casting the column to FLOAT in Oracle**, which gives me a ValueError in Python:
```
data-validation validate custom-query row -sc MY_OC_CONN -tc MY_BQ_CONN --source-query "SELECT row_id, CAST(decimal_col AS FLOAT) AS decimal_col FROM EDWCDC_OWN.DVT_TEST_DECIMAL WHERE  ROW_ID = '1-1ROW-ID'" --target-query "SELECT row_id AS row_id, CAST(decimal_col AS NUMERIC) AS decimal_col FROM vfcz_dh_edw_adhoc_dev_01_s.dvt_test_decimal WHERE  ROW_ID = '1-1ROW-ID'" -pk row_id --concat *
```
```
ValueError('Decimal type scale cannot be negative')
```

**Comment by helensilva14** [comment]
Hi @dominikhron! First of all, thank you for being so detailed on your issue, we really appreciate it!!! 

Which versions of DVT and Oracle are you using? Because I created the tables you provided, executed the first command you tried and I already got the Oracle value correctly with dot instead of comma. I used DVT 4.2.0 and Oracle 21, I'll try with Oracle 11g in a few. Please take a look below:

`data-validation validate custom-query row -sc oracle21 -tc bq --source-query "SELECT row_id, decimal_col FROM DVT_TEST.ISSUE1033_DVT_TEST_DECIMAL WHERE ROW_ID = '1-1ROW-ID'" --target-query "SELECT row_id AS row_id, CAST(decimal_col AS NUMERIC) AS decimal_col FROM dvt_test.ISSUE1033_DVT_TEST_DECIMAL WHERE ROW_ID = '1-1ROW-ID'" -pk row_id --concat '*'
`

![image](https://github.com/GoogleCloudPlatform/professional-services-data-validator/assets/37883833/2920945a-fd03-4535-9891-fff494ddfca2)

**Comment by helensilva14** [comment]
Update: same command also worked for Oracle 11g

**Comment by dominikhron** [comment]
Hi @helensilva14,

I'm using DVT version 4.2.0 and Oracle database version 19c with client 12.1. Does the cast to FLOAT on Oracle side (last command) work for you as well?

**Comment by helensilva14** [comment]
Just to make sure, I tried the 2nd command (casting the column to NUMBER in Oracle) and it works for both Oracle 21c and Oracle 11g.

`data-validation validate custom-query row -sc oracle21 -tc bq --source-query "SELECT row_id, CAST(decimal_col AS NUMBER) AS decimal_col FROM DVT_TEST.ISSUE1033_DVT_TEST_DECIMAL WHERE ROW_ID = '1-1ROW-ID'" --target-query "SELECT row_id AS row_id, CAST(decimal_col AS NUMERIC) AS decimal_col FROM dvt_test.ISSUE1033_DVT_TEST_DECIMAL WHERE ROW_ID = '1-1ROW-ID'" -pk row_id --concat '*'`

But for the 3rd command (casting the column to FLOAT in Oracle) I also got the same ValueError for both Oracle versions.

`data-validation validate custom-query row -sc oracle21 -tc bq --source-query "SELECT row_id, CAST(decimal_col AS FLOAT) AS decimal_col FROM DVT_TEST.ISSUE1033_DVT_TEST_DECIMAL WHERE  ROW_ID = '1-1ROW-ID'" --target-query "SELECT row_id AS row_id, CAST(decimal_col AS NUMERIC) AS decimal_col FROM dvt_test.ISSUE1033_DVT_TEST_DECIMAL WHERE  ROW_ID = '1-1ROW-ID'" -pk row_id --concat '*'`

Doing some investigation on that matter, I found [this article](https://database.guide/how-to-format-a-number-with-a-comma-in-oracle/), could you please check what do you get when executing this query on Oracle?

```
SQL> SELECT VALUE FROM V$NLS_PARAMETERS WHERE PARAMETER = 'NLS_NUMERIC_CHARACTERS';

VALUE
----------------------------------------------------------------
.,
```

It means my decimal character is represented by a dot/period and the group separator is represented by a comma.

**Comment by juraj-kugla** [comment]
Hi @helensilva14 .

I am working with @dominikhron and have tested your suggestion. After adding NLS parameter NLS_NUMERIC_CHARACTERS to system variables, the custom-query validation finished successfully.

I wanted to ask, if there is a way to set the NLS parameter as a session parameter, when DVT is accessing the Oracle db, as I want to have it set up differently for other tasks and don't want to change the system variable when launching the tool.

Thank you,

Juraj

**Comment by helensilva14** [comment]
Hi @juraj-kugla!, very happy to hear it worked! 

About setting this parameter for the session, @nj1973 is gonna take a look because it seems possible, but we do need to execute some tests. We'll provide updates once we have it!

**Comment by nj1973** [comment]
Hi @juraj-kugla , @dominikhron . I've pushed a fix for this, if it does not work for you please re-open this issue.
Thanks for informing us of this problem.
