### ISSUE TITLE
Getting [ibis.common.exceptions.OperationNotDefinedError: No translation rule for <class 'ibis.expr.operations.IfNull'>] error while running a row hash validation for all rows.

### ISSUE THREAD

**Issue by Jyotirm0y** [GoogleCloudPlatform/professional-services-data-validator#1040]
We are trying to check for row hash validation for all rows with a numeric primary key using GCP DVT whose source is MySQL and the target is bigquery, we have a proper schema match, and we don't have any null values in the table.
But we are getting this below error when we are trying to hash the columns:
ibis.common.exceptions.OperationNotDefinedError: No translation rule for <class 'ibis.expr.operations.IfNull'>

code:
data-validation validate row --source-conn mysql_CONN_NAME --target-conn bq_conn --tables-list testdb.bhandset_code_sql_new=$projectid.dbbqq.bhandset_code_test --primary-keys id --hash '*'

We found out from the dvt google product page https://cloud.google.com/blog/products/databases/automate-data-validation-with-dvt that Row-level Hash comparison is only valid for BigQuery and we are also able to successfully get a row hash validation between two BigQuery tables. 
But in the https://www.cloudskillsboost.google/focuses/45997?parent=catalog , they are able to make a Hash comparison between a hive table and a bq table.

In the Dvt GitHub link https://github.com/GoogleCloudPlatform/professional-services-data-validator#custom-query-row-validations it mentions a parameter "--concat COLUMNS " which is not recognized by DVT and it's giving an error data-validation: error: unrecognized arguments: --concat  id.

**Comment by nehanene15** [comment]
I believe you are running an older version of the tool and therefore hitting errors due to unsupported features.
Could you upgrade to the latest with `pip install google-pso-data-validator` and try again?

**Comment by nj1973** [comment]
@Jyotirm0y, I believe upgrading resolved this issue, is that correct?
