### ISSUE TITLE
row data comparison in Teradata fails due to case sensitive comparison on column names

### ISSUE THREAD

**Issue by paolocanaletti** [GoogleCloudPlatform/professional-services-data-validator#1044]
python 3.9.18
DVT 4.2

The use case is to compare Teradata with BQ, where Teradata has column in both upper and lowercase meanwhile BQ always lowercase. To simplify DVT configuration everything has been defined in lowercase. 
Column validation and Schema validation are working properly because they are not case sensitive.

Row data comparison instead is failing with the following:

`ibis.common.exceptions.IbisTypeError: Column '**rsn_desc**' is not found in table. Existing columns: 'RSN_CD', '**RSN_DESC**'.`
full stack trace below

Considering that Google Big Query migration assessment tool used to copy structure and metadata from Teradata to BQ is by default converting table and column name in lowercase is it possible to perform this check case insensitive as like as all the others? it will dramatically simplify the configuration of the validation of migrated data considering we have to apply it to hundreds of tables.

validation is invoked passing the json configuration directly to the python library:
```
json_config = json.loads(jtq)
validator = DataValidation(json_config)
df = validator.execute()
```

stack trace:
```
Traceback (most recent call last):
  File "/opt/SP/dvt/validate.py", line 268, in <module>
    validate()
  File "/opt/SP/dvt/validate.py", line 255, in validate
    df = validator.execute()
  File "/opt/rh/rh-python39/Python-3.9.18/venv/lib/python3.9/site-packages/data_validation/data_validation.py", line 89, in execute
    result_df = self.execute_recursive_validation(
  File "/opt/rh/rh-python39/Python-3.9.18/venv/lib/python3.9/site-packages/data_validation/data_validation.py", line 232, in execute_recursive_validation
    self._execute_validation(
  File "/opt/rh/rh-python39/Python-3.9.18/venv/lib/python3.9/site-packages/data_validation/data_validation.py", line 270, in _execute_validation
    source_query = validation_builder.get_source_query()
  File "/opt/rh/rh-python39/Python-3.9.18/venv/lib/python3.9/site-packages/data_validation/validation_builder.py", line 363, in get_source_query
    query = self.source_builder.compile(self.validation_type, table)
  File "/opt/rh/rh-python39/Python-3.9.18/venv/lib/python3.9/site-packages/data_validation/query_builder/query_builder.py", line 499, in compile
    table = table.projection(self.compile_comparison_fields(table))
  File "/opt/rh/rh-python39/Python-3.9.18/venv/lib/python3.9/site-packages/data_validation/query_builder/query_builder.py", line 461, in compile_comparison_fields
    return [field.compile(table) for field in self.comparison_fields]
  File "/opt/rh/rh-python39/Python-3.9.18/venv/lib/python3.9/site-packages/data_validation/query_builder/query_builder.py", line 461, in <listcomp>
    return [field.compile(table) for field in self.comparison_fields]
  File "/opt/rh/rh-python39/Python-3.9.18/venv/lib/python3.9/site-packages/data_validation/query_builder/query_builder.py", line 201, in compile
    comparison_field = ibis_table[self.field_name]
  File "/opt/rh/rh-python39/Python-3.9.18/venv/lib/python3.9/site-packages/ibis/expr/types/relations.py", line 469, in __getitem__
    return ops.TableColumn(self, what).to_expr()
  File "/opt/rh/rh-python39/Python-3.9.18/venv/lib/python3.9/site-packages/ibis/common/grounds.py", line 25, in __call__
    return cls.__create__(*args, **kwargs)
  File "/opt/rh/rh-python39/Python-3.9.18/venv/lib/python3.9/site-packages/ibis/common/grounds.py", line 99, in __create__
    return super().__create__(**kwargs)
  File "/opt/rh/rh-python39/Python-3.9.18/venv/lib/python3.9/site-packages/ibis/common/grounds.py", line 33, in __create__
    return type.__call__(cls, *args, **kwargs)
  File "/opt/rh/rh-python39/Python-3.9.18/venv/lib/python3.9/site-packages/ibis/expr/operations/generic.py", line 39, in __init__
ibis.common.exceptions.IbisTypeError: Column '**rsn_desc**' is not found in table. Existing columns: 'RSN_CD', '**RSN_DESC**'.
```

**Comment by nehanene15** [comment]
Is the JSON config for a hash validation or a comparison field validation? 
Hash validations with the CLI (`data-validation validate row ... -c config.yaml`) should build a YAML config with the proper casing between source and target. 
Comparison field validations rely on the user to provide the correct casing in the `source_column_name` and `target_column_name` fields in the config.

**Comment by nehanene15** [comment]
Following up on this - are you still encountering this issue?

**Comment by paolocanaletti** [comment]
Hi, 
yes I am still having the same problem, but I am still using DVT 4.2. Is there any improvement in the latest 4.3 version?

I am not using CLI, but invoking directly the python method and there is no plan to change the way we use it.

I am not getting why with Custom Query, Column validation and Schema validation the comparison is case insensitive meanwhile with Field Validation it is case sensitive.
Unfortunately Google Big Query migration tool is converting everything in lowercase instead of maintaining the same case of the source.
I see an inconsistency in the tools provided to migrate DB and to validate the data are properly moved.
I have to compare thousand of tables, having to provide the correct casing is a mess.

Is it possible to evaluate this as an enhancement that will strongly improve the usability of the tool?

**Comment by helensilva14** [comment]
> Is the JSON config for a hash validation or a comparison field validation? Hash validations with the CLI (`data-validation validate row ... -c config.yaml`) should build a YAML config with the proper casing between source and target. Comparison field validations rely on the user to provide the correct casing in the `source_column_name` and `target_column_name` fields in the config.

Hi @paolocanaletti, thanks a lot for your response! As @nehanene15 asked and explained last year, could you please tell us if you tried to execute which one of these row validation types: hash or comparison field? Because it determines how casing is handled. Also could you please share your JSON config with us so we can better help you? (PS: remember to anonimize any sensitive information)

We didn't change any of this logic in version 4.3. No problems about using our lib directly in your Python code, you can keep this approach! The suggestion here is to execute the command using CLI in a separate env/shell just to get the generated YAML which can help you get the fields and values needed to fill up the JSON config in your code. Valid to mention we're working on providing a specific feature for JSON config generation on this issue #908.

 By looking at your JSON config we can definitely better analyze if there's room to make changes to enhance the casing definition!

**Comment by paolocanaletti** [comment]
I was using row comparison without hash, then I switched to custom query to make it works.

Previously TD table were uppercase and BQ table lowercase, now I did another test, converting both source and target all uppercase (table name and column name) and using custom query.
The only way I found to make it works in to use the following config where custom query is uppercase as like as the tables but the list of columns is lowercase.

```
{
	"type": "Custom-query",
	"source_conn": {
		"source_type": "Teradata",
		"host": "xxxx",
		"port": "1025",
		"user_name": "xxxx",
		"password": "xxxx"
	},
	"target_conn": {
		"source_type": "BigQuery",
		"project_id": "projectid",
		"google_service_account_key_path": "/path/to/SA.json"
	},
	"schema_name": "TeradataDB",
	"table_name": "TABLE",
	"target_schema_name": "projectid.dataset",
	"target_table_name": "TABLE",
	"result_handler": {
		"type": "BigQuery",
		"project_id": "projectid",
		"table_id": "dataset.dvt_results"
	},
	"custom_query_type": "row",
	"source_query": "select top 100 A,B from TeradataDB.TABLE where C <= xxxx order by A",
	"target_query": "select A,B from `projectid.dataset.TABLE` where C <= xxxx order by A limit 100",
	"primary_keys": [
		{
			"source_column": "a",
			"target_column": "a",
			"field_alias": "a",
			"cast": null
		}
	],
	"comparison_fields": [
		{
			"source_column": "b",
			"target_column": "b",
			"field_alias": "b",
			"cast": null
		}
	]
}
```

if I change the config with the column uppercase like 

```
"primary_keys": [
		{
			"source_column": "A",
			"target_column": "A",
			"field_alias": "A",
			"cast": null
		}
	],
	"comparison_fields": [
		{
			"source_column": "B",
			"target_column": "B",
			"field_alias": "B",
			"cast": null
		}
	]
```

then I have again 
`ibis.common.exceptions.IbisTypeError: Column 'A' is not found in table. Existing columns: 'a', 'b'.`
