### ISSUE TITLE
DVT Cannot connect to oracle .Connection Type "Oracle" could not connect: (cx_Oracle.DatabaseError) Error while trying to retrieve text for error ORA-01804

### ISSUE THREAD

**Issue by Nireeksha17** [GoogleCloudPlatform/professional-services-data-validator#1056]
Connection Type "Oracle" could not connect: (cx_Oracle.DatabaseError) Error while trying to retrieve text for error ORA-01804
(Background on this error at: https://sqlalche.me/e/14/4xp6)

**Comment by helensilva14** [comment]
Hi @Nireeksha17! It's an error within the database itself and not the interface or data being passed. 

I suggest you to try some of the solutions listed here https://stackoverflow.com/q/12837811 or there https://github.com/oracle/python-cx_Oracle/issues/632 and let us know if something works!

**Comment by Nireeksha17** [comment]
hi Helen,

Stackoverflow solution is not working for me . https://github.com/oracle/python-cx_Oracle/issues/632 . 

Operating System used is Ubuntu

Instaclient Paths below
export ORACLE_HOME=usr/lib/oracle/instantclient_19_21
export LD_LIBRARY_PATH=$ORACLE_HOME/lib:$LD_LIBRARY_PATH
export PATH=$ORACLE_HOME/bin:$PATH

**Comment by helensilva14** [comment]
I see, well I'm still analyzing what it can be. 

@nj1973 or @sundar-mudupalli-work, I'd appreciate any thoughts on this issue, thank you!

**Comment by nj1973** [comment]
Hi @Nireeksha17 , which files did you include in your instant client directory?

In mine I unzipped:
```
unzip instantclient-basic-linux.x64-19.19.0.0.0dbru.zip
unzip instantclient-sqlplus-linux.x64-19.19.0.0.0dbru.zip
unzip instantclient-tools-linux.x64-19.19.0.0.0dbru.zip
```

In my instant client directory the library files are not in a lib subdirectory therefore `LD_LIBRARY_PATH` = `$ORACLE_HOME` for me:

```
export ORACLE_HOME=/home/foo/instantclient_19_19
export PATH=$PATH:$ORACLE_HOME
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ORACLE_HOME
```

Hope this helps.

**Comment by Nireeksha17** [comment]
Hello Neil,

I have included same whatever I previously posted.

**Comment by helensilva14** [comment]
Hi @Nireeksha17! 

According to an internal contact at Google that's supporting you, this problem got resolved by setting the path `LD_LIBRARY_PATH={pwd}`, right? I'll close it as resolved for now, but you can reopen the issue if needed.

**Comment by Nireeksha17** [comment]
Hi Helen,

The issue is resolved. Thank for the solution
