### ISSUE TITLE
connection to Impala failed while using a json file as configuration

### ISSUE THREAD

**Issue by elena-gottardi-nttdata** [GoogleCloudPlatform/professional-services-data-validator#1069]
I'm using DVT with python and I'm trying to connect to Hive using a json file as configuration for schema validation, as follows:
{
   "type":"Schema",
   "source_conn":{
      "source_type":"Impala",
      "host":"HOST_NAME",
      "port":"N_PORT",
      "database":"DB_NAME",
      "user":"USER_NAME",
      "password":"PASSWORD",
      "ca_cert":"CA_CERT",
      "use_ssl":true
   },
   "target_conn":{
      "source_type":"BigQuery",
      "project_id":"PROJECT_ID",
      "google_service_account_key_path":"GOOGLE_SA_JSON"
   },
   "schema_name":"",
   "table_name":"",
   "target_schema_name":"TARGET_SCHEMA_NAME",
   "target_table_name":"TARGET_TABLE_NAME",
   "result_handler":{
      "type":"BigQuery",
      "project_id":"PROJECT_ID",
      "table_id":"DATASET.TABLE"
   },
   "exclusion_columns":[
      
   ]
}

I'm getting the following error:
`  File "/opt/rh/rh-python39/Python-3.9.18/venv/lib/python3.9/site-packages/data_validation/data_validation.py", line 61, in __init__
    self.config_manager = ConfigManager(config, verbose=self.verbose)
  File "/opt/rh/rh-python39/Python-3.9.18/venv/lib/python3.9/site-packages/data_validation/config_manager.py", line 58, in __init__
    self.source_client = source_client or clients.get_data_client(
  File "/opt/rh/rh-python39/Python-3.9.18/venv/lib/python3.9/site-packages/data_validation/clients.py", line 257, in get_data_client
    raise exceptions.DataClientConnectionFailure(msg)
data_validation.exceptions.DataClientConnectionFailure: Connection Type "Impala" could not connect: unexpected exception`

Am I writing something wrong?

Thanks

**Comment by helensilva14** [comment]
Is it possible for you to try using the same parameter values within a default DVT CLI command? Something `data-validation validate row...`, so you could check it you can actually connect to this Hive instance regardless of the JSON configuration.

Also I would suggest to review our connection instructions to use Hive, maybe you might need to use other parameters or your current env does not check the requirements: https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/docs/connections.md#hive
