### ISSUE TITLE
Comma separated list of primary keys

### ISSUE THREAD

**Issue by mayanksroy01** [GoogleCloudPlatform/professional-services-data-validator#1077]
If any column in the comma separated list provided in primary keys is null, will DVT still produce correct results.
I'm getting some incorrect results for my use case when one column is null.

**Comment by nehanene15** [comment]
What type of incorrect results are you seeing?

DVT requires a unique primary key - if you have a composite PK and one of the columns being NULL creates a duplicate PK, the results may be incorrect.

**Comment by helensilva14** [comment]
Hi @mayanksroy01, any updates on this issue? Were you able to check Neha's comment? Thanks!
