### ISSUE TITLE
Increase Oracle SQL Alchemy arraysize

### ISSUE THREAD

**Issue by nj1973** [GoogleCloudPlatform/professional-services-data-validator#1086]
The default arraysize on an Oracle cursor is 50. It is common to increase this for applications that fetch many rows from Oracle.

I did some testing row hash validating a 1 million row Oracle table with PostgreSQL. Timings below:

Default arraysize:
```
real	0m51.717s
user	0m31.320s
sys	0m4.952s

real	0m51.475s
user	0m31.027s
sys	0m4.822s
```
Average: 51.5s

arraysize=500:
```
real	0m43.210s
user	0m30.662s
sys	0m4.435s

real	0m43.390s
user	0m30.652s
sys	0m4.601s
```
Average: 43.3s (-15%)

arraysize=1000:
```
real	0m44.232s
user	0m30.789s
sys	0m6.459s

real	0m42.280s
user	0m30.242s
sys	0m4.824s
```
Average: 43.3 (-15%)

This is the change we can make to implement this:
```
$ git diff
diff --git a/third_party/ibis/ibis_oracle/__init__.py b/third_party/ibis/ibis_oracle/__init__.py
index aa2c259..5360e42 100644
--- a/third_party/ibis/ibis_oracle/__init__.py
+++ b/third_party/ibis/ibis_oracle/__init__.py
@@ -55,7 +55,7 @@ class Backend(BaseAlchemyBackend):
             sa_url = sa.engine.url.make_url(url)

         self.database_name = sa_url.database
-        engine = sa.create_engine(sa_url, poolclass=sa.pool.StaticPool)
+        engine = sa.create_engine(sa_url, poolclass=sa.pool.StaticPool, arraysize=500)
```

**Comment by CMaxK** [comment]
@nj1973 happy to take this on!

**Comment by nj1973** [comment]
Thanks @CMaxK, much appreciated.

I believe you will need to fork the project, perform the changes in that fork and then open a PR in this repo to bring the changes back in. Apologies if you already knew this, it will be educational for me as I've not been involved in this process before.
