### ISSUE TITLE
Run Validation using SQL Statement instead of Table

### ISSUE THREAD

**Issue by dhercher** [GoogleCloudPlatform/professional-services-data-validator#109]
Ibis SQL Clients have a function `Client.sql(query) -> IbisTable`.  This can be used to some degree to replace a table object and execute validations against raw sql objects

https://github.com/ibis-project/ibis/blob/dccaec86cba4a08b6d1b04d235a7f9bd4928506f/ibis/client.py#L161

**Comment by nehanene15** [comment]
Using this for custom query validation for Issue #315
