### ISSUE TITLE
Snowflake DECIMAL casting when running row validation with concat

### ISSUE THREAD

**Issue by henrihem** [GoogleCloudPlatform/professional-services-data-validator#1109]
When running row validation and there is DECIMAL(p,s) in Snowflake and NUMERIC(p,s) in BigQuery, the concat and hash will create different results due to how Snowflake handles DECIMAL.

Running test:
```
data-validation validate row \
  -sc bq_conn \
  -tc sf_conn \
  -tbls tst.TEST=tst.TEST  \
  --concat order_number,invoice_sum,status \
  --primary-keys order_number,account \
  -rr \
  -rbs 100
```

BigQuery DDL:
```
create table tst.TEST (
    order_number STRING,
    account STRING,
    invoice_sum NUMERIC(10,2),
    status STRING
);
```

Snowflake DDL:
```
create table tst.TEST (
    order_number STRING,
    account STRING,
    invoice_sum DECIMAL(10,2),
    status STRING
);
```

Example results:
Snowflake:
`22777.10`

BigQuery:
`22777.1`

In a nutshell: 
If Snowflake has DECIMAL(10,5), the string representation is 10.00000 for 10 and 10.12000 for 10.12
If BigQuery has NUMERIC(10,5) (or DECIMAL), the string representation is 10 and 10.12 for 10.12

**Comment by sundar-mudupalli-work** [comment]
Hi,

Just for the reasons you point out - treating numeric as string is not a great idea. A better approach is to cast it into something that is meaningful for you from a business perspective. For example if the data is holding currency, you may only care about the first two digits of precision. If it is holding latitude or longitude, you will want more digits of precision. You could write a [custom query validation](https://github.com/GoogleCloudPlatform/professional-services-data-validator?tab=readme-ov-file#custom-query-column-validations) where you custom query transforms the decimal into a string for comparison. It may also be possible to use [Calculated Fields](https://github.com/GoogleCloudPlatform/professional-services-data-validator?tab=readme-ov-file#calculated-fields), though I am not very familiar with that feature.

Let me know if that resolves your issue.

Sundar Mudupalli

**Comment by nj1973** [comment]
I'll have a look at this. We had a similar issue in the past with PostgreSQL conversions from decimal to string.

**Comment by nj1973** [comment]
Better testing has highlighted that we have this same issue on MySQL too.

**Comment by nj1973** [comment]
@henrihem thanks for highlighting this, it has identified a flaw in our tests which I've now also fixed. Hopefully the fix unblocks decimal validations for you.
