### ISSUE TITLE
Filters not working correctly in Snowflake

### ISSUE THREAD

**Issue by henrihem** [GoogleCloudPlatform/professional-services-data-validator#1115]
There are some issues when comparing Snowflake to BigQuery or vice-versa.
It seems the where-condition does not work correctly to Snowflake.

Command I used for row validations:
```
data-validation validate row \
  -sc bq_conn \
  -tc sf_conn \
  -tbls schema.TABLE1=schema.TABLE1 \
  --concat column1,column2,column3 \
  --primary-keys unique_key \
  --filters 'date(load_dt)=current_date':'date("LOAD_DT")=current_date' \
  --config-file filters.yaml
```

BigQuery:
```
SELECT t4.`concat__all`, t4.`unique_key`
FROM (
  SELECT t3.*,
         ARRAY_TO_STRING([t3.`upper__rstrip__ifnull__cast__column1`, t3.`upper__rstrip__ifnull__cast__column2`, t3.`upper__rstrip__ifnull__cast__column3`], '') AS `concat__all`
  FROM t3
) t4
WHERE date(load_dt)=current_date
```
==> This work fine. There is t3.*, so load_dt is correctly queried.

Snowflake:
```SQL
SELECT t5."concat__all", t5."unique_key" 
FROM (SELECT t4."concat__all" AS "concat__all", t4."UNIQUE_KEY" AS "unique_key" 
FROM t4) AS t5 
WHERE date("LOAD_DT")=current_date
```
==> This does not work fine, as "LOAD_DT" is not queried from t4. 

DDL for the tables:
BigQuery:
```
create table TABLE1 (
   unique_key STRING,
   column1 STRING,
   column2 STRING,
   column3 STRING,
   load_dt DATETIME
)
```

Snowflake:
```
create table TABLE1 (
   unique_key STRING,
   column1 STRING,
   column2 STRING,
   column3 STRING,
   load_dt DATETIME
)
```

**Comment by helensilva14** [comment]
Hi @henrihem! 

It seems to be a problem with the quotation marks you used, I was able to execute it successfully by passing this format below:

`  --filters "date(load_dt)=current_date":"date('LOAD_DT')=current_date" \`

Could you please try it out and let us know if it works?

**Comment by helensilva14** [comment]
Just updated my comment bc I tested SF to BQ first

**Comment by henrihem** [comment]
This doesn't make a difference:
`--filters "date('LOAD_DT')=current_date":"date(load_dt)=current_date"`
From SF to BQ.

The query it generates:
```
SELECT t5."concat__all", t5."unique_key" 
FROM (SELECT t4."concat__all" AS "concat__all", t4."UNIQUE_KEY" AS "unique_key" 
FROM t4) AS t5 
WHERE date('LOAD_DT')=current_date
```
Can't work in that case, cause there really isn't LOAD_DT column from that t5.
