### ISSUE TITLE
Does dvt_airflow_dag.py support to have oracle as source connection?

### ISSUE THREAD

**Issue by simzo10** [GoogleCloudPlatform/professional-services-data-validator#1125]
I have installed the cx_Oracle library and the oracle instant client, setting up an oracle connection in the Airflow Connections and setting up an oracle home and LD_LIBRARY_PATH on the server where Airflow ran.

Can you tell me how to adjust the dvt_airflow_dag.py to have an OR_CONN as source_conn? @nj1973 @nehanene15

**Comment by nj1973** [comment]
Hi @simzo10 , I've not used the Airflow script before but I imagine the format should be something like this: 

```
OR_CONN = {
    "source_type": "Oracle",
    "host": oracle_host,
    "user": dvt_user_name,
    "password": dvt_user_pass,
    "port": 1521,
    "database": oracle_service,
}
```

Ensuring you set appropriate values for `oracle_host`, `dvt_user_name`, `dvt_user_pass` and `oracle_service`.

Or did I misunderstand the problem?

**Comment by simzo10** [comment]
Thanks for replying @nj1973. This is exactly what I've done, but my Airflow DAG is failing with this error: **DataClientConnectionFailure: Connection Type "Oracle" could not connect: pip install cx_Oracle**. This error is generated by the data_validation/clients.py script line 254. 
Please note that I've already installed cx_Oracle.

**Comment by nj1973** [comment]
Thanks, it appears that the Python where DVT is installed is not the same one that you installed cx_Oracle into. Can you check you are running the script in the same vitualenv that has cx_Oracle installed?

As I said before I've not used Airflow previously so perhaps @nehanene15 will have some insight to share once her day starts.

**Comment by simzo10** [comment]
Thank you @nj1973, I will check if the cx_Oracle library is installed in the virtual environment where DVT runs, and I'll get back to you.

**Comment by helensilva14** [comment]
Hi @simzo10! Since our sample runs DVT using the `PythonVirtualenvOperator`, I would check if adding the library `cx_Oracle` as a second requirement at this line https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/samples/airflow/dvt_airflow_dag.py#L93 would solve the issue. 

If not, my next recommendation would see if you can still the library in the Airflow cluster, probably it uses a Docker image or something in that sense that you can specify libraries you need for the Airflow environment.

**Comment by simzo10** [comment]
Hi @helensilva14, the issue is solved by adding cx_Oracle as a second requirement to the line you mentioned. Big Thanks!!

**Comment by helensilva14** [comment]
No problem, glad it worked, thanks for reaching out!
