### ISSUE TITLE
How can we perform validation between SQL and BQ for max(date) from a table

### ISSUE THREAD

**Issue by pavannadgoudar** [GoogleCloudPlatform/professional-services-data-validator#1131]
How can we perform validation between SQL and BQ for max(date) from a table:
We copy historically ingested data from source(SQL) to Datalake(BQ) during Migration so we dont want to compare this data(it is in millions and billions).

We want to compare the data for a particular date or more precisely max(date) from table. How can we apply this condition during data validation.

data-validation validate row --source-conn MSSQL--target-conn BQ --tables-list <SQLTable>=<BQTable> --filter-status fail --primary-keys <PrimaryKey> -comp-fields <ComparisonColumn> --bq-result-handler <DVT Results Table>

**Comment by nehanene15** [comment]
You can do MAX aggregations with column validation like so:
`data-validation validate column -sc MSSQL -tc BQ -tbls source=target --filter-status fail -max date_col -bqrh result.table`

You can also run sum, min, avg, and more listed [here](https://github.com/GoogleCloudPlatform/professional-services-data-validator?tab=readme-ov-file#column-validations)

**Comment by nj1973** [comment]
If you also want to avoid scanning the historic data and only validate newer data you can use the `--filters` option. Something like:
```
--filters 'date_column>date'2020-01-01'
```

**Comment by nehanene15** [comment]
@pavannadgoudar Did this answer your question? If so, I can close this issue.

**Comment by pavannadgoudar** [comment]
@nehanene15 @nj1973  Thanks for your inputs. It helped. We are able to validate only the data loaded on max(date). Please close this issue.

**Comment by nj1973** [comment]
Thanks for the update @pavannadgoudar
