### ISSUE TITLE
Trailing whitespace on PK filters in YAMLs from generate-partitions command 

### ISSUE THREAD

**Issue by franklinWhaite** [GoogleCloudPlatform/professional-services-data-validator#1179]
Similar to https://github.com/GoogleCloudPlatform/professional-services-data-validator/issues/1151

YAML's created with generate-partition will show literals with trailing whitespaces in filters for String type columns. This is causing undesired behavior (e.g. records being excluded from validation).

**Comment by nehanene15** [comment]
Closed with #1182
