### ISSUE TITLE
[TD to BQ] Unable to validate TIME fields

### ISSUE THREAD

**Issue by franklinWhaite** [GoogleCloudPlatform/professional-services-data-validator#1189]
We are unable to run validations on tables containing fields with `TIME` datatype in TD vs BQ.

TD DDL:
```
CREATE TABLE time_field_bug (
    id INTEGER,
    time_field TIME(0)
);
```

BQ DDL
```
CREATE OR REPLACE TABLE dataset.time_field_bug (
    id INTEGER,
    time_field TIME
);
```

Error:
`[Teradata Database] [Error 3800] Datatype Mismatch in THEN/ELSE expression.`

**Comment by sundar-mudupalli-work** [comment]
Hi,

This is related to [Timestamp issue with time zone](https://github.com/GoogleCloudPlatform/professional-services-data-validator/issues/929). Please review comments there.

At this time, we don't support the SQL TIME data type in our code - will investigate workarounds first.

Sundar Mudupalli
