### ISSUE TITLE
[TD] Invalid literal for pk filter in YAML from generate-partitions using date field as pk 

### ISSUE THREAD

**Issue by franklinWhaite** [GoogleCloudPlatform/professional-services-data-validator#1191]
When using Teradata as a source and using DATE field as primary key the generate table partitions commands will generate a yaml with a filter field like the one below

```
filters:
  - source: date_field <='2025-07-03'
    target: date_field <='2025-07-03'
    type: custom
  - source: ' ( date_field <= ''2025-07-03'' ) AND ( "date_field" < ''2024-01-20T00:00:00''
      )'
    target: ' ( date_field <= ''2025-07-03'' ) AND ( `date_field` < CAST(''2024-01-20
      00:00:00'' AS DATETIME) )'
    type: custom
```

The  `"date_field" < ''2024-01-20T00:00:00''` filter is not valid and will cause the following error on TD:

`teradatasql.OperationalError: [Version 20.0.0.12] [Session 4806] [Teradata Database] [Error 3535] A character string failed conversion to a numeric value.`

**Comment by sundar-mudupalli-work** [comment]
Impacted by [PR 1219](https://github.com/GoogleCloudPlatform/professional-services-data-validator/pull/1219). Upgrade first to latest develop branch
