### ISSUE TITLE
[TD to BQ] Teradata padding issue while comparing strings

### ISSUE THREAD

**Issue by paraschavda2411** [GoogleCloudPlatform/professional-services-data-validator#1217]
As comparing date in primary keys was creating this issue:  https://github.com/GoogleCloudPlatform/professional-services-data-validator/issues/1193#issuecomment-2264711015 

In order to resolve that we used casting and to_char to convert date to string while comparing source [teradata] to bigquery [destination] 

While testing it seems Teradata string values were having padding to the end. hence validation was failing eventhough the data was correctly matching.
![image](https://github.com/user-attachments/assets/efc46f17-9be5-44c0-8f61-cc3f98d4cfff)

This should help you recreate this issue : 

### Teradata

CREATE TABLE DB.test_2
 (src_cd SMALLINT NOT NULL,
  sub_src_cd SMALLINT NOT NULL,
  veh_company BYTEINT NOT NULL,
  veh_serial_no CHAR(17) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
  eff_dt DATE FORMAT 'YYYY-MM-DD' NOT NULL,
  bus_type CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS,
  cantype CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS,
  delinq_date DATE FORMAT 'YYYY-MM-DD' COMPRESS
  );

insert into DB.test_2 values(26, 529, 1, '1fa6gsgsdg160qw', '2019-06-03', 'NV','','0001-01-01');
insert into DB.test_2 values(26, 529, 1, '1fa6gsgsdg160qw', '2019-07-14', 'NV','','0001-01-01');
insert into DB.test_2 values(26, 529, 1, '1fa6gsgsdg160qw', '2019-09-17', 'NV','','0001-01-01');

### BigQuery 

create table `dataset.test_2`
 (src_cd INT64 ,
  sub_src_cd INT64,
  veh_company INT64,
  veh_serial_no STRING(17),
  eff_dt DATE,
  bus_type STRING(2),
  cantype STRING(1),
  delinq_date DATE
)
;

insert into `dataset.test_2` values(26, 529, 1, '1fa6gsgsdg160qw', '2019-06-03', 'NV','','0001-01-01');
insert into `dataset.test_2` values(26, 529, 1, '1fa6gsgsdg160qw', '2019-07-14', 'NV','','0001-01-01');
insert into `dataset.test_2` values(26, 529, 1, '1fa6gsgsdg160qw', '2019-09-17', 'NV','','0001-01-01');

### DVT Command
data-validation -v validate custom-query row \
-sc TD_CONN \
-tc bq_conn \
--source-query "select src_cd, sub_src_cd, veh_company, veh_serial_no, to_char(eff_dt,'YYYY-MM-DD') as eff_dt, bus_type, cantype, to_char(delinq_date, 'YYYY-MM-DD') as delinq_date from DB.test_2" \
--target-query "select src_cd, sub_src_cd, veh_company, veh_serial_no, cast(eff_dt as string) as eff_dt, bus_type, cantype, cast(delinq_date as string) as delinq_date from project.dataset.test_2" \
--primary-keys src_cd,sub_src_cd,veh_company,veh_serial_no,eff_dt \
-comp-fields bus_type,delinq_date -bqrh project.dataset.dvt_results

**Comment by nehanene15** [comment]
Could you try with adding the `--trim-string-pks` flag in the DVT custom query row command?

**Comment by paraschavda2411** [comment]
Here is the command that I used to test it with this flag : 

data-validation -v validate custom-query row \
--trim-string-pks \
-sc TD_CONN \
-tc BQ_CONN \
--source-query "select src_cd, sub_src_cd, veh_company, veh_serial_no, to_char(eff_dt,'YYYY-MM-DD') as eff_dt, bus_type, cantype, to_char(delinq_date, 'YYYY-MM-DD') as delinq_date from DB.test_2" \
--target-query "select src_cd, sub_src_cd, veh_company, veh_serial_no, cast(eff_dt as string) as eff_dt, bus_type, cantype, cast(delinq_date as string) as delinq_date from project.dataset.test_2" \
--primary-keys src_cd,sub_src_cd,veh_company,veh_serial_no,eff_dt \
-comp-fields **bus_type**,delinq_date \
-bqrh project.dataset.dvt_results


This is still creating padding on teradata for one of the "comp_fields : bus_type"
