### ISSUE TITLE
Aggregation for all the columns through YAML file

### ISSUE THREAD

**Issue by manojredward** [GoogleCloudPlatform/professional-services-data-validator#1236]
Hi Team,
We are facing an issue while constructing the YAML file for running sum aggregation on all columns from the table. We have tested with command line and able to execute that.
**data-validation validate column -sc bq -tc bq -tbls table.test1=table.test2 --sum '*'** 

and also,
We have generated the yaml file by passing -c test.yaml flag on it. In that we have renamed the source and target columns as * to pull all the columns and we know this is not the correct way. Please help us to generate the YAML for all the columns.

**test.yaml file**
result_handler: {}
source: bq
target: bq
validations:
- aggregates:
  - field_alias: count
    source_column: *
    target_column: *
    type: count
  - field_alias: sum__id
    source_column: *
    target_column: *
    type: sum
  case_insensitive_match: false
  filter_status: null
  filters: []
  format: table
  labels: []
  random_row_batch_size: null
  schema_name: dp-dev-curated-5fb7.dvt
  table_name: test1
  target_schema_name: dp-dev-curated-5fb7.dvt
  target_table_name: test2
  threshold: 0.0
  trim_string_pks: false
  type: Column
  use_random_rows: false

**Comment by nj1973** [comment]
After generating your YAML file using the command line you should not need to edit the column names in the YAML file.

Below is an example command :
```
$ data-validation validate column -sc=ora -tc=bq \
-tbls=pso_data_validator.dvt_core_types --sum='*' \
--config-file=/tmp/dvt-sum.yaml
08/22/2024 03:58:11 PM-INFO: Success! Config output written to /tmp/dvt-sum.yaml
```

If I look in the YAML file all columns are individually listed:
```
$ head -20 /tmp/dvt-sum.yaml
result_handler: {}
source: ora_local
target: bq_dbbb
validations:
- aggregates:
  - field_alias: count
    source_column: null
    target_column: null
    type: count
  - field_alias: sum__id
    source_column: id
    target_column: id
    type: sum
  - field_alias: sum__col_int8
    source_column: col_int8
    target_column: col_int8
    type: sum
  - field_alias: sum__col_int16
    source_column: col_int16
    target_column: col_int16
```

Did I misunderstand what you are trying to achieve?

**Comment by manojredward** [comment]
Hello @helensilva14 @nj1973 
We are able to use '*' in the command line and execute it. 

```
$ data-validation validate column -sc=ora -tc=bq \
-tbls=pso_data_validator.dvt_core_types --sum='*' \
--config-file=/tmp/dvt-sum.yaml
08/22/2024 03:58:11 PM-INFO: Success! Config output written to /tmp/dvt-sum.yaml
```

Here, '*' is used to pull all the numeric columns by default and generate the yaml file. My questions, is there any similar way to pull all the numeric column aggregation directly in yaml. Because we are feeding the pre-created yaml file into dvt and executing it. We don't want to manually add all the numeric columns in yaml.

Please let us know how to pull all the numeric column aggregation directly in yaml.

**Comment by helensilva14** [comment]
Hi @manojredward! @nj1973's comment described perfectly the situation here, in summary you already have your situation solved. 

Your initial command `data-validation validate column -sc bq -tc bq -tbls table.test1=table.test2 --sum '*' -c test.yaml` already outputs a YAML file containing each table column individually listed and that's the way our configuration file needs to be structured so DVT can read it properly during execution. It is not possible to have a single block representing all your columns, DVT needs to know exactly all the column names in both source and target, since they can be different sometimes.

**Comment by helensilva14** [comment]
Closing question-labeled issue since responses and clarification were already provided.
