### ISSUE TITLE
Dry Run option for executing DVT as a cloud run job

### ISSUE THREAD

**Issue by manojredward** [GoogleCloudPlatform/professional-services-data-validator#1237]
Hi Team,

We are running the DVT as cloud run job and the connections and input yaml files are stored in GCS bucket and we are referring the connection home from PSO_DV_CONN_HOME. We explored there is an option for using --dry-run in command line and the output gives the underlined executed query. When we try to use the dry-run flag in out input yaml file, we are unable to get the results.

Please suggest the way to pass the --dry-run flag in yaml format and execute it as a cloud run job.

**Comment by manojredward** [comment]
And also Please guide us on How to persist the generated output in a JSON format?

**Comment by nehanene15** [comment]
When you generate the YAML command, you can add the JSON format like so: `data-validation validate column ... --format json -c config.yaml`. Now when you run the YAML, the output will be in JSON format.

For dry-run, you can do the following: `data-validation configs run --dry-run -c config.yaml`.

**Comment by kudaravalligopi** [comment]
Is there a way to persist the SQL query JSON output from dryrun as a file (like GCS file path), particulary when we run this as Cloud Run Job?

**Comment by helensilva14** [comment]
> Is there a way to persist the SQL query JSON output from dryrun as a file (like GCS file path), particulary when we run this as Cloud Run Job?

Hi @kudaravalligopi! This is more a matter of Cloud Run/Python implementation code than related to DVT itself. I found this post that might be helpful, please take a look: https://stackoverflow.com/questions/59799941/writing-a-new-file-to-a-google-cloud-storage-bucket-from-a-google-cloud-function

**Comment by helensilva14** [comment]
Closing question-labeled issue since responses and clarification were already provided.
