### ISSUE TITLE
Filter is not working with Datetime in column validation

### ISSUE THREAD

**Issue by paraschavda2411** [GoogleCloudPlatform/professional-services-data-validator#1255]
`--filters "update_timestamp >= '2024-04-01 16:00:00 UTC'"`

when specified with column validation option it does not work and throws,
` ValueError("Unable to parse filter arguments.") line 1090, in get_filters`
 
Its splitting the timestamp into multiple values due to colon, --filter is trying to split the timestamp assuming there are source and target filters (as per the documentation --filter can be used with **source_filter : target_filter** )

it seems issue is with this line :https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/d01a40b14e5e090c1a99aa44fd8625fa8e515427/data_validation/cli_tools.py#L1073 

its not allowing to escape/handle the colons.

**Comment by nehanene15** [comment]
Can you try the following: `--filters 'update_timestamp >= "2024-04-01 16:00:00 UTC" '`

**Comment by paraschavda2411** [comment]
Using : `--filters 'update_timestamp >= "2024-04-01 16:00:00 UTC" '`
it produces same error
