### ISSUE TITLE
Error while validating Postgres BOOLEAN datatype with Teradata CHAR datatype in row validation

### ISSUE THREAD

**Issue by madhu-jain** [GoogleCloudPlatform/professional-services-data-validator#1262]
Customer facing another issue while validating Postgres with Teradata. They've a column,ISCURRENTFORTYPE, defined boolean in Postgres and CHAR(1) in Teradata. When they're validating this column using comp field comparison using below command, it's throwing error : 

data-validation validate row \
--source-conn pg_conn \
--target-conn td_conn \
--tables-list public.eodassetlocation=Z_OD_ALF_LIVE_M_Q.Z0325_ODSASSETLOC_CURR \
-tsp \
--primary-keys ID \
--comparison-fields ID,ASSETID,ISCURRENTFORTYPE \
--bq-result-handler prj-dfdl-528-fcmis-d-528.bq_dvt_validation_results_raw.bq_postgres_td_dvt_validation_results \
-l Tables=public.eodassetlocation:Z_OD_ALF_LIVE_M_Q.Z0325_ODSASSETLOC_CURR,run_date=20240910-1

**Error :** 
ibis.common.exceptions.IbisTypeError: Given arguement with datatype boolean is not implicitly castable to string.

Later they created a view on TD to type cast column ISCURRENTFORTYPE to BYTEINT and used view in DVT validation. Got below error : 

**TypeError:** Arguments differences_target_value:int64 and differences_source_value:boolean are not comparable

**Comment by madhu-jain** [comment]
I tried reproducing the issue at my end. Please find below details : 

**--Postgres :** 

CREATE TABLE test_boolean (
    id INT,
    name varchar(20),
    curr_type bool
);

insert into test_boolean (id,name, curr_type) values (1, 'Mike', '1');
insert into test_boolean (id,name, curr_type) values (2, 'Sam', '0');
insert into test_boolean (id,name, curr_type) values (3, 'Phil', '1');

postgres=> select * from test_boolean;
 id | name | curr_type 
----+------+-----------
  1 | Mike | t
  2 | Sam  | f
  3 | Phil | t
(3 rows)

**--Teradata :** 

CREATE TABLE retail.test_boolean (
    id INT,
    name varchar(20),
    curr_type CHAR(1)
);

insert into retail.test_boolean (id,name,curr_type) values (1, 'Mike', '1');
insert into retail.test_boolean (id,name,curr_type) values (2, 'Sam', '0');
insert into retail.test_boolean (id,name,curr_type) values (3, 'Phil', '1');

select * from retail.test_boolean order by id;

 *** Query completed. 3 rows found. 3 columns returned. 
 *** Total elapsed time was 1 second.

         id  name                  curr_type
-----------  --------------------  ---------
          1  Mike                      1
          2  Sam                      0
          3  Phil                       1


**--Running validation command :** 

data-validation validate row \
--source-conn PG_CONN \
--target-conn TD_CONN \
--tables-list public.test_boolean=retail.test_boolean \
-tsp \
--primary-keys id \
--comparison-fields name,curr_type \
--bq-result-handler paras-sandbox-364713.data_validator.dvt_results


**Error :** 

File "/home/dvt/venv/lib/python3.11/site-packages/toolz/functoolz.py", line 304, in __call__
    return self._partial(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dvt/venv/lib/python3.11/site-packages/ibis/expr/rules.py", line 270, in value
    raise com.IbisTypeError(
ibis.common.exceptions.IbisTypeError: Given argument with datatype boolean is not implicitly castable to string

**Comment by madhu-jain** [comment]
**CHAR(1)** column (**curr_type**) casted to **BYTEINT** in Teradata view definition and view is used in DVT command : 

create view retail.vw_test_boolean as select id, name, cast(curr_type as BYTEINT) as curr_type from retail.test_boolean

**DVT Command :** 

data-validation validate row \
--source-conn PG_CONN \
--target-conn TD_CONN \
--tables-list public.test_boolean=retail.vw_test_boolean \
-tsp \
--primary-keys id \
--comparison-fields name,curr_type \
--bq-result-handler paras-sandbox-364713.data_validator.dvt_results

**Error :** 

File "/home/dvt/venv/lib/python3.11/site-packages/ibis/common/grounds.py", line 33, in __create__
    return type.__call__(cls, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dvt/venv/lib/python3.11/site-packages/ibis/expr/operations/logical.py", line 65, in __init__
    raise TypeError(
TypeError: Arguments differences_target_value:int64 and differences_source_value:boolean are not comparable

**Comment by sundar-mudupalli-work** [comment]
Hi,

Since Teradata has no concept of boolean, you have to convert the Boolean type into something that Teradata understands - i.e. char or byte int. I have used the char conversion in the example below and used a custom query. Does that work
```
data-validation validate custom-query row -sc my_postgres -tc teradata -pk id --hash '*' -sq 'select id, name, case curr_type when '"'"'true'"'"' then '"'"'1'"'"' else '"'"'0'"'"' end as curr_type from mudupalli.test_boolean' -tq 'select id, name, curr_type from udf.test_boolean'
```
You have to modify this to suit your environment - connection paramters, table name etc. The five character `'"'"'` is how you can escape the `'` in shell. 

Thanks.

Sundar Mudupalli

**Comment by nj1973** [comment]
There's still an issue here. I tested with source connection Teradata and target PostgreSQL. If I swap them around the command fails with:
```
TypeError: Arguments differences_target_value:float64 and differences_source_value:boolean are not comparable
```
There's something Teradata specific in the code that is not checking source & target. I need to go find it.
