### ISSUE TITLE
test: Validate all integration tests with Python 3.11

### ISSUE THREAD

**Issue by helensilva14** [GoogleCloudPlatform/professional-services-data-validator#1321]
Adding 3.11 and 3.12 to the Python versions list on `noxfile.py` will need to be addressed in a separate issue because first we need to make sure all clients work properly for each one of the versions. So far, I was able to get errors from Oracle and Hive with 3.12. And since we randomly choose a Python version for each system, it's not something that we can have certainty right now on when it will be selected or not.

_Originally posted by @helensilva14 in https://github.com/GoogleCloudPlatform/professional-services-data-validator/issues/1303#issuecomment-2462420861_

**Comment by nj1973** [comment]
Repurposing this issue to add Python 3.11 to our tests. Python 3.12 is now in issue: https://github.com/GoogleCloudPlatform/professional-services-data-validator/issues/1344

**Comment by nj1973** [comment]
I made a mistake in my testing of Python 3.11. I was sure I'd tested all with 3.11 but Oracle integration testing is now failing with:
```
textPayload: "Step #10 - "integration_oracle": nox > Session integration_oracle failed: Python interpreter 3.11 not found."
```

Re-opening this issue.
