### ISSUE TITLE
Enable Levenshtein distance comparison between string fields

### ISSUE THREAD

**Issue by dhaval-d** [GoogleCloudPlatform/professional-services-data-validator#136]
For data validation, it would be nice to have an ability to find a Levenshtein distance between two strings. This could help understand the similarity of two string fields.

Python package already available: https://pypi.org/project/python-Levenshtein/

**Comment by nehanene15** [comment]
For comparing string fields, we now support comparison fields for an exact string match or using string length() column aggregations. Please re-open if the current functionality is not sufficient.
