### ISSUE TITLE
FR: Ability to compare results of queries across databases

### ISSUE THREAD

**Issue by dhaval-d** [GoogleCloudPlatform/professional-services-data-validator#155]
One of the customer has a request to provide support to compare the results of queries across source and target databases. 

It seems like Ibis doesn't have any support for that. However, Ibis leverages SQLAlchemy under the hood. Hence, we can build  a wrapper around a SELECT query and store it in a table using SQLAlchemy in both source and target databases. Once tables are stored, we can use existing features of the tool to compare two tables.

**Comment by nehanene15** [comment]
This is now supported with custom query. Close with PR #390
