### ISSUE TITLE
FR: Support COUNT_DISTINCT validation

### ISSUE THREAD

**Issue by dhaval-d** [GoogleCloudPlatform/professional-services-data-validator#164]
Can we add COUNT_DISTINCT validation to the tool? It seems like ibis already has expressions for this. Also, a customer was asking for this validation to validate their primary keys(single column and multiple columns).

**Comment by sramsrinivasan** [comment]
The ticket was originally created under the assumption that an COUNTD (or its equivalent) function was readily available in ibis but upon analyzing we found that more manual customizations were needed to get this functionality to work. Can close this ticket as 'Not Planned'

**Comment by sramsrinivasan** [comment]
The ticket was originally created under the assumption that an COUNTD (or its equivalent) function was readily available in ibis but upon analyzing we found that more manual customizations were needed to get this functionality to work. Can close this ticket as 'Not Planned'
