### ISSUE TITLE
Teradata numeric overflow for count validation

### ISSUE THREAD

**Issue by oapa** [GoogleCloudPlatform/professional-services-data-validator#207]
Encountered a Teradata numeric overflow error below when trying to run "count" validation on a table.  According to [this post](https://downloads.teradata.com/forum/database/2616-numeric-overflow-occurred-during-computation-1), it looks like count(*) can overflow on Teradata since it implicitly casts to INT.

```
pandas.io.sql.DatabaseError: Execution failed on sql 'SELECT count(*) AS "count", count("id") AS "count__id",
 ......
FROM {td_schema}.{td_table}
SAMPLE 10000': [Version 17.0.0.8] [Session 31075829] [Teradata Database] [Error 2616] Numeric overflow occurred during computation
```

**Comment by nehanene15** [comment]
This is now possible with the `--cast-to-bigint` flag and via [YAML](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/docs/examples.md#sample-yaml-with-calc-fields-cast-to-numeric-before-aggregation). This will cast any int32 columns to int64 before running an aggregation. Closed with PR #461
