### ISSUE TITLE
Validation Combiner Datatype Alignment Issues

### ISSUE THREAD

**Issue by dhercher** [GoogleCloudPlatform/professional-services-data-validator#211]
This ticket is intended to track issues joining different data types between the many different data sources and types we work with.

Currently our pandas logic forces all unknown or un-joinable data types to raw objects to avoid causing errors.  This behavior should be improved over time.

Examples to consider:
https://github.com/GoogleCloudPlatform/professional-services-data-validator/pull/210

**Comment by nehanene15** [comment]
PR #470 resolves issues with decimals (unsupported pandas type). If issues with other data types are encountered, we can open a separate issue for tracking.
