### ISSUE TITLE
Allow a Max Failures Flag for CLI

### ISSUE THREAD

**Issue by dhercher** [GoogleCloudPlatform/professional-services-data-validator#215]
Add a flag into the CLI which will allow X failures to occur before failing the entire validation.

`data-validation run --yaml file.yaml --max-failures 10`
Default: No max failures

This feature enables us to run through many validations without causing constant blocks for temporal issues.  It also allows us to highlight which validations are failing at once rather than by running through them all until you hit an issue.

**Comment by nehanene15** [comment]
Added better error handling to partially address this.
Can re-open if we see demand for this; since we don't 'stream' validation results row-by-row we would still end up running the whole table validation with failures. Typically customers validate one table per YAML
