### ISSUE TITLE
cleanup spanner connector to delete duplicate code from google-cloud-spanner library

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/professional-services-data-validator#225]
Once the following PRs are merged and released, we can delete the duplicate code from the spanner connector:

- [x] `list_tables()` https://github.com/googleapis/python-spanner/pull/219 (merged, but duplicate code not cleaned up)
- [ ] `to_dataframe()` https://github.com/googleapis/python-spanner/pull/226 (unmerged)

**Comment by nehanene15** [comment]
Duplicate code cleaned up for `list_tables()`. `to_dataframe()` seems like a stale PR. If it gets merged we can re-open this issue.
