### ISSUE TITLE
Tracking DVT Usage with GCS Connection Configs

### ISSUE THREAD

**Issue by dhercher** [GoogleCloudPlatform/professional-services-data-validator#229]
We want to be able to track DVT usage across all users once its made open source.

Our current method tracks when results are sent to BigQuery, but this is limited and will often not be the method a customer is using when they run the tool (currently all Oracle to Postgres usage is being missed, for example)

We want to add logic to track
- Each validation run that occurs
- what type of validation is happening
- Success/Failure

Other information might be interesting, but most other fields would be potentially PII.

Methods to track:
- Google Analytics

**Comment by nehanene15** [comment]
Use Secrets Integration (Issue #21) for tracking DVT usage

**Comment by nehanene15** [comment]
Tracking with Google Analytics was not approved; the API calls over the Internet would also cause a security concern for our enterprise consumers.
Instead, we can use PSO code tracking to track GCS API calls through the Cloud Storage [client library we instantiate](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/data_validation/state_manager.py#L136) in the state_manager class. 

In addition, add documentation that recommends GCS connection configs over local file configs
