### ISSUE TITLE
Allow user to specify a format for stdout

### ISSUE THREAD

**Issue by nehanene15** [GoogleCloudPlatform/professional-services-data-validator#242]
Currently, the default stdout output is not readable due to the large amount of fields we print. The user should be able to specify a `--format` flag similar to the [gcloud format flag](https://cloud.google.com/sdk/gcloud/reference#--format).

We can also trim down the amount of fields we output to stdout if they are user specified parameters.

**Comment by yogeshtewari** [comment]
Updated code to take in `--format` flag and pretty print formatted results on the console. Default format is tabular grid.
