### ISSUE TITLE
Enhance the tool to allow running schema validation as a part of tables data validation.

### ISSUE THREAD

**Issue by dhaval-d** [GoogleCloudPlatform/professional-services-data-validator#246]
We should enhance the tool to allow running schema validation as a part of table data validation. This enhancement should support following two options:

- Schema validation: Enforced - meaning if schema validation doesn't match, don't perform data validation
- Schema validation: warning only - meaning even if schema validation doesn't match, continue with data validation

We will need to introduce additional flags to achieve above.

**Comment by helensilva14** [comment]
Team agreed this feature wouldn't be that much useful as our users already can handle schema and other validations separately and this demand never really came up.
