### ISSUE TITLE
Docker Image Release Process

### ISSUE THREAD

**Issue by dhercher** [GoogleCloudPlatform/professional-services-data-validator#256]
Release a public docker image which anyone can use for OSS sources (will not work for third party non-imported code, the user can build their own in this case)

**Comment by nehanene15** [comment]
- Make a Artifact Registry repository and push a Docker image with DVT to it: https://cloud.google.com/artifact-registry/docs/docker/store-docker-container-images
- Allow public access to the repository with our image: https://cloud.google.com/artifact-registry/docs/access-control#public

**Comment by sramsrinivasan** [comment]
1. Create a docker repository (ex: pso-dvt-docker-repo) in artifact registry
2. There are 3 ways to create a docker image viz. (a) cloud build config (b) docker file (c) packs.
3. I chose Dockerfile method - 
4. cd samples/docker and then run ./build_docker.sh
5. tag docker image - docker tag data_validation:2.0.1 us-central1-docker.pkg.dev/pso-kokoro-resources/pso-dvt-docker-repo/professional-services-data-validator:latest
6. push the docker image - docker push us-central1-docker.pkg.dev/pso-kokoro-resources/pso-dvt-docker-repo/professional-services-data-validator:latest
7. pull the image for testing - docker pull us-central1-docker.pkg.dev/pso-kokoro-resources/pso-dvt-docker-repo/professional-services-data-validator:latest
8. test run the docker image - docker run -v ~/.config/:/root/.config --rm eaed085867cf -h

**Comment by SansBailmare** [comment]
> 1. Create a docker repository (ex: pso-dvt-docker-repo) in artifact registry
> 2. There are 3 ways to create a docker image viz. (a) cloud build config (b) docker file (c) packs.
> 3. I chose Dockerfile method -
> 4. cd samples/docker and then run ./build_docker.sh
> 5. tag docker image - docker tag data_validation:2.0.1 us-central1-docker.pkg.dev/pso-kokoro-resources/pso-dvt-docker-repo/professional-services-data-validator:latest
> 6. push the docker image - docker push us-central1-docker.pkg.dev/pso-kokoro-resources/pso-dvt-docker-repo/professional-services-data-validator:latest
> 7. pull the image for testing - docker pull us-central1-docker.pkg.dev/pso-kokoro-resources/pso-dvt-docker-repo/professional-services-data-validator:latest
> 8. test run the docker image - docker run -v ~/.config/:/root/.config --rm eaed085867cf -h

@nehanene15 /@sramsrinivasan
I have build the image , But I am not able to run it, I would appreciate your guidance in getting that image run..

Also,Would you please help me with sample config file where we can mention the conncetions, gcloud configs etc..
