### ISSUE TITLE
FR: Support Impala connection from CLI

### ISSUE THREAD

**Issue by nehanene15** [GoogleCloudPlatform/professional-services-data-validator#262]
The DVT supports Impala connections but it is not documented or supported via the CLI.

A user should be able to add a connection with this command: 
```
data-validation connections add --connection-name $IMPALA_CONN Impala --host $HOST --database $DATABASE --hdfs-client $CLIENT 
```

We should also document this connection type, as well as an example of connecting to Hive.

**Comment by danieldeleo** [comment]
Looks like supporting Impala connection will [also enable Hive](https://saagie.zendesk.com/hc/en-us/articles/360007829439-Read-Write-from-Hive) as a connection

**Comment by danieldeleo** [comment]
The following packages are necessary to use impala connection type:
* pip install thrift_sasl
* pip install hdfs

**Comment by danieldeleo** [comment]
I was able to create a hive connection type using the following command:

```
data-validation connections add -c hive Raw --json "$(cat hive.json)"
```

where hive.json contains the following:
```
{   
  "source_type": "Impala",
  "host": "HIVE_IP_ADDRESS",
  "port": 10000,
  "database": "default",
  "auth_mechanism":"PLAIN"
}
```
