### ISSUE TITLE
Allow users to pass json instead of comma-separated lists to --grouped_columns arg in CLI?

### ISSUE THREAD

**Issue by sarahspak** [GoogleCloudPlatform/professional-services-data-validator#276]
I've been seeing warnings when running `data-validation run -t GroupedColumn` w/ the cli
```
WARNING: Unknown cast types can cause memory errors
```

Looks like DVT allows for users to cast the type of grouped columns [here](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/ae076e52d91ea43e2d41fbf7535222e15c96f4ed/samples/bq_result_handler_grouped.py#L37) but it does not seem to be supported by the CLI.

Would be helpful if users could pass in a json like the one below
```
$GROUPED_COLS=[{"field_alias": "starttime","source_column": "starttime","target_column": "starttime","cast": "date",},]
``` 

to the cli

`data-validation run -t GroupedColumn -sc $BQ -tc $BQ -tbls "${source}"="${target}" --sum '*' --count '*' --grouped-columns "${GROUPED_COLS}" -bqrh "${MY_PROJECT}".pso_data_validator.results`

instead of being limited to passing in a list. 

Would be even better if users could have the option of setting cast equal to the source_column's data type.

**Comment by nehanene15** [comment]
One workaround for this is to save the validation in a config YAML file and edit the grouped column config there. Then, you can run the validation using `run-config`.

**Comment by nehanene15** [comment]
Not planned for now since we rely on YAML configs for more detailed casts.
