### ISSUE TITLE
Implement hashing algorithm on the Teradata connector

### ISSUE THREAD

**Issue by nehanene15** [GoogleCloudPlatform/professional-services-data-validator#299]
This issue is part of implementing heterogeneous row validation between Teradata and BQ (Issue #282).

- Look into using C plugins through SQL API
- Document the add ons necessary for Teradata connector hashing

**Comment by renzokuken** [comment]
C plugins are accessed via the SQL API. I've registered the functions for TD and need to setup a sandbox for testing
