### ISSUE TITLE
Add additional connection parameters for Hive connection

### ISSUE THREAD

**Issue by nehanene15** [GoogleCloudPlatform/professional-services-data-validator#308]
The Ibis impala connect() method supports `auth_mechanism` and 'kerberos_service_name` which should be configurable by the end user when creating a connection like so:
```
data-validation connections add --connection-name HIVE_SRC_CONN Impala --host <host_ip_address> --port <hive_conn_port> --database <hive_database> --auth-mechanism PLAIN --kerberos_service_name 'hive'
```

**Comment by liufeiyafly** [comment]
The `--kerberos_service_name 'hive'` is not correct. `kerberos_service_name` cannot contain any underline! `--kerberos-service-name 'hive'` is right.

**Comment by nehanene15** [comment]
> The `--kerberos_service_name 'hive'` is not correct. `kerberos_service_name` cannot contain any underline! `--kerberos-service-name 'hive'` is right.

To use this parameter, you would use `data-validation connections add ... --kerberos-service-name 'hive' ...`. The variable is stored as `kerberos_service_name` in the application when parsed with [argparse](https://docs.python.org/3/library/argparse.html).
