### ISSUE TITLE
add option to allow teeing of output to stdout in addition to sending the output to bigquery

### ISSUE THREAD

**Issue by pupamanyu** [GoogleCloudPlatform/professional-services-data-validator#310]
There are instances where validation tool may be used in a job workflow which relies on stdout(job log) for the troubleshooting of validation jobs. However it is not economical to force users to run a separate validation run for scenarios where the validation result also needs to be made available in bigquery for analytical purposes. I see that there are two result handlers(txt, bigquery). There is a need to enable teeing of result df output to stdout in addition to sending the output to bigquery within the bigquery result handler using only one invocation of DVT, and provide an option for enable such teeing.

**Comment by nehanene15** [comment]
We will be taking this into consideration as we are currently redesigning the result handler design. Thanks.
