### ISSUE TITLE
Error with Hive partitioned tables 'NoneType' object has no attribute lower

### ISSUE THREAD

**Issue by nehanene15** [GoogleCloudPlatform/professional-services-data-validator#314]
DVT is throws an exception when the date column is included in the tables since the 'date' data type is not supported in ibis open source. [(Link)](https://github.com/ibis-project/ibis/blob/master/ibis/backends/impala/udf.py#L368)

In addition, Hive partitioned tables are running into this Ibis issue: https://github.com/ibis-project/ibis/issues/1483

**Comment by ghost** [comment]
Any fix for this issue? Ibis doesn't work for partitioned Impala table.

**Comment by nehanene15** [comment]
No, since Ibis Impala does not support partitioned Hive tables, we will be building out a separate Hive connector.

**Comment by nehanene15** [comment]
> Any fix for this issue? Ibis doesn't work for partitioned Impala table.

No, since Ibis Impala does not support partitioned Hive tables, we will be building out a separate Hive connector.

**Comment by ghost** [comment]
i was able to fix this issue, by making same change in the source code, in client.py file, there was a function which was describing table and function was failing. with small fix in this function i was able to make it work for partitioned table aswell.

**Comment by nehanene15** [comment]
With this fix, have you seen any other issues with partitioned tables at a large scale?

**Comment by ghost** [comment]
Nothing as such until now...  everything is working fine..
