### ISSUE TITLE
Group By validation for Hive uses unsupported syntax

### ISSUE THREAD

**Issue by nehanene15** [GoogleCloudPlatform/professional-services-data-validator#319]
Ibis generates a group_by query like so:
```
SELECT `bikeid`, count(*) AS `count`
FROM `bigquery-public-data.new_york_citibike.citibike_trips`
GROUP BY 1
```
which is unsupported in Hive. Group_By requires the column name instead of the integer reference.

This will require overwritting the [fomrat_group_by()](https://github.com/ibis-project/ibis/blob/b00e4321a1dc9bee764be522967f2d562ebd8830/ibis/backends/base/sql/compiler/query_builder.py#L415) function in third_party/ibis/ibis_impala/compiler.py so that we can reference the column name.

**Comment by ghost** [comment]
I was able to solve this issue by setting below property in Hive
hive.groupby.orderby.position.alias=true

There are two approaches to set this property:
1. Pass this property as part of cluster creation
2. Run this command when you create hive connection in the source code. 

I followed approach 1 and it fixed the issue.
