### ISSUE TITLE
TeraDataClient is missing __enter__  - Leads custom TD queries to break

### ISSUE THREAD

**Issue by aymanfarhat** [GoogleCloudPlatform/professional-services-data-validator#331]
Trying to run a custom query against a Teradata source, the code seems to be breaking when trying to run `with client.raw_sql(args.query, results=True) as cur:` on [Line 268 in data_validation/__main__.py](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/0936d843c215ed8b6c81385175f23cf705278a9a/data_validation/__main__.py#L267)

What I'm running

```
data-validation query \
--conn TD_DVT \
--query "SELECT * FROM TEST_DB.USA_NAMES_SIMPLE"
```

Exception

```
Traceback (most recent call last):
  File "/teradata-experiments/tdvt/bin/data-validation", line 8, in <module>
    sys.exit(main())
  File "/teradata-experiments/tdvt/lib/python3.8/site-packages/data_validation/__main__.py", line 379, in main
    print(run_raw_query_against_connection(args))
  File "/teradata-experiments/tdvt/lib/python3.8/site-packages/data_validation/__main__.py", line 269, in run_raw_query_against_connection
    with client.raw_sql(args.query, results=True) as cur:
AttributeError: __enter__
```

Tracing this back in the code, it looks like [TeradataClient](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/0936d843c215ed8b6c81385175f23cf705278a9a/third_party/ibis/ibis_teradata/client.py#L61) class imported in [data_validation/clients.py](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/0936d843c215ed8b6c81385175f23cf705278a9a/data_validation/clients.py#L61) on line 61 does not implement a `__enter__` nor `__exit__` methods in order to be usable in a with statement, leading to the exception shared above.

Another thing to note, even if TeradataClient did implement `__enter__` it seems like `client.raw_sql` method returns a DataFrame. Which means, it could break again on the line below it `cur.fetchall()` since DataFrame does not have this function. On the other hand, in case of BigQuery, the value of cur will be a BigQueryCursor, hence `cur.fetchall` will work. So I guess an overall strategy on dealing with different return types from different clients will be needed here.

**Comment by nehanene15** [comment]
This is fixed with the Ibis upgrade PR #894
