### ISSUE TITLE
Add external support for DB2 connections

### ISSUE THREAD

**Issue by nehanene15** [GoogleCloudPlatform/professional-services-data-validator#356]
We have a method to connect to DB2 via the [third_party/ibis/ibis_DB2](https://github.com/GoogleCloudPlatform/professional-services-data-validator/tree/develop/third_party/ibis/ibis_DB2) directory, but we don't support connecting through the CLI. 

This needs to be built out and tested

**Comment by bnb01** [comment]
How's this coming?

**Comment by nehanene15** [comment]
This is currently being tested.

**Comment by ctezna-factored** [comment]
hi is there anything I can help with to get this feature out? I'm part of an organization looking to use this as soon as possible.

**Comment by nehanene15** [comment]
Hello, the ETA for this feature is 3-4 weeks. We are currently working on some debugging with the alchemy package before we push official support for DB2
