### ISSUE TITLE
Did not recognize type 'nvarchar2' of column 'SHORTNAME6'

### ISSUE THREAD

**Issue by anxinlk1** [GoogleCloudPlatform/professional-services-data-validator#361]
source: Oracle
target: GaussDB（Postgres）
The field type of the target library is nvarchar2. Does this tool not support it?

**Comment by nehanene15** [comment]
Ibis supports VARCHAR, but not NVARCHAR.

**Comment by nehanene15** [comment]
Ibis supports VARCHAR, but not NVARCHAR.
