### ISSUE TITLE
DVT tool taking only default schema 'dbo' for MSSQL for validation

### ISSUE THREAD

**Issue by LUJ20** [GoogleCloudPlatform/professional-services-data-validator#363]
DVT tool taking only default schema 'dbo' for MSSQL for validation

Example: I have a database named dvt,multiple shemas underneath like dbo,Sales,Person,...when I run validation it works only for dbo like below

> python3 -m  data_validation validate column -sc SQLServerSrc -tc SQLServerTgt -tbls dbo.ErrorLog

Error:pyodbc.ProgrammingError: ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot open database "dbo" requested by the login. The login failed. (4060) (SQLDriverConnect)')
**

> python3 -m  data_validation validate column -sc SQLServerSrc -tc SQLServerTgt -tbls dvt.ErrorLog

╒════╤═══════════════════╤═══════════════════╤═════════════════════╤══════════════════════╤════════════════════╤═════════════════════╤══════════════════════╤════════════════════╤════════════════════╤══════════════╤══════════════════╤══════════╕
│    │ validation_name   │ validation_type   │ source_table_name   │ source_column_name   │   source_agg_value │ target_table_name   │ target_column_name   │   target_agg_value │ group_by_columns   │   difference │   pct_difference │ status   │
╞════╪═══════════════════╪═══════════════════╪═════════════════════╪══════════════════════╪════════════════════╪═════════════════════╪══════════════════════╪════════════════════╪════════════════════╪══════════════╪══════════════════╪══════════╡
│  0 │ count             │ Column            │ dvt.ErrorLog        │                      │                  0 │ dvt.ErrorLog        │                      │                  0 │                    │            0 │              nan │ success  │
╘════╧═══════════════════╧═══════════════════╧═════════════════════╧══════════════════════╧════════════════════╧═════════════════════╧══════════════════════╧════════════════════╧════════════════════╧══════════════╧══════════════════╧══════════╛

It works only for default schema dbo but not for other schemas.Likewise I noticed a note stating for Postgres it takes 'Public' as default schema

MSSQL and POSTGRES should address all schema for validtaion

**Comment by dolonmukherji** [comment]
@LUJ20 how did you setup a connection for MSSQL?
I am using the below connection string
python -m data_validation connections add --connection-name PS_CONN MSSQL --host <host ip> --port <port> --user <user>    --password <pwd>  --database <dbname>

I am getting the error below:
 Connection Type "MSSQL" could not connect: (pyodbc.InterfaceError) ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')
