### ISSUE TITLE
Error validating when results export format is 'table'

### ISSUE THREAD

**Issue by rilkeanheart** [GoogleCloudPlatform/professional-services-data-validator#367]
When the format is changed to table, the data-validator returns an error based on line 
—-------------------------------------
46 in text.py:
KeyError: "['difference' 'labels' 'pct_threshold'] not found in axis"

The results are returned as expected for the other export formats

**Comment by ajwelch4** [comment]
@rilkeanheart Is this for a `schema` or `column` validation? Can you post the full traceback? This may be fixed by #371.
