### ISSUE TITLE
Schema validation generate wrong result if source column name is lower and target column name is upper

### ISSUE THREAD

**Issue by grzegorz-wasilewski** [GoogleCloudPlatform/professional-services-data-validator#385]
Hi,

I'm try to check schema validation in BigQuery source view vs target view. But in source i have lower name column and in target i have upper case name. If i run validation then i see "column<>COLUMN" and i have status FAILED :)

I made quic change in schema_validation.py and add some 2 lines and working:
```
def schema_validation_matching(source_fields, target_fields):
    """ Compare schemas between two dictionary objects """
    results = []
    # Go through each source and check if target exists and matches
    
   #----------- GW add START
    target_fields = {k.casefold(): v for k, v in target_fields.items()}
    source_fields** = {k.casefold(): v for k, v in source_fields.items()}
   #----------- GW add STOP

    for source_field_name, source_field_type in source_fields.items():
```

Please add a parameter to configuration maybe that I can choose if i want use lower or upper.
In documentation BigQuery - https://cloud.google.com/bigquery/docs/reference/standard-sql/lexical#case_sensitivity is see something like that:
`
Category | Case Sensitive?
Table names | Yes
Column names | No
`

Thanks,
Greg

**Comment by nehanene15** [comment]
Similar to Issue #495

**Comment by grzegorz-wasilewski** [comment]
Thanks 👍
