### ISSUE TITLE
Report schema validation - please add for source and target datatypes

### ISSUE THREAD

**Issue by grzegorz-wasilewski** [GoogleCloudPlatform/professional-services-data-validator#386]
If I run schema validation i have report with this column:
`run_id,validation_name,validation_type,start_time,end_time,source_table_name,target_table_name,source_column_name,target_column_name,aggregation_type,source_agg_value,target_agg_value,status`
One column is missing is the source and target datatypes - for me if I do a UnitTest this information I need to have i acceptable criteria.

Thanks,
Greg

**Comment by nehanene15** [comment]
We could include the source and target data types in the `source_agg_value` and `target_agg_value`

**Comment by nehanene15** [comment]
Similar to Issue #555 . This will be closed by PR #558

**Comment by grzegorz-wasilewski** [comment]
Thanks 👍
