### ISSUE TITLE
hash function?  Compare strings, What are labels used for?

### ISSUE THREAD

**Issue by bnb01** [GoogleCloudPlatform/professional-services-data-validator#398]
data-validation validate schema -sc mybq -tc mybq2 -tbls bnb_new2.csv1=bnb_new3.csv1 -bqrh ml-mps-trl-bd-landing-p-4536.pso_data_validator.results
data-validation validate column -sc mybq -tc mybq2 -tbls bnb_new2.csv1=bnb_new3.csv1 -bqrh ml-mps-trl-bd-landing-p-4536.pso_data_validator.results
data-validation validate column -sc mybq -tc mybq2 -tbls bnb_new2.csv1=bnb_new3.csv1 -gc C1 -max '*' -bqrh ml-mps-trl-bd-landing-p-4536.pso_data_validator.results
data-validation validate column -sc mybq -tc mybq2 -tbls bnb_new2.csv1=bnb_new3.csv1 -gc C1 -min '*' -bqrh ml-mps-trl-bd-landing-p-4536.pso_data_validator.results
data-validation validate column -sc mybq -tc mybq2 -tbls bnb_new2.csv1=bnb_new3.csv1 -gc C1 -sum '*' -bqrh ml-mps-trl-bd-landing-p-4536.pso_data_validator.results
data-validation validate column -sc mybq -tc mybq2 -tbls bnb_new2.csv1=bnb_new3.csv1 -gc C1 -avg '*' -bqrh ml-mps-trl-bd-landing-p-4536.pso_data_validator.results

data-validation validate row -sc mybq -tc mybq2 -tbls bnb_new2.csv1=bnb_new3.csv1 --primary-keys --hash '*' -bqrh ml-mps-trl-bd-landing-p-4536.pso_data_validator.results

All these validations seem to work except the last one which is the hash.  Both tables are in BQ.  I pulled the git repo in the last few days.  Also, how do I compare string columns?  And what is the purpose of labels?

**Comment by ajg12345** [comment]
I'm having a very similar issue because only hash appears to be broken for me too. When I run the following simple example acc to instructions [here ](https://github.com/GoogleCloudPlatform/professional-services-data-validator#row-validations):
```
data-validation validate row -sc bq_conn_pandera-data-demo -tc bq_conn_pandera-data-demo -tbls pandera-data-demo.demo_temp.test_dvt_hash=demo_temp.test_dvt_hashv2 -pk i
d --hash '*'
```
I get the following error, which makes it seem like "validate row" is simply not an option.
`data-validation run-config -c ex_yaml.yaml validate: error: argument validate_cmd: invalid choice: 'row' (choose from 'column', 'schema')`

**Comment by nehanene15** [comment]
Hash support should be supported as of release 1.7.0, although the latest bug fixes are in the develop branch. You can pull the latest code and run a `pip install .` to install the newest changes.

The syntax in your commands are correct and should work with the latest version.

@bnb01 Hash validation compares string columns via checksum. You can also run a comparison field validation which will check if the value of strings are equal. i.e `data-validation validate row -sc bq_conn -tc bq_conn -tbls project.dataset.table --comparison-fields string_column -pk id`

The purpose of labels is to add metadata to a validation run. You can add who is running the validation, any filters you used, or any other comments.
