### ISSUE TITLE
Query Filter Metadata Management

### ISSUE THREAD

**Issue by dhercher** [GoogleCloudPlatform/professional-services-data-validator#40]
How should we manage and store filters around each validation?
A basic filter could be relatively simple, but as it grows in complexity it becomes harder to store (ie how do you store an Ibis column object, cast, isGreaterThan timestamp of X days before today).

**Comment by nehanene15** [comment]
With the use of calculated fields (for CAST, TRIMs, IFNULL, etc) and custom filters, I think this issue is accounted for. But feel free to re-open if we should consider re-architecting for additional functionality.
