### ISSUE TITLE
Filter results to output only failed (or succeeded) records

### ISSUE THREAD

**Issue by FX-HAO** [GoogleCloudPlatform/professional-services-data-validator#412]
This is a feature request. It might be good to have a flag to display only failed (or succeeded) report.

**Comment by nehanene15** [comment]
This should be implemented as a `--filter-status` flag that accepts a comma-separated list of status' with the default being 'succes,fail'. This should apply to all types of validations (column, row, schema, etc.)

For example, to filter out only failed records in the output a user would pass in `--filter-status 'fail'`.

The filter itself should be implemented in the result handler and should apply to both text and BigQuery.
This would also require updating the documentation and adding an example of flag usage in docs/examples.
