### ISSUE TITLE
Large BQ only table compares incorrect

### ISSUE THREAD

**Issue by bnb01** [GoogleCloudPlatform/professional-services-data-validator#415]
I have two equal tables in BQ that are in the same schema, loaded from CSV files, have different names, same unique rows in each table (verified by SQL queries in GCP BQ), all STRING columns, about 200,000 rows.  The column compares are failing with some interesting rows in the BQRH table where either the source or target tables is null.  

I'm going to modify the test today and make several columns, including the PK and compare column, INTEGER and see if I get the same compare results.

The tables were loaded to BQ using Cloud tools for PowerShell on W10.  Cloud tools gets updated to current each day.

**Comment by nehanene15** [comment]
This seems to be a bug that limits the rows at 10k due to support for [random row limits](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/data_validation/consts.py#L65).

**Comment by bnb01** [comment]
I added a trace and some other information.
[err2_2022_4_1.txt](https://github.com/GoogleCloudPlatform/professional-services-data-validator/files/8399921/err2_2022_4_1.txt)

**Comment by nehanene15** [comment]
This seems to be the culprit - Ibis limits query results to 10k: [ibis.options.sql.default_limit = 100](https://github.com/ibis-project/ibis/blob/9bb6bc2816de2c5acc96f3073fa92a879536d42b/docs/user_guide/configuration.md#sql-query-execution)

**Comment by bnb01** [comment]
Can you explain how to build the development branch?  I can download the repo but when I do a “pip install google-pso-data-validator” does that build the development branch?

I haven’t gotten any action on the developers list manager at Mayo.  I’ll probably be a tester for now.  After I build and test the latest fixes I’ll report any bugs again.  Thank you for your help!
Brian Brownlow
Senior Analyst Programmer
Big Data services
Office 507-293-8240
Mayo Clinic Rochester

From: Neha Nene ***@***.***>
Sent: Friday, April 01, 2022 4:39 PM
To: GoogleCloudPlatform/professional-services-data-validator ***@***.***>
Cc: Brownlow, Brian N. ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [GoogleCloudPlatform/professional-services-data-validator] Large BQ only table compares incorrect (Issue #415)


This seems to be the culprit - Ibis limits query results to 10k: ibis.options.sql.default_limit = 100<https://github.com/ibis-project/ibis/blob/9bb6bc2816de2c5acc96f3073fa92a879536d42b/docs/user_guide/configuration.md#sql-query-execution>
