### ISSUE TITLE
Doc: Broken link for "commit prefixes" under Conventional Commits (CONTRIBUTING.md)

### ISSUE THREAD

**Issue by Sync271** [GoogleCloudPlatform/professional-services-data-validator#421]
I was looking into the Contribution Guide and found this link to be broken:
https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/fc73e21810ffe74459a90b79b956a91168c0dc1c/CONTRIBUTING.md?plain=1#L55-L56

And right after that, there's a list of **commit prefixes** anyways:
https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/fc73e21810ffe74459a90b79b956a91168c0dc1c/CONTRIBUTING.md?plain=1#L58-L74

So,I feel it'd be better to update the link or just remove the hyperlink to avoid confusion.

**Comment by celiajmd** [comment]
This is the correct link: https://github.com/googleapis/release-please
