### ISSUE TITLE
How to support Row validation b/w MSSQL Server and BigQuery?

### ISSUE THREAD

**Issue by cah-mahesh-kumar01** [GoogleCloudPlatform/professional-services-data-validator#423]
How to support Row validation b/w MSSQL Server and BigQuery? Any hints would be helpful

**Comment by nehanene15** [comment]
You would need to add a method to format MSSQL hashbytes similar to the methods for BQ, Teradata, and Hive here: https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/third_party/ibis/ibis_addon/operations.py#L104

Then you would update the `MSSQLExprTranslator` registry to point to that format hashbytes function [here](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/third_party/ibis/ibis_addon/operations.py#L187).

**Comment by nehanene15** [comment]
This will be implemented with Issue #560
