### ISSUE TITLE
Support aggregate validation on string columns with length(string_col)

### ISSUE THREAD

**Issue by nehanene15** [GoogleCloudPlatform/professional-services-data-validator#424]
DVT should support column level aggregates (sum, min, max, avg) on the length of string columns. This is supported via calculated fields in a YAML config, but it should also be supported through the CLI. 

Running a '*' aggregation should run over all _numeric_ columns.
`data-validation validate column -sc my_bq_conn -tc my_bq_conn -tbls pso-kokoro-resources.hivetest.mascot -sum '*'`

But specifying a certain string column name should implicitly convert run the aggregation over the length(string_col) 
`data-validation validate column -sc my_bq_conn -tc my_bq_conn -tbls pso-kokoro-resources.hivetest.mascot -sum name`

**Comment by ryanmcdowell** [comment]
Perhaps adding an additional flag could also help:
```
--wildcard-include-string-len
```

Thinking that it may be simpler to run a single validation run for cases which you want to do both numeric and string length instead of separate runs.
