### ISSUE TITLE
unable to row validate hash with Teradata

### ISSUE THREAD

**Issue by ajg12345** [GoogleCloudPlatform/professional-services-data-validator#433]
I get the following error when error when trying to run a validate row using hash all.
` [Teradata Database] [Error 3706] Syntax error: Data Type "concat__all" does not match a Defined Type name.`

Here is an example of the command
` data-validation validate row -sc td-conn -tc bq-conn -tbls expdw_ete_dwh.DWH_D_ORG_LOC_GRP_LU=EXPDW_POC_DWH.DWH_D_ORG_LOC_GRP_LU --primary-keys LOC_GRP_KEY --hash LOC_GRP_KEY 
`
If i try to specify columns (rather than --hash '*') by creating a configuration file and editing it, I get the same error. 

part of hte error shows the created SQL statement which gets run in Teradata:
`SELECT LOC_GRP_KEY, LOC_GRP_ID, LOC_GRP_DESC, RCD_INS_TS, RCD_UPD_TS, RCD_CLOSE_FLG, RCD_CLOSE_DT, cast__LOC_GRP_KEY, ifnull__cast__LOC_GRP_KEY, rstrip__ifnull__cast__LOC_GRP_KEY, upper__rstrip__ifnull__cast__LOC_GRP_KEY, concat__all,
       hash_sha256("concat__all") AS "hash__all"
FROM (
  SELECT LOC_GRP_KEY, LOC_GRP_ID, LOC_GRP_DESC, RCD_INS_TS, RCD_UPD_TS, RCD_CLOSE_FLG, RCD_CLOSE_DT, cast__LOC_GRP_KEY, ifnull__cast__LOC_GRP_KEY, rstrip__ifnull__cast__LOC_GRP_KEY, upper__rstrip__ifnull__cast__LOC_GRP_KEY,
         ARRAY_TO_STRING(["upper__rstrip__ifnull__cast__LOC_GRP_KEY"], ',') AS "concat__all"
  FROM (
    SELECT LOC_GRP_KEY, LOC_GRP_ID, LOC_GRP_DESC, RCD_INS_TS, RCD_UPD_TS, RCD_CLOSE_FLG, RCD_CLOSE_DT, cast__LOC_GRP_KEY, ifnull__cast__LOC_GRP_KEY, rstrip__ifnull__cast__LOC_GRP_KEY,
           upper("rstrip__ifnull__cast__LOC_GRP_KEY") AS "upper__rstrip__ifnull__cast__LOC_GRP_KEY"
    FROM (
      SELECT LOC_GRP_KEY, LOC_GRP_ID, LOC_GRP_DESC, RCD_INS_TS, RCD_UPD_TS, RCD_CLOSE_FLG, RCD_CLOSE_DT, cast__LOC_GRP_KEY, ifnull__cast__LOC_GRP_KEY,
             rtrim("ifnull__cast__LOC_GRP_KEY") AS "rstrip__ifnull__cast__LOC_GRP_KEY"
      FROM (
        SELECT LOC_GRP_KEY, LOC_GRP_ID, LOC_GRP_DESC, RCD_INS_TS, RCD_UPD_TS, RCD_CLOSE_FLG, RCD_CLOSE_DT, cast__LOC_GRP_KEY,
               coalesce("cast__LOC_GRP_KEY", 'DEFAULT_REPLACEMENT_STRING') AS "ifnull__cast__LOC_GRP_KEY"
        FROM (
          SELECT LOC_GRP_KEY, LOC_GRP_ID, LOC_GRP_DESC, RCD_INS_TS, RCD_UPD_TS, RCD_CLOSE_FLG, RCD_CLOSE_DT,
                 CAST("LOC_GRP_KEY" AS STRING) AS "cast__LOC_GRP_KEY"
          FROM expdw_ete_dwh.DWH_D_ORG_LOC_GRP_LU
        ) t4
      ) t3
    ) t2
  ) t1
) t0`

and so I ran this in Teradata studio and it appears the error is twofold:
1. Teradata doesn't have a ARRAY_TO_STRING() function, so that fails. A working alternative would be concat() i think.
2. Teradata doesn't have a hash_sha256() function. A working alternative would be hashrow()

I hope this makes it easy to implement and fix and release.

**Comment by renzokuken** [comment]
Thanks for reaching out @ajg12345 it seems like there are two separate issues here

1) The incorrect concatenate function is being called on Teradata. We should be able to override the default implementation without too much issue

2) The hash_sha256() replacement is a bit more involved. Teradata does not support a native sha256 hashing algorithm so a udf needs to be deployed and registered under that namespace. I see this is missing in the documentation and I will resolve. Using the native hashrow() function would be the preferred approach but as far as I can tell the algorithm is proprietary and/or undocumented. Since this tool is designed for heterogeneous database comparisons we need the same algorithm implemented on all platforms.

I will update the docs and look at the concatenate issue. Thanks for raising and please let me know if you have any questions.

**Comment by srikanthgaddam2** [comment]
We are running into the same issue with ARRAY_TO_STRING function on teradata.

**Comment by srikanthgaddam2** [comment]
the follow changes are implemented on teradata to get the query working 
hash_sha256("concat__all") -> hash_sha256(concat__all)
ARRAY_AGG("upper__rstrip__ifnull__cast ->  concat("upper__rstrip__ifnull__cast

**Comment by renzokuken** [comment]
I have a PR open for this that is under review. Once that is cleared this will get merged into develop

**Comment by ajg12345** [comment]
sounds good! thank you for the update

**Comment by srikanthgaddam2** [comment]
Updated the code to resolve the issue. Line 413
![image](https://user-images.githubusercontent.com/103214226/165604773-12fdf453-b136-4c87-9974-55381c54e6f8.png)

**Comment by ajg12345** [comment]
@renzokuken  and so this is part of a PR now?

**Comment by nehanene15** [comment]
Yes this should be resolved with PR #457 and #482 . Thanks!
