### ISSUE TITLE
Error structure in result table

### ISSUE THREAD

**Issue by rkymtnsteel** [GoogleCloudPlatform/professional-services-data-validator#434]
I am running full column compares in source and target, but the error_result structure is not reported in the result table when a column fails.

**Comment by nehanene15** [comment]
The error_result field is not built out yet - it exists as a placeholder in the result_handler for future implementation. You should be able to dive into the mismatched rows if you specify `--grouped-columns` for column validations. This way you can find the group where the failure occurred.

Row validation (only supported for BQ, Hive, and Teradata) will show the failure at the row level with a status of 'fail'.
