### ISSUE TITLE
Installing the tool on Cloud Composer

### ISSUE THREAD

**Issue by dolonmukherji** [GoogleCloudPlatform/professional-services-data-validator#435]
Has anyone been able to successfully install the tool on Cloud Composer?
The documentation talks about copying the data_validation folder contents to the bucket in the cloud composer environment. Can you provide the steps on how to install the package on cloud composer ?
If you can provide a sample dag to invoke the tool also, that would be great. Thanks!

**Comment by renzokuken** [comment]
A sample dag can be found in the examples at https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/samples/airflow_dag.py

The documentation is a bit outdated and reflects how to install the package directly. The package is currently available on pypi and can be installed the same way as other public packages.

https://cloud.google.com/composer/docs/how-to/using/installing-python-dependencies

please let me know if you have any questions!

**Comment by dolonmukherji** [comment]
We are facing issues when installing the PyPI packages as given in the requirements.txt. We are using composer-1.18.5-airflow-1.10.15
Composer keeps complaining about the incompatibility of the versions of the dependent packages for marshmallow, pyarrow, google-cloud-spanner, proto-plus etc. Is the google-pso-data-validator package compatible with our version of composer and airflow instance?
