### ISSUE TITLE
Unable to create a Snowflake connection

### ISSUE THREAD

**Issue by Squal78** [GoogleCloudPlatform/professional-services-data-validator#439]
hello
we try to use this tool with snowflake but we are unable to create a snowflake connection
after a full install, we execute this command line 
`data-validation connections add --connection-name MY_SF_CONN Snowflake --account "uxxxxxx.europe-west4.gcp.snowflakecomputing.com" --user yyyyyyy --password zzzzzzz`

we always have this error 

> data_validation.exceptions.DataClientConnectionFailure: Connection Type "Snowflake" could not connect: pip install snowflake-connector-python

A basic python connection to snowflake with this script works 

```
import snowflake.connector
ctx = snowflake.connector.connect(
    user='yyyyyyy',
    password='zzzzzzz',
    account='uxxxxxx.europe-west4.gcp'
    )
cs = ctx.cursor()
try:
    cs.execute("SELECT current_version()")
    one_row = cs.fetchone()
    print(one_row[0])
finally:
    cs.close()
ctx.close()
```
 
By the way we manage to add a teradata connection without any issue

Many thanks for your help

**Comment by nehanene15** [comment]
This is what the code uses to connect to Snowflake: https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/third_party/ibis/ibis_snowflake/client.py#L44

It might be useful to delete the exception handling [here](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/data_validation/clients.py#L83) and see what the underlying exception generated is.

**Comment by nehanene15** [comment]
You will also need to install the following:
```
pip install snowflake-sqlalchemy

```
as described [here](https://github.com/GoogleCloudPlatform/professional-services-data-validator/tree/develop/third_party/ibis/ibis_snowflake#1installation). Please re-open if this issue is still ongoing.
