### ISSUE TITLE
1.7.1 status for schema validation, validation_status for column validation?

### ISSUE THREAD

**Issue by bnb012008** [GoogleCloudPlatform/professional-services-data-validator#449]
Are we supposed to have one results table for schema validations and one table for column validations?  

In 'data-validation validate column' validations the results column validation_status is used. 

In 'data-validation validate schema',  validations a column named status is used.

**Comment by nehanene15** [comment]
Both column and schema should be loading to the same results table -- this is a bug. 
We need to update schema validation logic in the data frame [here](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/data_validation/schema_validation.py#L57).

**Comment by helensilva14** [comment]
@nehanene15 @Raniksingh Hello! is there any estimate of releasing this fix? I have a customer that is being blocked by this issue

**Comment by nehanene15** [comment]
@helensilva14 This should be fixed now!

**Comment by helensilva14** [comment]
> @helensilva14 This should be fixed now!

That's great, thanks a lot! And is there an estimate to release it on PyPi? 
https://pypi.org/project/google-pso-data-validator/#history
