### ISSUE TITLE
DVT Validation for String New line comparison

### ISSUE THREAD

**Issue by srikanthgaddam2** [GoogleCloudPlatform/professional-services-data-validator#450]
DVT is surfacing false errors for strings in TD that have new lines in them. Address this issue so that DVT can handle new-lines

**Comment by nehanene15** [comment]
What was the workaround for this? Was using RTRIM an option?

**Comment by srikanthgaddam2** [comment]
@nehanene15 Used source_df = source_df.applymap(lambda x: x.strip() if isinstance(x, str) else x)

**Comment by nehanene15** [comment]
This fix was applied after these lines defining source_df and target_df for a Teradata (source) to BigQuery (target) validation: https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/data_validation/data_validation.py#L310

**Comment by nehanene15** [comment]
Was this for row validation? Curious is the hash generated had trailing whitespace or if it was the string value itself. 
We have seen the TD hash_sha256() UDF generate extra whitespace and cause validation failures despite a matching hash value.

**Comment by nehanene15** [comment]
We added an RSTRIP for row validation hash to avoid this.
