### ISSUE TITLE
min aggregate function seems to be incorrect when reporting 'fail' in column compare, yaml included

### ISSUE THREAD

**Issue by bnb012008** [GoogleCloudPlatform/professional-services-data-validator#456]
I have the csv files and can provide if needed.

result_handler: {}
source: csv11
target: csv12
validations:
- aggregates:
  - field_alias: count
    source_column: null
    target_column: null
    type: count
  - field_alias: min_c7
    source_column: C7
    target_column: C7
    type: min    
  - field_alias: max_c7
    source_column: C7
    target_column: C7
    type: max  
  - field_alias: sum_c7
    source_column: C7
    target_column: C7
    type: sum    
  - field_alias: avg_c7
    source_column: C7
    target_column: C7
    type: avg      
  calculated_fields: []
  dependent_aliases:
  - C1
  filters: []
  format: csv
  grouped_columns:
  - cast: null
    field_alias: C1
    source_column: C1
    target_column: C1
  labels: []
  primary_keys:
  - cast: null
    field_alias: C1
    source_column: C1
    target_column: C1
  random_row_batch_size: '11000'
  schema_name: null
  table_name: csv11
  target_schema_name: null
  target_table_name: csv12
  threshold: 0.0
  type: Column
  use_random_rows: true

**Comment by bnb012008** [comment]
select run_id,
       group_by_columns,
       source_column_name as scn,
       source_table_name as st,
       source_agg_value as sav,
       target_table_name as tt,
       target_agg_value as tav,
       validation_name as vn,
       aggregation_type as at,
       validation_status as vs 
from yaml007
where validation_status = 'fail' and validation_name like 'min%'
order by validation_name, group_by_columns asc;

6ca23f3b-9ef6-4643-bc3d-7780b736f64e	{"C1": "351285000462778676"}	C7	csv11	1	csv12	2	min_c7	min	fail
6ca23f3b-9ef6-4643-bc3d-7780b736f64e	{"C1": "383532140808002842"}	C7	csv11	1	csv12	2	min_c7	min	fail
6ca23f3b-9ef6-4643-bc3d-7780b736f64e	{"C1": "419253706040001633"}	C7	csv11	7	csv12	8	min_c7	min	fail
6ca23f3b-9ef6-4643-bc3d-7780b736f64e	{"C1": "487630658199545736"}	C7	csv11	8	csv12	9	min_c7	min	fail
6ca23f3b-9ef6-4643-bc3d-7780b736f64e	{"C1": "743775675144892972"}	C7	csv11	4	csv12	5	min_c7	min	fail
6ca23f3b-9ef6-4643-bc3d-7780b736f64e	{"C1": "780960906663112749"}	C7	csv11	1	csv12	2	min_c7	min	fail
6ca23f3b-9ef6-4643-bc3d-7780b736f64e	{"C1": "861652146696054795"}	C7	csv11	2	csv12	3	min_c7	min	fail
6ca23f3b-9ef6-4643-bc3d-7780b736f64e	{"C1": "957277041999049904"}	C7	csv11	4	csv12	5	min_c7	min	fail

**Comment by bnb012008** [comment]
produced yaml7 above

result_handler: {}
source: csv11
target: csv12
validations:
- aggregates:
  - field_alias: count_c1
    source_column: C1
    target_column: C1
    type: count
  - field_alias: min_c7
    source_column: C7
    target_column: C7
    type: min
  - field_alias: max_c7
    source_column: C7
    target_column: C7
    type: max
  - field_alias: avg_c7
    source_column: C7
    target_column: C7
    type: avg
  - field_alias: sum_c7
    source_column: C7
    target_column: C7
    type: sum   
  - field_alias: min_c8
    source_column: C8
    target_column: C8
    type: min
  - field_alias: max_c8
    source_column: C8
    target_column: C8
    type: max
  - field_alias: avg_c8
    source_column: C8
    target_column: C8
    type: avg
  - field_alias: sum_c8
    source_column: C8
    target_column: C8
    type: sum     
  calculated_fields: []
  dependent_aliases:
  - C1
  filters: []
  format: csv
  grouped_columns:
  - cast: null
    field_alias: C1
    source_column: C1
    target_column: C1
  labels: []
  primary_keys:
  - cast: null
    field_alias: C1
    source_column: C1
    target_column: C1
  random_row_batch_size: '12000'
  use_random_rows: true
  schema_name: null
  table_name: csv11
  target_schema_name: null
  target_table_name: csv12
  threshold: 0.0
  type: Column

**Comment by nehanene15** [comment]
I'm unsure what the issue is here - Is the SQL query being generated correctly when this is run with the `--verbose` flag? What is incorrect about the MIN aggregate function?

**Comment by nehanene15** [comment]
Following up on this - is this still an issue?
