### ISSUE TITLE
Best practice for doing a validation?

### ISSUE THREAD

**Issue by bnb012008** [GoogleCloudPlatform/professional-services-data-validator#462]
Is it better to use a yaml?  Validate using the command line without a yaml?  Or use a Python program to call the functions used, like some of the testcases appear to do?

I have found that the best thing is to generate a yaml, modify the yaml to do what I want it to do and then run validation with the modified yaml.

Do people use bqrh not, in the yaml?  All in one table?

What are others doing?  How are you recording your validation results?  What type of artifacts are you saving?  Is there anywhere that has a list of best practices?  Perhaps a forum somewhere that people can suggest?

I like the tool.

Thank you!

**Comment by nehanene15** [comment]
We recommend either YAML or CLI for running validations, although there is more flexibility regrading configuration with YAML. 

You can specify a BQ result handler for results in the YAML with the 'result_handler' block as shown in the [example YAML](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/docs/examples.md#sample-yaml-file-grouped-column-validation). You can also use the `--config-file config.yaml`  flag to export your CLI command into a YAML file. 

We recommend using the BQ result handler as it is better for analysis of results. We will be putting together a best practice/how to use DVT guide after we become GA.

**Comment by bnb012008** [comment]
Is there a tentative GA date?
