### ISSUE TITLE
Big integers fail compare

### ISSUE THREAD

**Issue by bnb012008** [GoogleCloudPlatform/professional-services-data-validator#465]
I have output including -v option data.  The schema via -v lists my column as int64.

This is an example of the source column (my Primary key): 919019527657161197.  Should the application indicate a range error?  My research on BQ and python show that my key is within range.  An individual row value should compare correctly.

919019527657161197  My key
9223372036854775807 BQ int64
9223372036854775807 Numpy int64

validation_name,validation_type,aggregation_type,source_table_name,source_column_name,source_agg_value,target_table_name,target_column_name,target_agg_value,group_by_columns,difference,pct_difference,pct_threshold,validation_status,run_id,labels,start_time,end_time
sum_c1,Column,sum,csv20,C1,231044148861767936,bnb01_test.csv20nh_C3STR,C1,231044148861767927,"{""C1"": ""231044148861767927""}",-9.0,-3.895359412622319e-15,0.0,fail,49384750-a6b4-425e-ad2a-cfd907a11fbf,[],2022-05-03 15:09:16.402454+00:00,2022-05-03 15:09:19.390449+00:00

**Comment by bnb012008** [comment]
I'm a little less concerned.  My source is a csv on my W10 pc.  The pk column in the csv is perceived as a string by my PC DB tool, DBeaver.  My target is on BQ and the pk was an integer via the schema.  The sum of the pk (only one row because it is a true pk) succeeds most of the time and fails sometimes.  I'm less concerned about this bug because an integer is being compared to a string but am concerned the GVT is not being consistent.  It succeeds sometimes and fails sometimes.  The same compare, when both columns in the two tables are integers, always succeeds as expected.  I'll try this with things other than a csv on W10/BQ compare.

**Comment by nehanene15** [comment]
If you are encountering an integer overflow error when doing a SUM/AVG, you can CAST to BIGINT or NUMERIC before running the aggregation like so: `SUM(CAST(int_col AS NUMERIC))`.

See the [example](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/docs/examples.md#sample-yaml-with-calc-fields-cast-to-numeric-before-aggregation) YAML to do so.

You can also use the `--cast-to-bigint` flag if you want to automatically cast and INT (int32) columns to BIGINT (int64). Keep in mind that BigQuery INT is by default already int64, so this wouldn't apply to BQ.
