### ISSUE TITLE
What determines the upper limit for random_row_batch_size?

### ISSUE THREAD

**Issue by bnb012008** [GoogleCloudPlatform/professional-services-data-validator#471]
I just tried 100000 rows using a yaml and my W10 workstation with GitBash.  The DVT failed and did not write anything to my bqrh location.  I think it should have failed in a more user friendly fashion with a good error message.  I can easily recreate this using -v option if anyone is interested.

**Comment by bnb012008** [comment]
I will download and try the new build today.

**Comment by nehanene15** [comment]
The upper limit is determined based on the memory and compute limits on your machine. The random row feature selects a certain amount (default 10000) rows randomly from the source and includes them in the WHERE() filter of the target query based on the primary key. This way the same rows are compared between source and target.

Keep in mind that for row validation, the results of the query will be stored in memory and then DVT will compare the results to see if they match. If you are performing load testing with this flag, feel free to update this issue with your findings.
