### ISSUE TITLE
ibis.common.exceptions.IbisTypeError: 'c13' is not a field in ['C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8', 'C9', 'C10', 'C11', 'C12', 'C13']

### ISSUE THREAD

**Issue by bnb012008** [GoogleCloudPlatform/professional-services-data-validator#473]
Even though BQ lists an upper case C13 as the column name in the schema and the BQ load statement created the table column with C13, the DVT code puts c13 in the yaml.  If I manually correct the yaml from c13 to C13 it will run.

**Comment by nehanene15** [comment]
This is working as intended as we automatically lowercase column names to do a case insensitive match. ([Code example](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/data_validation/config_manager.py#L500)) Editing the YAML will allow customization with case sensitive column names.
