### ISSUE TITLE
Based on testing and review I would like to suggest comment and userid columns added to bqrh

### ISSUE THREAD

**Issue by bnb012008** [GoogleCloudPlatform/professional-services-data-validator#475]
The userid column would be a string of the person running the validation, the comment would be a string that could have multiple uses based on customer needs.  This was suggested by one of the people I work.  Thank you!

**Comment by bnb012008** [comment]
bqrh = the big query results handler table

**Comment by nehanene15** [comment]
Labels can be used for both of these purposes. I.e `data-validation validate column -sc my_bq_conn -tc my_bq_conn -tbls bigquery-public-data.new_york_citibike.citibike_trips --labels userid=john_doe,comment=test_run
`
