### ISSUE TITLE
Schema validations don't seem to support labels tag in the yaml file

### ISSUE THREAD

**Issue by bnb012008** [GoogleCloudPlatform/professional-services-data-validator#478]
Schema validations don't seem to support labels tag in the yaml file.

**Comment by nehanene15** [comment]
Do you get an error if this is included? Can you include an example or an error message?

**Comment by celiajmd** [comment]
@bnb012008 
Schema validation with labels tag is tested and it works fine. This issue will be closed.  Please refer to the screenshot. 

<img width="1303" alt="Screen Shot 2022-09-02 at 4 12 05 PM" src="https://user-images.githubusercontent.com/55033756/188732431-b0c4757e-e502-45b0-8f8c-565224adf1d1.png">
