### ISSUE TITLE
How to apply Case Insensitive Column Matching (Issue #105)

### ISSUE THREAD

**Issue by flummoxify** [GoogleCloudPlatform/professional-services-data-validator#479]
Hi,
version 1.7.2
Am I reading it correctly that Issue  #105 was implemented and would allow for Oracle column names (lower case) to match Teradata column names (upper case)?   I cannot find a switch to allow this to happen and currently they are getting marked as "fail".
We are doing software testing before we switch to Google BigQuery.
Thanks.

**Comment by nehanene15** [comment]
DVT should be converting all column names to lowercase before matching for a case insensitive match. Can you provide an example of the results and the command used to generate them?

**Comment by flummoxify** [comment]
Sure. I can do that.   Here is the command that was used.  It uses a connection to Teradata and Oracle

data-validation --verbose validate schema -sc my_td -tc my_ora -tbls SCHEMA_NAME.TABLE1_MTRC_UNVRS=USER___.TABLE1_MTRC_UNVRS_T  -fmt text > table_schema_compare.txt

In the two sample output lines of the comparison, the same column in Teradata  has the column name in UPPER CASE and the next line has the Oracle column name in lower case.

**source_column_name target_column_name aggregation_type source_agg_value target_agg_value validation_status
MTRC_CD                N/A           Schema                1                0              fail
N/A            mtrc_cd           Schema                0                1              fail**

The entire comparison is in the following file:
[table_schema_compare.txt](https://github.com/GoogleCloudPlatform/professional-services-data-validator/files/8828110/table_schema_compare.txt)

Thanks,

**Comment by RajeevGCP** [comment]
@flummoxify @nehanene15 we have same situation in our project, BQ source has upper case column names and Hive/Impala has lower case columns. Is there a way to do schema compare in DVT for us? Can we pass columns as pairs for comparison in cases where column names are not full match? Thanks

**Comment by nehanene15** [comment]
> @flummoxify @nehanene15 we have same situation in our project, BQ source has upper case column names and Hive/Impala has lower case columns. Is there a way to do schema compare in DVT for us? Can we pass columns as pairs for comparison in cases where column names are not full match? Thanks

PR #507 and PR #500 should fix this for schema validation

**Comment by nehanene15** [comment]
This issue is fixed with PR #500 which makes schema validation case insensitive.
