### ISSUE TITLE
The documentation lists a reference to 'PSO Cloud Build project', where is it?

### ISSUE THREAD

**Issue by bnb012008** [GoogleCloudPlatform/professional-services-data-validator#481]
I looked around the GCP and searched github but couldn't find it.  Does it exist under another name?

**Comment by nehanene15** [comment]
Can you please link where in the documentation this is referenced?

**Comment by nehanene15** [comment]
We have a couple references to `pso-kokoro-resources` GCP project where we run our Cloud Build tests and host some test images. It is not accessible by the public. You should be able to run tests locally with pytest or nox if needed.
