### ISSUE TITLE
BQ vs Spanner?

### ISSUE THREAD

**Issue by bnb012008** [GoogleCloudPlatform/professional-services-data-validator#487]
When importing an AVRO file from DB2 for validation has anyone compared importing to Spanner vs. BQ?  I find that importing to BQ changes some column types like DB2 date to BQ string.  The BQ can be parsed, parse_date('%Y-%m-%d',dt), and made to look like the DB2 date but I can't figure out what to do to get them to compare, DB2 is a DATE, BQ is a string.  I don't want to create and compare an intermediate table with right typing.  

Is it better to import DB2 AVRO into Spanner and compare them that way?  I was thinking of testing that.

Any ideas or comments?

**Comment by nehanene15** [comment]
You could try casting the BQ string as DATE and then comparing from DB2 source to BQ target. I'm unsure if importing an Avro from DB2 into Spanner will convert the DB2 data types in the same way importing to BigQuery does.
