### ISSUE TITLE
Do schema validations and other validations have different bqrh by design, e.g. schema vs column validation?  Build 2.0.0

### ISSUE THREAD

**Issue by bnb012008** [GoogleCloudPlatform/professional-services-data-validator#493]
data-validation validate schema -sc csv11GB -tc csv12GB -tbls csv11=csv12 -fmt csv

run_id,validation_name,validation_type,labels,start_time,end_time,source_table_name,target_table_name,source_column_name,target_column_name,aggregation_type,source_agg_value,target_agg_value,validation_status

**Comment by bnb012008** [comment]
Build 2.0

**Comment by bnb012008** [comment]
data-validation validate column -sc csv11GB -tc csv12GB -tbls csv11=csv12 -fmt csv

validation_name,validation_type,aggregation_type,source_table_name,source_column_name,source_agg_value,target_table_name,target_column_name,target_agg_value,group_by_columns,primary_keys,num_random_rows,difference,pct_difference,pct_threshold,validation_status,run_id,labels,start_time,end_time

**Comment by nehanene15** [comment]
This is a bug - the recent updates to the result schema (adding columns for primary_keys and num_random_rows) was not implemented for schema validation.

**Comment by helensilva14** [comment]
@bnb012008 Hi, we just merged the fix for this problem and it'll be available on the next release, thanks for pointing out!
