### ISSUE TITLE
Remove dependency on tables list for custom query

### ISSUE THREAD

**Issue by nehanene15** [GoogleCloudPlatform/professional-services-data-validator#496]
A user should be able to omit the `--tbls` flag and only specify the source and target SQL query for custom query validations. This way a user will not have to parse through the SQL to find the table name(s) when validating queries at scale.

**Comment by sramsrinivasan** [comment]
@nehanene15  - Skimming through the code, I see --tbls is not a mandatory argument.
Running the command **_data-validation validate custom-query_**, I see the below output

**_data-validation run-config -c ex_yaml.yaml validate custom-query: error: the following arguments are required: --source-conn/-sc, --target-conn/-tc, --custom-query-type/-cqt_**

So for custom-query validation only --source-conn, --target-conn and --custom-query-type are the mandatory arguments.
