### ISSUE TITLE
Expand our Contributing guide with more examples and details

### ISSUE THREAD

**Issue by nehanene15** [GoogleCloudPlatform/professional-services-data-validator#498]
We should include more examples of how to locally test code before committing, details on conventional commit guidelines when opening a PR and writing commit messages, how to run our linter (black, flake8), and more about nox. 

See [this Contributing guide](https://github.com/GoogleCloudPlatform/professional-services/blob/main/CONTRIBUTING.md) as an example.

**Comment by nehanene15** [comment]
Add how to test with pytest:
```
pip install pyfakefs==4.3.3
pytest tests/unit
```

And how to lint:
```
pip install black==22.3.0
pip install flake8
black $BLACK_PATHS
flake8 $PATHS
```

As done in our [nox tests](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/179d1c5378e1c727f579cb5083a2565f9a772f45/noxfile.py#L91).

**Comment by sourav25998** [comment]
Hello @nehanene15 . I am starting my open source contribution journey and this issue seems to be a good start. Can you please assign this issue to me and brief me about it?

**Comment by nehanene15** [comment]
> Hello @nehanene15 . I am starting my open source contribution journey and this issue seems to be a good start. Can you please assign this issue to me and brief me about it?

Hi, this issue is simply adding documentation for how to contribute to DVT (how to test code, open issues, etc.). Feel free to open a PR with changes if you would like to address this. Issue #596 would also be a good first issue.
