### ISSUE TITLE
Support --concat flag for row level comparison

### ISSUE THREAD

**Issue by nehanene15** [GoogleCloudPlatform/professional-services-data-validator#511]
Currently we only support a column list for row level comparison field validation i.e.
`data-validation validate row -sc conn -tc conn -tbls tbls -comp-fields col_a,col_b`

The above command will run a value comparison for each column. We should enable support for running a string comparison on the sanitized and concatenated result of the row.  

Row hash validation will differ from this since it will hash the concatenated row and compare the hash value. This will compare the concatenated string (the input of row hash) instead of the output of row hash.

This can be implemented with a `--concat col_a,col_b` flag that should also support '*'.

**Comment by renzokuken** [comment]
do we want to compare all columns or just the cast? Wondering if this should be a separate operation e.g. you can pass hash or concat.

**Comment by nehanene15** [comment]
Closed with #566
