### ISSUE TITLE
Unable to install on Macbook M1 - fails at numpy install

### ISSUE THREAD

**Issue by sujitrect** [GoogleCloudPlatform/professional-services-data-validator#522]
Hi,

I am unable to install this promising tool on my M1 Macbook.
`pip3 install google-pso-data-validator` fails at step while installing numpy (sourced from dependency with pyarraow==3.0.0)
Attached log file:
[DVT-install-err.txt](https://github.com/GoogleCloudPlatform/professional-services-data-validator/files/8975915/DVT-install-err.txt)

I have tried various workarounds:
- local clone and build with setup.py modified to a diff pyarrow version
- pip --nodeps , --constraints options and some more 
but always hitting one roadblock or other.

Any suggestions to get through this?

**Comment by nehanene15** [comment]
Are you installing this in a virtual environment? And what Python version are you using?

**Comment by helensilva14** [comment]
Hi @sujitrect! Reaching out to know if you can answer the questions that Neha previously sent, it would be really helpful. Also we released a new version on Friday, could you check if the problem persists? Thanks!

**Comment by sujitrect** [comment]
Same issue still.

@nehanene15 I am using virtual env. Below are other details:
```
(psdv-venv) ➜  /tmp uname -a
Darwin < myhost> 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64
(psdv-venv) ➜  /tmp python3 -V
Python 3.9.13
```

I am able to install in a Ubuntu system, but it's failing on my MacBook.

**Comment by sujitrect** [comment]
Finally resolved, with below steps:
1. `brew install postgressql openssl` # pg_config is required to be accessible. As well as openssl libs
2. Clone this repo and `cd` into it.
3. Current referred `pyarrow` version is not building due to the dependent numpy. Change `setup.py` to use below dependency versions (instead of existing)
```
# found below with trial and error
pyarrow==6.0.0
ibis-bigquery==1.0.0
```
4. Below exports were needed. Otherwise `grpcio` was not getting installed ([reference](https://stackoverflow.com/a/68137855/2438951)).
```
# Replace with ur openssl paths in below
export GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=1
export GRPC_PYTHON_BUILD_SYSTEM_ZLIB=1
export LIBRARY_PATH=$LIBRARY_PATH:"/opt/homebrew/opt/openssl@1.1/lib" 
export CFLAGS="-I/opt/homebrew/opt/openssl@1.1/include"
export LDFLAGS="-L/opt/homebrew/opt/openssl@1.1/lib"
```
5. `python3 -m venv venv; source venv/bin/activate`
6. `pip install .`

PS: I haven't yet tried out the tool. Just checked it invokes and prints usage info.
