### ISSUE TITLE
Max timestamp doesnot return any results for oracle

### ISSUE THREAD

**Issue by aaslam17** [GoogleCloudPlatform/professional-services-data-validator#532]
We have tested the max aggregation function for a timestamp column in oracle, the results doesnot contain the max timestamp. Instead only default record count is present.
https://screenshot.googleplex.com/4yzXze6sWZo8kho.

**Comment by nehanene15** [comment]
Could you provide the command used to generate this and the data types you are comparing in Oracle versus BigQuery? i.e Oracle TIMESTAMP to BigQuery TIMESTAMP?

**Comment by nehanene15** [comment]
Sample timestamp `30-NOV-21 08.00.00.000000 AM UTC`. This issue is regarding Oracle data type TIMESTAMP WITH TIME ZONE

**Comment by nehanene15** [comment]
This is an issue with the [client and server having different timezones](https://stackoverflow.com/questions/7678485/oracle-ora-01805-on-oracle-11g-database). To resolve this, use an older version of the cx_oracle client:
`pip install -U cx-Oracle==6.4.1`
