### ISSUE TITLE
Refactor custom query validation to use query builder

### ISSUE THREAD

**Issue by nehanene15** [GoogleCloudPlatform/professional-services-data-validator#539]
Currently the custom query validations uses separate logic to build the column level query. This should be refactored to use the existing query_builder logic used for standard column validations.

**Comment by sramsrinivasan** [comment]
- [] Remove -tbls argument from command

**Comment by sramsrinivasan** [comment]
- [ ] #575

**Comment by koolbrezz80** [comment]
Sorry I just saying someone is trying to take my Yahoo account

**Comment by koolbrezz80** [comment]
augustussimpkins55@yahoo.com haven't had access for about 3mon

**Comment by koolbrezz80** [comment]
Has a permalink code I guess on it
