### ISSUE TITLE
DVT breakage?

### ISSUE THREAD

**Issue by bnb012008** [GoogleCloudPlatform/professional-services-data-validator#545]
In the prior release the below worked:

data-validation validate column -sc db2xxxx -tc bqxxxxx -tbls EDTDM.DIMENSION_DATE=DIMENSION_DATE.DIMENSION_DATE -gc 'dt_sk' -pk 'dt_sk' -sum 'dt_sk' -rr -rbs 3 -fmt csv

In the current build it does not:

google.api_core.exceptions.BadRequest: 400 Column name DT_SK is ambiguous at [1:8]

**Comment by bnb012008** [comment]
It's the same whether I use command line or a yaml to run.

**Comment by nehanene15** [comment]
What is the SQL query that is generated? I wasn't able to reproduce this error for a BQ to BQ validation.
