### ISSUE TITLE
run_id is missing from standard console output of DVT

### ISSUE THREAD

**Issue by kanhaPrayas** [GoogleCloudPlatform/professional-services-data-validator#549]
We observed the run_id is missing from standard output of DVT. run_id is required by the customer as a reference to query the results in bigquery for a particular execution. So it will be great to have run_id as part of the standard output.

**Comment by nehanene15** [comment]
If you remove [this line](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/data_validation/consts.py#L137), run_id will be printed to standard out. We use the [COLUMN_FILTER_LIST](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/data_validation/consts.py#L132) constant to exclude certain columns when printing a summary to stdout. This can be edited to include certain columns as needed.
