### ISSUE TITLE
DVT output is not proper and giving ambiguous output with --filters,  --use-random-row and --random-row-batch-size options

### ISSUE THREAD

**Issue by kanhaPrayas** [GoogleCloudPlatform/professional-services-data-validator#552]
We are running DVT with filters, --random-row-batch-size and  --use-random-row(for sampling) options. The source and target tables both are Teradata. The DVT execution is going thru properly. However the output generated is not correct and is ambiguous.
We are trying to run the DVT with 10,000 batch size, but the output  being generated is only for very handful rows(3/5/7).

**Comment by nehanene15** [comment]
Can you provide an example command and an example of the output generated? Does this occur for both text and BQ result handler? Is the query generated correct?

**Comment by nehanene15** [comment]
The issue here is that DVT currently treat filters and random row mutually exclusively, when in fact we need to apply the filter inside the random row. I.e. when getting the X IDs randomly, we need to apply the filter 'timestamp > Y'.
