### ISSUE TITLE
Oracle connection error

### ISSUE THREAD

**Issue by gaj995** [GoogleCloudPlatform/professional-services-data-validator#554]
Has anyone seen the following when trying oracle connection? Trying this through Cloud Functions and keep getting this. Any idea on how to resolve this? 
```
data_validation.exceptions.DataClientConnectionFailure: Connection Type "Oracle" could not connect: (cx_Oracle.DatabaseError) DPI-1047: Cannot locate a 64-bit Oracle Client library: "libclntsh.so: cannot open shared object file: No such file or directory". See https://cx-oracle.readthedocs.io/en/latest/user_guide/installation.html for help
(Background on this error at: http://sqlalche.me/e/13/4xp6)
```

**Comment by nehanene15** [comment]
You will need to install an [oracle client library](https://www.oracle.com/database/technologies/instant-client/downloads.html) to connect to an Oracle DB. Unfortunately, this is not possible on a Cloud Function environment, but there are some workarounds described in [this StackOverflow article](https://stackoverflow.com/questions/58073843/how-to-call-oracle-db-from-google-cloud-functions-in-node-js).
