### ISSUE TITLE
Cloud Run with multiple tables

### ISSUE THREAD

**Issue by gaj995** [GoogleCloudPlatform/professional-services-data-validator#559]
Is there a way to pass multiple source and target tables to validate in single run like with the CLI (schema.table=target_schema.target_table) in Cloud Run?

**Comment by gaj995** [comment]
From CLI example: `Comma separated list of tables in the form schema.table=target_schema.target_table`

**Comment by nehanene15** [comment]
With our current [Cloud Run sample code](https://github.com/GoogleCloudPlatform/professional-services-data-validator/tree/develop/samples/run), you would need to send separate requests per validation run. The benefit of this is scaling and parallelization. 

Although, you could add support for multiple requests by tweaking `_get_request_content` to parse through a list of configs, and then run validate(config) for each.

cc @dhercher
