### ISSUE TITLE
Maximum number of tables in YAML

### ISSUE THREAD

**Issue by gaj995** [GoogleCloudPlatform/professional-services-data-validator#561]
Is there a limit to the amount of tables that should be in a YAML file? 

I have a YAML file with over 350 tables to be compared (Oracle=BQ) and after 90 it just freezes and doesn't do anything. 

Also tried splitting the files into 5 different files with 75 tables and after the 75th table comparison it also freezes and doesn't exit. 

I am running this in a VM

**Comment by nehanene15** [comment]
No, there isn't a set limit. Although since the validations run synchronously so there may be a quota or limit on the databases themselves or the compute power of the VM you are running on. It may be helpful to use verbose logging to see where it is getting stuck.
