### ISSUE TITLE
Support for Hive as a source

### ISSUE THREAD

**Issue by TirayrK** [GoogleCloudPlatform/professional-services-data-validator#578]
Hello,

Does the tool source Hive as a source? 

I can see Hive as an option in the document but after installing the tool I can't see it in the list of supported options:

data-validation connections add -h
usage: The Data Validation CLI tool is intended to help to build and execute
data validation runs with ease.

The Data Validator can be called either using:
    data-validation -h
    python -m data_validation -h

ex.
Step 1) Store Connection to be used in validation
data-validation connections add -c my_bq_conn BigQuery --project-id pso-kokoro-resources

Step 2) Run Validation using supplied connections
data-validation run -t Column -sc my_bq_conn -tc my_bq_conn -tbls bigquery-public-data.new_york_citibike.citibike_trips,bigquery-public-data.new_york_citibike.citibike_stations --sum '*' --count '*'

python -m data_validation run -t GroupedColumn -sc my_bq_conn -tc my_bq_conn -tbls bigquery-public-data.new_york_citibike.citibike_trips --grouped-columns starttime --sum tripduration --count tripduration

data-validation run -t Column -sc my_bq_conn -tc my_bq_conn -tbls bigquery-public-data.new_york_citibike.citibike_trips,bigquery-public-data.new_york_citibike.citibike_stations --sum tripduration,start_station_name --count tripduration,start_station_name -rc pso-kokoro-resources.pso_data_validator.results
-c ex_yaml.yaml

data-validation run-config -c ex_yaml.yaml connections add
       [-h] [--connection-name CONNECTION_NAME] {Raw,BigQuery,Teradata,Oracle,MSSQL,MySQL,Snowflake,Postgres,Redshift,Spanner,FileSystem} ...

positional arguments:
  {Raw,BigQuery,Teradata,Oracle,MSSQL,MySQL,Snowflake,Postgres,Redshift,Spanner,FileSystem}
    Raw                 Supply Raw JSON config for a connection
    BigQuery            Store a BigQuery connection
    Teradata            Store a Teradata connection
    Oracle              Store a Oracle connection
    MSSQL               Store a MSSQL connection
    MySQL               Store a MySQL connection
    Snowflake           Store a Snowflake connection
    Postgres            Store a Postgres connection
    Redshift            Store a Redshift connection
    Spanner             Store a Spanner connection
    FileSystem          Store a FileSystem connection

optional arguments:
  -h, --help            show this help message and exit
  --connection-name CONNECTION_NAME, -c CONNECTION_NAME
                        Name of connection used as reference

**Comment by nehanene15** [comment]
We do support Hive as a data source through the Impala connector as described [here](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/docs/connections.md#Hive).

Do you have the latest version of the tool? The output of `data-validation connections add -h` shows Impala/Hive when I run it:
```
usage: The Data Validation CLI tool is intended to help to build and execute
data validation runs with ease.

The Data Validator can be called either using:
    data-validation -h
    python -m data_validation -h

ex.
Step 1) Store Connection to be used in validation
data-validation connections add -c my_bq_conn BigQuery --project-id pso-kokoro-resources

Step 2) Run Validation using supplied connections
data-validation validate column -sc my_bq_conn -tc my_bq_conn -tbls bigquery-public-data.new_york_citibike.citibike_trips,bigquery-public-data.new_york_citibike.citibike_stations --sum '*' --count '*'

python -m data_validation validate column -sc my_bq_conn -tc my_bq_conn -tbls bigquery-public-data.new_york_citibike.citibike_trips --grouped-columns starttime --sum tripduration --count tripduration

data-validation validate column -sc my_bq_conn -tc my_bq_conn -tbls bigquery-public-data.new_york_citibike.citibike_trips,bigquery-public-data.new_york_citibike.citibike_stations --sum tripduration,start_station_name --count tripduration,start_station_name -bqrh pso-kokoro-resources.pso_data_validator.results
-c ex_yaml.yaml

data-validation run-config -c ex_yaml.yaml connections add
       [-h] [--connection-name CONNECTION_NAME] {Raw,BigQuery,Teradata,Oracle,MSSQL,MySQL,Snowflake,Postgres,Redshift,Spanner,FileSystem,Impala,DB2} ...

positional arguments:
  {Raw,BigQuery,Teradata,Oracle,MSSQL,MySQL,Snowflake,Postgres,Redshift,Spanner,FileSystem,Impala,DB2}
    Raw                 Supply Raw JSON config for a connection
    BigQuery            Store a BigQuery connection
    Teradata            Store a Teradata connection
    Oracle              Store a Oracle connection
    MSSQL               Store a MSSQL connection
    MySQL               Store a MySQL connection
    Snowflake           Store a Snowflake connection
    Postgres            Store a Postgres connection
    Redshift            Store a Redshift connection
    Spanner             Store a Spanner connection
    FileSystem          Store a FileSystem connection
    Impala              Store a Impala connection
    DB2                 Store a DB2 connection
```
