### ISSUE TITLE
Column with string type which have different case in like name in source and Name in target don't join .

### ISSUE THREAD

**Issue by piyushbajaj125** [GoogleCloudPlatform/professional-services-data-validator#597]
Hi , 
I have tried tried this with MySQL and Postgre that if i have different case in the source or in the designation then i get an error , column name (name) not present in the target columns list .

**Comment by nehanene15** [comment]
For tables with different casing in source vs target, you will need to use the YAML config to specify the 'source_column_name' and 'target_column_name'.
