### ISSUE TITLE
How to run DVT tool locally on System 

### ISSUE THREAD

**Issue by tirthshah485** [GoogleCloudPlatform/professional-services-data-validator#618]
Hey guys I want to setup this DVT tool on my machine and try to run to run it locally i followed every steps that mentioned in installation page can someone help me to how can I run this tool in my local machine

**Comment by nehanene15** [comment]
The [installation guide](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/docs/installation.md#setup) has all the steps to run the tool locally. You will need to make sure your local machine can connect to the databases.
