### ISSUE TITLE
Row hash validation for NUMERIC fails between Postgres and Oracle

### ISSUE THREAD

**Issue by sundar-mudupalli-work** [GoogleCloudPlatform/professional-services-data-validator#620]
A table is loaded with the following data
iowa=> select * from dvt_test;
 id |                                        value                                        
----+-------------------------------------------------------------------------------------
 A  |                                                                                   1
 B  |                                                                                 1.5
 C  |                                                                     1.5000000000000
 D  |                                                                     1.5000000000000
 E  |                                                        123486701293414.129341923471
 F  |                                                                     150000000000000
 G  |                               12134917239469569585923569056928364912346000000000000
 H  | 12349453847394754396582930467349067834706573249876592347598237459743287200000000000
 I  |                                                          1.500000000000000000000001

The id being the primary key and the value as shown above. When this data is loaded into both Oracle and Postgres (sql scripts are [drop_create_test_ora.txt](https://github.com/GoogleCloudPlatform/professional-services-data-validator/files/9853714/drop_create_test_ora.txt) and [drop_create_test_pg.txt](https://github.com/GoogleCloudPlatform/professional-services-data-validator/files/9853722/drop_create_test_pg.txt))

Validation fails for ids 'C', 'D', 'G' and 'H'. Query output and verbose output below.
``data-validation query --conn my_postgres --query 'select * from dvt_test'
[('A', Decimal('1')), ('B', Decimal('1.5')), ('C', Decimal('1.5000000000000')), ('D', Decimal('1.5000000000000')), ('E', Decimal('123486701293414.129341923471')), ('F', Decimal('150000000000000')), ('G', Decimal('12134917239469569585923569056928364912346000000000000')), ('H', Decimal('12349453847394754396582930467349067834706573249876592347598237459743287200000000000')), ('I', Decimal('1.500000000000000000000001'))]``
``data-validation query --conn my_oracle --query 'select * from dvt_test'
[('A', 1), ('B', Decimal('1.5')), ('C', Decimal('1.5')), ('D', Decimal('1.5')), ('E', Decimal('123486701293414.129341923471')), ('F', 150000000000000), ('G', 12134917239469569585923569056928364912300000000000000), ('H', 12349453847394754396582930467349067834700000000000000000000000000000000000000000000), ('I', Decimal('1.500000000000000000000001'))]``

Here is the verbose output for failure on 'C'
``data-validation --verbose validate row --source-conn my_postgres --target-conn my_oracle --tables-list public.dvt_test=sysad.dvt_test --primary-keys 'id' --hash 'value' --filter-status fail --filters "id='C'"
10/24/2022 05:06:31 PM-INFO: {'data_client': <ibis.backends.postgres.client.PostgreSQLClient object at 0x7f2df73405b0>, 'schema_name': 'public', 'table_name': 'dvt_test'}
10/24/2022 05:06:31 PM-INFO: -- ** Source Query ** --
10/24/2022 05:06:31 PM-INFO: SELECT t0.id, t0.value, t0.cast__value, t0.ifnull__cast__value, t0.rstrip__ifnull__cast__value, t0.upper__rstrip__ifnull__cast__value, t0.concat__all, t0.hash__all 
FROM (SELECT t2.id AS id, t2.value AS value, t2.cast__value AS cast__value, t2.ifnull__cast__value AS ifnull__cast__value, t2.rstrip__ifnull__cast__value AS rstrip__ifnull__cast__value, t2.upper__rstrip__ifnull__cast__value AS upper__rstrip__ifnull__cast__value, t2.concat__all AS concat__all, encode(sha256(convert_to(t2.concat__all, 'UTF8')), 'hex') AS hash__all 
FROM (SELECT t3.id AS id, t3.value AS value, t3.cast__value AS cast__value, t3.ifnull__cast__value AS ifnull__cast__value, t3.rstrip__ifnull__cast__value AS rstrip__ifnull__cast__value, t3.upper__rstrip__ifnull__cast__value AS upper__rstrip__ifnull__cast__value, concat_ws(%(param_1)s, t3.upper__rstrip__ifnull__cast__value) AS concat__all 
FROM (SELECT t4.id AS id, t4.value AS value, t4.cast__value AS cast__value, t4.ifnull__cast__value AS ifnull__cast__value, t4.rstrip__ifnull__cast__value AS rstrip__ifnull__cast__value, upper(t4.rstrip__ifnull__cast__value) AS upper__rstrip__ifnull__cast__value 
FROM (SELECT t5.id AS id, t5.value AS value, t5.cast__value AS cast__value, t5.ifnull__cast__value AS ifnull__cast__value, rtrim(t5.ifnull__cast__value) AS rstrip__ifnull__cast__value 
FROM (SELECT t6.id AS id, t6.value AS value, t6.cast__value AS cast__value, coalesce(t6.cast__value, %(param_2)s) AS ifnull__cast__value 
FROM (SELECT t1.id AS id, t1.value AS value, CAST(t1.value AS TEXT) AS cast__value 
FROM public.dvt_test AS t1) AS t6) AS t5) AS t4) AS t3) AS t2) AS t0 
WHERE id='C'
10/24/2022 05:06:31 PM-INFO: {'data_client': <third_party.ibis.ibis_oracle.client.OracleClient object at 0x7f2df7322f70>, 'schema_name': 'sysad', 'table_name': 'dvt_test'}
10/24/2022 05:06:31 PM-INFO: -- ** Target Query ** --
10/24/2022 05:06:31 PM-INFO: SELECT t0.id, t0.value, t0.cast__value, t0.ifnull__cast__value, t0.rstrip__ifnull__cast__value, t0.upper__rstrip__ifnull__cast__value, t0.concat__all, t0.hash__all 
FROM (SELECT t2.id AS id, t2.value AS value, t2.cast__value AS cast__value, t2.ifnull__cast__value AS ifnull__cast__value, t2.rstrip__ifnull__cast__value AS rstrip__ifnull__cast__value, t2.upper__rstrip__ifnull__cast__value AS upper__rstrip__ifnull__cast__value, t2.concat__all AS concat__all, lower(standard_hash(t2.concat__all, 'SHA256')) AS hash__all 
FROM (SELECT t3.id AS id, t3.value AS value, t3.cast__value AS cast__value, t3.ifnull__cast__value AS ifnull__cast__value, t3.rstrip__ifnull__cast__value AS rstrip__ifnull__cast__value, t3.upper__rstrip__ifnull__cast__value AS upper__rstrip__ifnull__cast__value, upper__rstrip__ifnull__cast__value AS concat__all 
FROM (SELECT t4.id AS id, t4.value AS value, t4.cast__value AS cast__value, t4.ifnull__cast__value AS ifnull__cast__value, t4.rstrip__ifnull__cast__value AS rstrip__ifnull__cast__value, upper(t4.rstrip__ifnull__cast__value) AS upper__rstrip__ifnull__cast__value 
FROM (SELECT t5.id AS id, t5.value AS value, t5.cast__value AS cast__value, t5.ifnull__cast__value AS ifnull__cast__value, rtrim(t5.ifnull__cast__value) AS rstrip__ifnull__cast__value 
FROM (SELECT t6.id AS id, t6.value AS value, t6.cast__value AS cast__value, coalesce(t6.cast__value, :param_1) AS ifnull__cast__value 
FROM (SELECT t1.id AS id, t1.value AS value, CAST(t1.value AS VARCHAR2(4000 CHAR)) AS cast__value 
FROM sysad.dvt_test t1) t6) t5) t4) t3) t2) t0 
WHERE id='C'
10/24/2022 05:06:31 PM-INFO: -- ** Pandas Schema ** --
10/24/2022 05:06:31 PM-INFO: Series([], dtype: float64)
╒═══════════════════╤═══════════════════╤═════════════════════╤══════════════════════╤══════════════════════════════════════════════════════════════════╤══════════════════════════════════════════════════════════════════╤══════════════════╤═════════════════════╕
│ validation_name   │ validation_type   │ source_table_name   │ source_column_name   │ source_agg_value                                                 │ target_agg_value                                                 │ pct_difference   │ validation_status   │
╞═══════════════════╪═══════════════════╪═════════════════════╪══════════════════════╪══════════════════════════════════════════════════════════════════╪══════════════════════════════════════════════════════════════════╪══════════════════╪═════════════════════╡
│ hash__all         │ Row               │ public.dvt_test     │ hash__all            │ bda1ed13c30a8385782a96798c3d14287e2de7868382779e5796ea2cb06ee83e │ 9f29a130438b81170b92a42650f9a94291ecad60bd47af2a3886e75f7f728725 │                  │ fail                │
╘═══════════════════╧═══════════════════╧═════════════════════╧══════════════════════╧══════════════════════════════════════════════════════════════════╧══════════════════════════════════════════════════════════════════╧══════════════════╧═════════════════════╛``

Here is the verbose output for failure on 'G'
``data-validation --verbose validate row --source-conn my_postgres --target-conn my_oracle --tables-list public.dvt_test=sysad.dvt_test --primary-keys 'id' --hash 'value' --filter-status fail --filters "id='G'"
10/24/2022 05:07:48 PM-INFO: {'data_client': <ibis.backends.postgres.client.PostgreSQLClient object at 0x7f3047d583d0>, 'schema_name': 'public', 'table_name': 'dvt_test'}
10/24/2022 05:07:48 PM-INFO: -- ** Source Query ** --
10/24/2022 05:07:48 PM-INFO: SELECT t0.id, t0.value, t0.cast__value, t0.ifnull__cast__value, t0.rstrip__ifnull__cast__value, t0.upper__rstrip__ifnull__cast__value, t0.concat__all, t0.hash__all 
FROM (SELECT t2.id AS id, t2.value AS value, t2.cast__value AS cast__value, t2.ifnull__cast__value AS ifnull__cast__value, t2.rstrip__ifnull__cast__value AS rstrip__ifnull__cast__value, t2.upper__rstrip__ifnull__cast__value AS upper__rstrip__ifnull__cast__value, t2.concat__all AS concat__all, encode(sha256(convert_to(t2.concat__all, 'UTF8')), 'hex') AS hash__all 
FROM (SELECT t3.id AS id, t3.value AS value, t3.cast__value AS cast__value, t3.ifnull__cast__value AS ifnull__cast__value, t3.rstrip__ifnull__cast__value AS rstrip__ifnull__cast__value, t3.upper__rstrip__ifnull__cast__value AS upper__rstrip__ifnull__cast__value, concat_ws(%(param_1)s, t3.upper__rstrip__ifnull__cast__value) AS concat__all 
FROM (SELECT t4.id AS id, t4.value AS value, t4.cast__value AS cast__value, t4.ifnull__cast__value AS ifnull__cast__value, t4.rstrip__ifnull__cast__value AS rstrip__ifnull__cast__value, upper(t4.rstrip__ifnull__cast__value) AS upper__rstrip__ifnull__cast__value 
FROM (SELECT t5.id AS id, t5.value AS value, t5.cast__value AS cast__value, t5.ifnull__cast__value AS ifnull__cast__value, rtrim(t5.ifnull__cast__value) AS rstrip__ifnull__cast__value 
FROM (SELECT t6.id AS id, t6.value AS value, t6.cast__value AS cast__value, coalesce(t6.cast__value, %(param_2)s) AS ifnull__cast__value 
FROM (SELECT t1.id AS id, t1.value AS value, CAST(t1.value AS TEXT) AS cast__value 
FROM public.dvt_test AS t1) AS t6) AS t5) AS t4) AS t3) AS t2) AS t0 
WHERE id='G'
10/24/2022 05:07:48 PM-INFO: {'data_client': <third_party.ibis.ibis_oracle.client.OracleClient object at 0x7f3047ce6760>, 'schema_name': 'sysad', 'table_name': 'dvt_test'}
10/24/2022 05:07:48 PM-INFO: -- ** Target Query ** --
10/24/2022 05:07:48 PM-INFO: SELECT t0.id, t0.value, t0.cast__value, t0.ifnull__cast__value, t0.rstrip__ifnull__cast__value, t0.upper__rstrip__ifnull__cast__value, t0.concat__all, t0.hash__all 
FROM (SELECT t2.id AS id, t2.value AS value, t2.cast__value AS cast__value, t2.ifnull__cast__value AS ifnull__cast__value, t2.rstrip__ifnull__cast__value AS rstrip__ifnull__cast__value, t2.upper__rstrip__ifnull__cast__value AS upper__rstrip__ifnull__cast__value, t2.concat__all AS concat__all, lower(standard_hash(t2.concat__all, 'SHA256')) AS hash__all 
FROM (SELECT t3.id AS id, t3.value AS value, t3.cast__value AS cast__value, t3.ifnull__cast__value AS ifnull__cast__value, t3.rstrip__ifnull__cast__value AS rstrip__ifnull__cast__value, t3.upper__rstrip__ifnull__cast__value AS upper__rstrip__ifnull__cast__value, upper__rstrip__ifnull__cast__value AS concat__all 
FROM (SELECT t4.id AS id, t4.value AS value, t4.cast__value AS cast__value, t4.ifnull__cast__value AS ifnull__cast__value, t4.rstrip__ifnull__cast__value AS rstrip__ifnull__cast__value, upper(t4.rstrip__ifnull__cast__value) AS upper__rstrip__ifnull__cast__value 
FROM (SELECT t5.id AS id, t5.value AS value, t5.cast__value AS cast__value, t5.ifnull__cast__value AS ifnull__cast__value, rtrim(t5.ifnull__cast__value) AS rstrip__ifnull__cast__value 
FROM (SELECT t6.id AS id, t6.value AS value, t6.cast__value AS cast__value, coalesce(t6.cast__value, :param_1) AS ifnull__cast__value 
FROM (SELECT t1.id AS id, t1.value AS value, CAST(t1.value AS VARCHAR2(4000 CHAR)) AS cast__value 
FROM sysad.dvt_test t1) t6) t5) t4) t3) t2) t0 
WHERE id='G'
10/24/2022 05:07:48 PM-INFO: -- ** Pandas Schema ** --
10/24/2022 05:07:48 PM-INFO: Series([], dtype: float64)
╒═══════════════════╤═══════════════════╤═════════════════════╤══════════════════════╤══════════════════════════════════════════════════════════════════╤══════════════════════════════════════════════════════════════════╤══════════════════╤═════════════════════╕
│ validation_name   │ validation_type   │ source_table_name   │ source_column_name   │ source_agg_value                                                 │ target_agg_value                                                 │ pct_difference   │ validation_status   │
╞═══════════════════╪═══════════════════╪═════════════════════╪══════════════════════╪══════════════════════════════════════════════════════════════════╪══════════════════════════════════════════════════════════════════╪══════════════════╪═════════════════════╡
│ hash__all         │ Row               │ public.dvt_test     │ hash__all            │ ba372f014c202da8992aa6d6760446001e38c1a980972dc99d44b869ed61b7af │ 121a46a995f19c73b47fb75b5119e95f85ff03833122d06e5820f39057494851 │                  │ fail                │
╘═══════════════════╧═══════════════════╧═════════════════════╧══════════════════════╧══════════════════════════════════════════════════════════════════╧══════════════════════════════════════════════════════════════════╧══════════════════╧═════════════════════╛``

**Comment by nehanene15** [comment]
Closing this out since we now have to_char support as per PR #632 to standardize NUMERIC columns into a formatted string before hashing.
