### ISSUE TITLE
Add AlloyDB support 

### ISSUE THREAD

**Issue by Raniksingh** [GoogleCloudPlatform/professional-services-data-validator#625]

**Comment by nehanene15** [comment]
This should already be possible via the Postgres connector, so this issue will involve testing the Postgres connection on an AlloyDB table. If the connection and validations are successful, the README can be updated to include AlloyDB

**Comment by slatawa** [comment]
Tested DVT with Alloy DB cluster using a Postgres connector and DVT is able to talk with Alloy DB using the Postgres connector itself. Have tested and confirmed this for Row and Column validations .
Unable to test Custom query Row and Column validation as Custom Postgres Connector is under development. we can test the remaining test cases once ready.

**Comment by slatawa** [comment]
Have tested Custom query with Alloy DB using postgress connector and it works fine.

**Comment by slatawa** [comment]
This PR - https://github.com/GoogleCloudPlatform/professional-services-data-validator/pull/645 resolves the ticket
