### ISSUE TITLE
Unrecognized arguments --user_name for Oracle connection

### ISSUE THREAD

**Issue by JordyHeusdensDT** [GoogleCloudPlatform/professional-services-data-validator#658]
Based on [Oracle connection](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/docs/connections.md#oracle) documentation, I can use the next command to add a new Oracle connection:

`data-validation connections add -c CONNECTION_NAME Oracle --host HOST_NAME --port POST --user_name USERNAME --password PASSWORD --database DATABASE`

However, this gives me the next error: 
`data-validation: error: unrecognized arguments: --user_name USERNAME`

The parameter `--user` seems to work though. Can this be fixed?

**Comment by nehanene15** [comment]
Thanks for the issue. It should be updated to 'user' for Oracle.


This issue should also standardize the Connections guide as the underscores in the JSON config ([Oracle example](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/docs/connections.md#oracle), [Spanner example](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/docs/connections.md#google-spanner)) should be hyphens when used in the CLI.

**Comment by SunnyAgrawal12** [comment]
I have also faced this issue and I thought the documentation was wrong about the username part. But I tried multiple things and if you try --user in the command instead of --user-name, it will work.
