### ISSUE TITLE
Error handling for --config-dir YAMLs

### ISSUE THREAD

**Issue by nehanene15** [GoogleCloudPlatform/professional-services-data-validator#659]
When running YAMLs from a config directory, we should catch and handle errors so that users can pinpoint which config failed.
Since each YAML runs as a separate validation, we should log the name of the YAML file that is currently being processed and if there was a failure.

**Comment by kanhaPrayas** [comment]
PR: https://github.com/GoogleCloudPlatform/professional-services-data-validator/pull/663
