### ISSUE TITLE
Schema Validation for target Postgres database - Did not recognize type 'xml' of column 'xmlevent'

### ISSUE THREAD

**Issue by pankajsgit** [GoogleCloudPlatform/professional-services-data-validator#667]
Source: SQL Server
Target: Postgres
Data Type on Source: XML
Data Type on Target: XML

When validating the schema for Postgres as target, the DVT is unable to recognize the "xml" data type. 

Failed msg:
/usr/local/lib/python3.7/dist-packages/sqlalchemy/dialects/postgresql/base.py:3199: SAWarning: Did not recognize type 'xml' of column 'xmlevent'

Result:
 Schema            │ Schema            │ []       │ dbo.databaselog     │ dbo.databaselog     │ xmlevent             │ xmlevent             │ string[non-nullable] │ null                 │ fail

**Comment by nehanene15** [comment]
Unfortunately XML is not a supported type in SQLAlchemy Postgres dialect, therefore it is not recognized. You can exclude it from the validation with `--exclusion-columns`
