### ISSUE TITLE
Add support for automatic IAM authentication to Cloud SQL

### ISSUE THREAD

**Issue by ghost** [GoogleCloudPlatform/professional-services-data-validator#669]
A username and password are expected when connecting to a Cloud SQL for Postgres database. Add support for automatic IAM authentication using the [cloud-SQL-python-connector.](https://github.com/GoogleCloudPlatform/cloud-sql-python-connector) .

**Comment by ghost** [comment]
Running the auth proxy as a sidecar and providing a dummy password is a good enough workaround for me. Closing.

**Comment by naher** [comment]
hi, is there any documentation or example on how to set up a postgres connection for the professional-services-data-validator using AWS IAM?
