### ISSUE TITLE
Making primary key flag compulsory in custom-query-row validation

### ISSUE THREAD

**Issue by piyushsarraf** [GoogleCloudPlatform/professional-services-data-validator#670]
Earlier primary key was not mandatory because the hash values were compared with `hash_all` column as reference, but after recent [change](https://github.com/GoogleCloudPlatform/professional-services-data-validator/commit/a7f800d9958b3e971ea99eade679cfc77c192c7c#diff-e55665966f6165967c646d72cbfde78c62ce8c1cf32149dfbfe0a5c3e3a4fda9R295-R299) where hash values are getting compared with `primary key` column as reference, DVT throws error of None primary  key if `--primary_key` flag is not present.

**Comment by nehanene15** [comment]
This can be a sub-issue of Issue #673
