### ISSUE TITLE
Fix dependency resolution errors for google.auth

### ISSUE THREAD

**Issue by letmardi** [GoogleCloudPlatform/professional-services-data-validator#671]
The versions of the libraries (google-auth==1.35.0; google-auth-oauthlib==0.6.0) conflict with each other and give an error:
`ImportError: ‘external_account_authorized_user’ from ‘google.auth’ `
This is due to the update: https://github.com/googleapis/google-auth-library-python-oauthlib/commit/f8a15f75115ed5ef3ea47b50a707459ed62a8f48
Please update dependencies in google-pso-data-validator.

**Comment by nehanene15** [comment]
What version of the tool are you using?

**Comment by nehanene15** [comment]
Is this still an issue? If not, I will be closing this in the next week. Thanks.
