### ISSUE TITLE
Optimize CLI tools arg parser

### ISSUE THREAD

**Issue by nehanene15** [GoogleCloudPlatform/professional-services-data-validator#673]
Currently the arg parser does not make use of all the features of [argparse](https://docs.python.org/3/library/argparse.html). We should ensure that for the subparsers, we can fail fast if some required args are not provided, or if only certain values are accepted by using the `required` or `choices` or `default` parameters ([Reference](https://docs.python.org/3/library/argparse.html#quick-links-for-add-argument))

We should also remove support for the data-validation run command. ([Example](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/data_validation/cli_tools.py#L213))

**Comment by nehanene15** [comment]
Currently, the column level parser also accepts hash, concat, comp-fields which makes the `data-validation validate column -h` command invalid.

**Comment by mohdt786** [comment]
Issues solved:

1. deprecated: Remove support for data-validation run-config command
2. test: 🎨 Remove tests for run-config command
3. fix: 🔥 Add a subparser for validate custom-query: validate custom-query row and validate custom-query column
4. fix: Remove random-row and added --comparison-fields support for custom-query row validation
5. fix: Make --hash, --concat, and --comparison-fields required and mutually exclusive for validate row command.
6. fix: Remove --hash, --concat, and --comparison-fields from validate column command
7. fix: Split optional and required arguments into different groups for better visibility while using -h flag
8. deprecated: Deprecate --result-handler-config and --type in validate and generate-table-partitions command
9. fix: Remove data-validation run-config -c ex_yaml.yaml from cli usage doc_string
10. fix: Remove --tables-list from validate custom-query command
11. fix: Remove --grouped-columns from validate row command
12. fix: Remove --use-random-row and --random-row-batch-size for generate-table-partitions command
13. fix: Remove primary-keys argument for validate column and validate custom-query column
14. feat: Add support for --comparison-fields for validate custom-query row
15. refactor: 🎨 Refactored cli_tools.py and main.py
16. fix: Reorganise function build_config_managers_from_args()
17. docs: Update custom-query CLI command in README.md

**Comment by mohdt786** [comment]
Updated:

1. Remove `run-config` command
2. Make `--hash`, `--concat`, and `--comparison-fields` required and mutually exclusive for `validate row` command.
3. Remove `--hash`, `--concat`, and `--comparison-fields` from `validate column` command
4. Split optional and required arguments into different groups for better visibility while using `-h` flag
5. Deprecate `--result-handler-config` and `--type` in `validate` and `generate-table-partitions` command
6. Remove `data-validation run-config -c ex_yaml.yaml` from cli usage doc_string
7. Remove `--tables-list` from `validate custom-query` command
8. Remove `--grouped-columns` from `validate row` command
9. Remove `--use-random-row` and `--random-row-batch-size` for generate-table-partitions command
