### ISSUE TITLE
validate schema: --allow-list option prevents some required mappings

### ISSUE THREAD

**Issue by nj1973** [GoogleCloudPlatform/professional-services-data-validator#683]
There is a secondary check in the code behind `--allow-list` that ensures the base data type is the same in source and target.
It will accept mapping of `decimal(10,0)` to `decimal(8,0)` but rejects `decimal(10,0)` to `int64` (`bigint`). This is rejected because the base data type of `decimal` is `decimal` and that is not the same as the base datatype of `int64` which is `int`.

This prevents these useful mappings:

- date -> timestamp
- timestamp -> date
- decimal(?,0) -> int[16/32/64]

We need to understand why these mappings were prevented and, ideally, extend the accepted base types to include those above.

**Comment by nehanene15** [comment]
Issue #706 is related - timestamp -> timestamp('utc') could not be passed into the allowlist
