### ISSUE TITLE
Custom Query Row validation for MSSQL to BQ fails

### ISSUE THREAD

**Issue by Raniksingh** [GoogleCloudPlatform/professional-services-data-validator#691]
**Command 1:**
data-validation validate custom-query \
--custom-query-type row \
--source-query-file ss_row_validate_src.sql \
--target-query-file ss_row_validate_tgt.sql \
-sc MSSQL_CONN \
-tc BQ_CONN \
--primary-keys custid

Error : 

File "/home/madhujain/env/lib/python3.9/site-packages/ibis/backends/base_sqlalchemy/alchemy.py", line 1559, in _format_table
    result = result.alias(alias)
AttributeError: 'str' object has no attribute 'alias'

**Command 2:**
data-validation validate custom-query \
--custom-query-type row \
--source-query-file ss_cust_sum_src.sql \
--target-query-file ss_cust_sum_tgt.sql \
-sc MSSQL_CONN \
-tc BQ_CONN \
--primary-keys custid

Error : 
File "/home/madhujain/env/lib/python3.9/site-packages/third_party/ibis/ibis_mssql/client.py", line 264, in <listcomp>
    type_map[row[1]] for row in cur.proxy._cursor_description()
KeyError: <class 'decimal.Decimal'>

**Comment by bnb012008** [comment]
Could you post the connection json (MSSQL_CONN) for mssql?

**Comment by madhu-jain** [comment]
Connection json : 

{"source_type": "MSSQL", "host": "10.25.192.5", "port": "1433", "user": "user_name", "password": "********", "database": "tempdb"}

**Comment by madhu-jain** [comment]
As comp-fields is not supported in Custom Query - Row Validation. We tried doing Concat comparison (only for INT and STRING datatype) using Custom query as below : 

**Source SQL** - select custid, custname, age from dbo.customer
**Target SQL** - select custid, custname, age from paras-sandbox-364713.dlp.customer

**Command Run :** 

data-validation validate custom-query \
--custom-query-type row \
--source-query-file ss_row_validate_src.sql \
--target-query-file ss_row_validate_tgt.sql \
-sc MSSQL_CONN \
-tc BQ_CONN \
--concat 'custname,age' \
--primary-keys custid \
--bq-result-handler paras-sandbox-364713.data_validator.results

**Error :** 

​​AttributeError: 'str' object has no attribute 'alias'

**Comment by madhu-jain** [comment]
Also tried Custom Query - Row Validation for datetime field. Datetime field converted to STRING in both source and target as below : 

**Source SQL** - select custid,custname,convert(varchar, load_ts, 21) as load_ts from tempdb.dbo.customer;
**Target SQL** - select custid,custname,substr(string(load_ts), 1, 23) as load_ts from paras-sandbox-364713.dlp.customer;

**Command Run :** 

data-validation validate custom-query \
--custom-query-type row \
--source-query-file ss_ts_src.sql \
--target-query-file ss_ts_tgt.sql \
-sc MSSQL_CONN \
-tc BQ_CONN \
--concat 'custname,load_ts' \
--primary-keys custid \
--bq-result-handler paras-sandbox-364713.data_validator.results

**Error :** 

AttributeError: 'str' object has no attribute 'alias'
