### ISSUE TITLE
DVT should consider translation API for validation

### ISSUE THREAD

**Issue by rohangoogle** [GoogleCloudPlatform/professional-services-data-validator#698]
DVT fails the check if the data type does not match exactly between Hive and Bigquery. For example BQ translation API converts int32 in hive to int64 in BQ. DVT marks this check as fail as it goes for exact match at both the ends and ignores the inputs from translation API.

**Comment by Raniksingh** [comment]
For such scenarios you can pass --allow-list argument where you can provide mappings of source and destination. Refer this [link](https://github.com/GoogleCloudPlatform/professional-services-data-validator#schema-validations)
