### ISSUE TITLE
Document minimum privileges required for Oracle DVT connection

### ISSUE THREAD

**Issue by nj1973** [GoogleCloudPlatform/professional-services-data-validator#705]
Most Oracle customers will not tolerate using the SYSTEM account for validations and will want to know the minimum privileges required so they can create a specific read only account following the principle of least privilege.

We already do this for BigQuery: https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/docs/connections.md#google-bigquery

We should do something similar for the Oracle connectivity section (and in future for other RDBMSs too).

**Comment by slatawa** [comment]
Closing the ticket. Doc updated under -  https://github.com/GoogleCloudPlatform/professional-services-data-validator/commit/a7889bf7c8b5106a4144a73a0767c2b59b4c09b0
