### ISSUE TITLE
Row and column validation different result handler table?

### ISSUE THREAD

**Issue by bnb012008** [GoogleCloudPlatform/professional-services-data-validator#707]
When I run a validation and write it to a CSV, schema and column validations have different column names.  Does this mean that I have to deploy different BQ tables to hold the results for schema and column?

**Comment by nehanene15** [comment]
No, they both will can write to the same table. The results that are shown with the standard out text handler are summarized outputs with only the columns that are most important to that validation type.

The table in BigQuery will have the most data on the validations and can be written to for row, schema, and column validations.
