### ISSUE TITLE
SQL Server Row Validation - throwing error for Random rows as 50000

### ISSUE THREAD

**Issue by madhu-jain** [GoogleCloudPlatform/professional-services-data-validator#711]
In Row Validation - Field Comparison between SQL server(source) and Big query(target) with source having ~13mn records is failing for random 50k records

**Command Used :** 

data-validation validate row \
-sc MSSQL_CONN \
-tc BQ_CONN \
-tbls tempdb.dbo.dvt_prices=paras-sandbox-364713.dlp.dvt_prices \
--primary-keys sr_no \
-comp-fields symbol,log_date,close_stock,volume,adjusted,stock_load_date,is_active \
-rr \
-rbs 50000 \
--bq-result-handler paras-sandbox-364713.data_validator.results

**Error :** 

pyodbc.ProgrammingError: ('The SQL contains -15536 parameter markers, but 50000 parameters were supplied', 'HY000')

**Comment by madhu-jain** [comment]
We tried with random rows as 10000, still facing issue.

**Command used :** 

data-validation validate row \
-sc MSSQL_CONN \
-tc BQ_CONN \
-tbls tempdb.dbo.dvt_prices=paras-sandbox-364713.dlp.dvt_prices \
--primary-keys sr_no \
-comp-fields symbol,log_date,close_stock,volume,adjusted,stock_load_date,is_active \
-rr \
-rbs 10000 \
--bq-result-handler paras-sandbox-364713.data_validator.results

**Error :** 

pyodbc.Error: ('07002', '[07002] [Microsoft][ODBC Driver 17 for SQL Server]COUNT field incorrect or syntax error (0) (SQLExecDirectW)')

**Comment by madhu-jain** [comment]
Seems random rows as 2000 is supported for Row Validation

Command used : 

data-validation validate row \
-sc MSSQL_CONN \
-tc BQ_CONN \
-tbls tempdb.dbo.dvt_prices=paras-sandbox-364713.dlp.dvt_prices \
--primary-keys sr_no \
-comp-fields symbol,volume \
-rr \
-rbs 2000 \
--bq-result-handler paras-sandbox-364713.data_validator.results

Ouput : Comparison result returned successfully

**Comment by nehanene15** [comment]
This is a database and network packet size limitation - there is no exact hard limit, but every SQL batch has to fit in [Batch Size Limit](http://msdn.microsoft.com/en-us/library/ms143432.aspx): 65,536 * Network Packet Size.
The limit will be different depending on the machine DVT is run on and the runtime conditions.

We recommend using selective filters to avoid having thousands of elements in the IN() clause.

See [here](https://stackoverflow.com/questions/1869753/maximum-size-for-a-sql-server-query-in-clause-is-there-a-better-approach) for more details.
