### ISSUE TITLE
Issue in Generating Table Partitions

### ISSUE THREAD

**Issue by madhu-jain** [GoogleCloudPlatform/professional-services-data-validator#712]
Facing issue in Generating Table Partitions for Comparison between SQL server and Big query of large tables.

**Command used :** 

data-validation generate-table-partitions
-sc MSSQL_CONN \
-tc BQ_CONN \
-tbls tempdb.dbo.dvt_prices=paras-sandbox-364713.dlp.dvt_prices \
--primary-keys sr_no \
-comp-fields symbol,log_date,close_stock,volume,adjusted,stock_load_date,is_active \
-cdir `/home/madhujain` \
-pn 10 \ 
-partkey sr_no \
--bq-result-handler paras-sandbox-364713.data_validator.results

**Error :** 

data-validation: error: argument command: invalid choice: 'generate-table-partitions' (choose from 'validate', 'run-config', 'configs', 'connections', 'find-tables', 'query', 'beta')

**Comment by madhu-jain** [comment]
We tried below commands using cloud shell to clone repo and pip install but unable to connect to MSSQL.

1) git clone https://github.com/GoogleCloudPlatform/professional-services-data-validator

2) pip install -e /home/madhujain/professional-services-data-validator

3) pip install pyodbc

4) data-validation connections add --connection-name MSSQL_CONN MSSQL --host=34.71.165.179 --port=1433 --user=sqlserver --password=sql-12345! --database tempdb
(connecting using external IP)
Error : 
data_validation.exceptions.DataClientConnectionFailure: Connection Type "MSSQL" could not connect: pip install pyodbc

5) git branch
output : * develop

6) git describe --tags
output : V2.8.0-5-g21a26af

**Comment by rishabkhawad** [comment]
Hello, did you follow the steps on the [link](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server) for the connection issue?

**Comment by nehanene15** [comment]
Was this connection issue resolved?
