### ISSUE TITLE
DB2 vs BQ - Row Validation - Custom Query throwing error

### ISSUE THREAD

**Issue by madhu-jain** [GoogleCloudPlatform/professional-services-data-validator#715]
Row Validation - comp field comparison between db2 and Bigquery throwing error. As comparison is not supported in Custom query row validation. We created a yaml file for comparison and configured it to run as Custom query, it was throwing error.

**YAML Config :** customer_rv_cq.yaml

result_handler:
  project_id: rite-aid-371612
  table_id: data_validator.results
  type: BigQuery
source: DB2_CONN
target: BQ_CONN
validations:
- calculated_fields: []
  comparison_fields:
  - cast: null
    field_alias: custname
    source_column: custname
    target_column: custname
  - cast: null
    field_alias: age
    source_column: age
    target_column: age
  filter_status: null
  filters: []
  format: table
  labels: []
  primary_keys:
  - cast: null
    field_alias: custid
    source_column: custid
    target_column: custid
  random_row_batch_size: '1'
  schema_name: null
  source_query: select custid, custname, age from POCDB2.CUSTOMER 
  table_name: null
  target_query: SELECT custid, custname, age FROM rite-aid-371612.bq_dvt.customer_dvt 
  target_schema_name: null
  target_table_name: null
  threshold: 0.0
  type: Custom-query 
  use_random_rows: true

**Execution Command :** data-validation run-config -c customer_rv_cq.yaml

**Error :** 

raise exc.NoSuchTableError(table.name)
sqlalchemy.exc.NoSuchTableError: None

**Comment by nehanene15** [comment]
Custom query isn't supported for DB2 so errors are expected. We can reopen this if it's still an issue after #714 is closed.
