### ISSUE TITLE
Getting 'Token has been expired or revoked' error while writing result to Big Query

### ISSUE THREAD

**Issue by ajeesh2705** [GoogleCloudPlatform/professional-services-data-validator#728]
Hi, 
I am trying this tool to write the validation results to BiqQuery. but I am getting this error . I am using my user account. I have write to create table and insert etc... not sure why I am getting below error. I may be not setting up credentials correctly, Can you help how to use google user account to write validation results to Big Query

google.auth.exceptions.RefreshError: ('invalid_grant: Token has been expired or revoked.'

**Comment by nehanene15** [comment]
You can run `gcloud auth application-default login` and ensure you have permissions to write to the BigQuery dataset/table.

**Comment by ajeesh2705** [comment]
Perfect, it worked, Thanks.  I was running `gcloud auth login --update-adc`  

Do you think it may be better to update this doc section with this details ? (https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/docs/installation.md#setup) with this `A Google user account with appropriate permissions`
