### ISSUE TITLE
Seems like uuid is not supported 

### ISSUE THREAD

**Issue by ajeesh2705** [GoogleCloudPlatform/professional-services-data-validator#729]
I am trying to do a hash comparison of all columns of 2 postgres table. I am encountering the following error,  not sure what's going wrong here.

data-validation validate row -sc source -tc target -tbls postgres_table --primary-keys id --hash '*' -rr -rbs 10  

  File "/opt/anaconda3/lib/python3.9/site-packages/ibis/expr/rules.py", line 219, in value
    raise com.IbisTypeError(
ibis.common.exceptions.IbisTypeError: Given argument with datatype uuid is not subtype of string nor implicitly castable to it

**Comment by ajeesh2705** [comment]
If I remove some uuid from --hash list, its working.

**Comment by nehanene15** [comment]
This is supported with the Ibis upgrade PR #894
