### ISSUE TITLE
Impala DVT connection does not allow use-ssl parameter that is allowed in impyla under the hood.

### ISSUE THREAD

**Issue by wt1309** [GoogleCloudPlatform/professional-services-data-validator#743]
The use-ssl parameter is not included in the DVT connection parameters, however, the Impala connection I am working with today is kerberized and requires SSL flag to be true. I performed the following to get this to work. Plan to eventually submit a pull request once I get some time, but for now, here is the solution: 

1. Missing python library: sudo pip3 install kerberos
2. Used port 21050 instead of 21000 (21000 works for CLI impala shell)
3. Update DVT source code to accomodate new parameter use_ssl

- 	Add following lines of code after Line 35, 42,and 48 respectively:

	professional-services-data-validator/third_party/ibis/ibis_impala/api.py

	after line 35: use_ssl=False
	after line 42: use_ssl = (use_ssl, False)[use_ssl is None]
	after line 48: use_ssl=use_ssl,

- 	Add the following line of code after Line 131 in:

	professional-services-data-validator/data_validation/cli_tools.py 

	after line 131: ["use_ssl", "Use SSL when connecting to HiveServer2 (default is False)"],

4. cd to professional-services-data-validator folder
5. Then run command to build new code: sudo python3 -m pip install . 

Now this connection should work: 
data-validation connections add --connection-name <Conneciton_Name> Impala --host <hostname> --auth-mechanism GSSAPI --kerberos-service-name impala --port 21050 **--use-ssl True**

**Comment by mloeberc** [comment]
closed by PR #790
