### ISSUE TITLE
validate schema: Enhancements to --allow-list option

### ISSUE THREAD

**Issue by nj1973** [GoogleCloudPlatform/professional-services-data-validator#751]
**Enhancement 1**
Oracle does not have native integral data types like int, bigint, smallint. All numbers are decimal in nature.
This means validation of a migration from Oracle to PostgreSQL is generating a lot of `--allow-list` entries. Example below from a simple 3 table validation:
```
--allow-list="decimal(38,0):int32[non-nullable],decimal(38,0):int32,decimal(38,0):int32[non-nullable],decimal(3,0):int32,decimal(3,0):int16[non-nullable],decimal(6,0):int32[non-nullable]"
```

I suspect we'll have similar challenges for Oracle to BigQuery migrations.

It would be a nice option to be able to provide decimal precision as a range, for example:

`decimal(1-9,0):int32`: Matches any decimal precision between 1 and 8, which are all valid for int32.
`decimal(1-18,0):int64`: Matches any decimal precision between 1 and 18, which are all valid for int64.

Or perhaps use a wildcard instead which is more flexible, but less precise. For example:

`decimal([1-9]?,0):int32`: Matches any decimal precision between 1 and 8, which are all valid for int32.
`decimal([0-9]+,0):int64`: Matches any decimal precision between 1 and 8, which are all valid for int32.

**Enhancement 2**
I've also noticed that spaces in the decimal break the comparison. But that is how they are represented in the final report.

For example if I take the reported failure values from below to construct an `--allow-list` option:
```
═╤══════════════════════╤════════════════════╤═════════════════════╤═════════════════════╕
 │ target_column_name   │ source_agg_value   │ target_agg_value    │ validation_status   │
═╪══════════════════════╪════════════════════╪═════════════════════╪═════════════════════╡
 │ weight_class         │ decimal(3, 0)      │ int16[non-nullable] │ fail                │
```

```
-allow-list="decimal(3, 0):int16[non-nullable]"
```

Then the status remains `fail`. I need to remove the space from the decimal spec. e.g.:
```
-allow-list="decimal(3,0):int16[non-nullable]"
```

This is pretty trivial but when there are several 10s of decimal combinations to cater for it is easy to miss a space or two.

**Enhancement 3**
In the example below I have two Oracle NUMBER(38) columns, one has been mapped for BIGINT in PostgreSQL and the other to DECIMAL(1000).
Oracle:
```
create table dvt_test.tab_num38 (
  id number(2), col1 number(38), col2 number(38)
);
```
PostgreSQL:
```
create table dvt_test.tab_num38 (
  id int, col1 decimal(1000), col2 bigint
);
```

The basic output for these columns from DVT is:
```
╤══════════════════════╤════════════════════╤════════════════════╤═══════════════
│ target_column_name   │ source_agg_value   │ target_agg_value   │ status
╪══════════════════════╪════════════════════╪════════════════════╪═══════════════
│ col1                 │ decimal(38, 0)     │ decimal(1000, 0)   │ fail
┼──────────────────────┼────────────────────┼────────────────────┼───────────────
│ col2                 │ decimal(38, 0)     │ int64              │ fail
╧══════════════════════╧════════════════════╧════════════════════╧═══════════════
```

I have no way of mapping both types using `-allow-list`, only the latter mapping takes effect.
`--allow-list="decimal(38,0):int64,decimal(38,0):decimal(1000,0)"`:
```
╤══════════════════════╤════════════════════╤════════════════════╤═══════
│ target_column_name   │ source_agg_value   │ target_agg_value   │ status
╪══════════════════════╪════════════════════╪════════════════════╪═══════
│ id                   │ decimal(2, 0)      │ int32              │ fail
┼──────────────────────┼────────────────────┼────────────────────┼───────
│ col2                 │ decimal(38, 0)     │ int64              │ fail
╧══════════════════════╧════════════════════╧════════════════════╧═══════
```

`--allow-list="decimal(38,0):decimal(1000,0),decimal(38,0):int64"`:
```
╤══════════════════════╤════════════════════╤════════════════════╤════════
│ target_column_name   │ source_agg_value   │ target_agg_value   │ status
╪══════════════════════╪════════════════════╪════════════════════╪════════
│ id                   │ decimal(2, 0)      │ int32              │ fail
┼──────────────────────┼────────────────────┼────────────────────┼────────
│ col1                 │ decimal(38, 0)     │ decimal(1000, 0)   │ fail
╧══════════════════════╧════════════════════╧════════════════════╧════════
```

**Comment by nehanene15** [comment]
Another customer request was to support a config file for the allowlist, i.e. `--allow-list orace_pg.yaml` so they can reuse mappings between certain systems and it will prevent long configs on the command line

**Comment by nj1973** [comment]
@nehanene15 , do you think we need to create a new issue for "Enhancement 1" and support for a config file? I can raise if you agree.

**Comment by nj1973** [comment]
Ignore that question I answered it myself and raised: https://github.com/GoogleCloudPlatform/professional-services-data-validator/issues/887
