### ISSUE TITLE
Option for simpler report output grid

### ISSUE THREAD

**Issue by nj1973** [GoogleCloudPlatform/professional-services-data-validator#753]
By default the reported output of DVT is Tabulate `fancy_grid`, as seen in the `data_validation/result_handlers/text.py` code below:
```
            print(
                result_df.drop(self.cols_filter_list, axis=1).to_markdown(
                    tablefmt="fancy_grid", index=False
                )
```

This uses complex characters that are not copy/paste friendly and also inserts a grid line between each report row. For a row validation this can add up to a lot of non-essential noise on screen.

An alternative is to use `--format=text` but then we gain extra columns because `self.cols_filter_list` columns are not dropped and lose heading underlines.

This is obviously low priority but it would be nice if could control the `tablefmt` value hardcoded above. Perhaps any value other than `text`, `csv` and `json` could be passed to `to_markdown(tablefmt`?

**Comment by Raniksingh** [comment]
PR #802
