### ISSUE TITLE
Issue with environment variable PSO_DV_CONFIG_HOME

### ISSUE THREAD

**Issue by madhu-jain** [GoogleCloudPlatform/professional-services-data-validator#756]
Description : 

While using environment variable PSO_DV_CONFIG_HOME to fetch connection details and configuration yaml from GCS bucket, it expects 2 folders : connections and validations.

Given connection json would have sensitive information like password, it's not advisable to store connection json in GCS bucket instead create it at run time.
But when using variable PSO_DV_CONFIG_HOME, it seems it expect both connection json and config yaml reside in GCS bucket ie. both connections and validations are tightly coupled. 
Is it possible to decouple them?

**Comment by nehanene15** [comment]
Closed by #1129
