### ISSUE TITLE
Unable to connect to Google Cloud SQL using Public IP of SQL and credentials

### ISSUE THREAD

**Issue by rajenrishi** [GoogleCloudPlatform/professional-services-data-validator#757]
Hi ,

I am trying to add connection for google cloud SQL. Public IP of the MySQL server and credentials are available.
But when i try to add connection, 
data_validation.exceptions.DataClientConnectionFailure: COnnection Type "MySQL" could not connect: (pymysql.err.OperationsError) (2003, "Can't connect to MySQL server on <IP> (timeout)")

I am running the command in Google cloud shell.

Please help me to resolve this issue.

Thank You,
Rajendra

**Comment by nehanene15** [comment]
Even if you have a public IP, you would need to add the Cloud Shell IP to the list of authorized addresses or address ranges on your CloudSQL instance. I would recommend using the CloudSQL proxy to connect and configure the DVT connection to point to localhost/port 3306

**Comment by nehanene15** [comment]
Has this issue been resolved?
