### ISSUE TITLE
--filters feature not working on DB2 No translation rule for <class 'third_party.ibis.ibis_addon.operations.RawSQL'>

### ISSUE THREAD

**Issue by vc49as** [GoogleCloudPlatform/professional-services-data-validator#760]
tried this:  --filters "code_version='1.0.0'" and got ibis.common.exceptions.OperationNotDefinedError: No translation rule for <class 'third_party.ibis.ibis_addon.operations.RawSQL'>

Traceback (most recent call last):
  File "C:\Users\m045517\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\m045517\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\m045517\AppData\Local\Google\Cloud SDK\professional-services-data-validator\venv\Scripts\data-validation.exe\__main__.py", line 7, in <module>
  File "C:\Users\m045517\AppData\Local\Google\Cloud SDK\professional-services-data-validator\venv\lib\site-packages\data_validation\__main__.py", line 600, in main
    validate(args)
  File "C:\Users\m045517\AppData\Local\Google\Cloud SDK\professional-services-data-validator\venv\lib\site-packages\data_validation\__main__.py", line 576, in validate
    run(args)
  File "C:\Users\m045517\AppData\Local\Google\Cloud SDK\professional-services-data-validator\venv\lib\site-packages\data_validation\__main__.py", line 536, in run
    run_validations(args, config_managers)
  File "C:\Users\m045517\AppData\Local\Google\Cloud SDK\professional-services-data-validator\venv\lib\site-packages\data_validation\__main__.py", line 492, in run_validations
    run_validation(config_manager, verbose=args.verbose)
  File "C:\Users\m045517\AppData\Local\Google\Cloud SDK\professional-services-data-validator\venv\lib\site-packages\data_validation\__main__.py", line 467, in run_validation
    validator.execute()
  File "C:\Users\m045517\AppData\Local\Google\Cloud SDK\professional-services-data-validator\venv\lib\site-packages\data_validation\data_validation.py", line 98, in execute
    result_df = self._execute_validation(
  File "C:\Users\m045517\AppData\Local\Google\Cloud SDK\professional-services-data-validator\venv\lib\site-packages\data_validation\data_validation.py", line 335, in _execute_validation
    source_df = futures[0].result()
  File "C:\Users\m045517\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "C:\Users\m045517\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\Users\m045517\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\m045517\AppData\Local\Google\Cloud SDK\professional-services-data-validator\venv\lib\site-packages\ibis\client.py", line 220, in execute
    query = self._get_query(query_ast, **kwargs)
  File "C:\Users\m045517\AppData\Local\Google\Cloud SDK\professional-services-data-validator\venv\lib\site-packages\ibis\client.py", line 226, in _get_query
    return self.query_class(self, dml, **kwargs)
  File "C:\Users\m045517\AppData\Local\Google\Cloud SDK\professional-services-data-validator\venv\lib\site-packages\ibis\client.py", line 40, in __init__
    self.compiled_sql = sql.compile()
  File "C:\Users\m045517\AppData\Local\Google\Cloud SDK\professional-services-data-validator\venv\lib\site-packages\ibis\backends\base_sqlalchemy\compiler.py", line 55, in compile
    compiled_queries = [q.compile() for q in self.queries]
  File "C:\Users\m045517\AppData\Local\Google\Cloud SDK\professional-services-data-validator\venv\lib\site-packages\ibis\backends\base_sqlalchemy\compiler.py", line 55, in <listcomp>
    compiled_queries = [q.compile() for q in self.queries]
  File "C:\Users\m045517\AppData\Local\Google\Cloud SDK\professional-services-data-validator\venv\lib\site-packages\ibis\backends\base_sqlalchemy\alchemy.py", line 1333, in compile
    frag = step(frag)
  File "C:\Users\m045517\AppData\Local\Google\Cloud SDK\professional-services-data-validator\venv\lib\site-packages\ibis\backends\base_sqlalchemy\alchemy.py", line 1420, in _add_where
    args = [
  File "C:\Users\m045517\AppData\Local\Google\Cloud SDK\professional-services-data-validator\venv\lib\site-packages\ibis\backends\base_sqlalchemy\alchemy.py", line 1421, in <listcomp>
    self._translate(pred, permit_subquery=True) for pred in self.where
  File "C:\Users\m045517\AppData\Local\Google\Cloud SDK\professional-services-data-validator\venv\lib\site-packages\ibis\backends\base_sqlalchemy\compiler.py", line 1598, in _translate
    return translator.get_result()
  File "C:\Users\m045517\AppData\Local\Google\Cloud SDK\professional-services-data-validator\venv\lib\site-packages\ibis\backends\base_sqlalchemy\compiler.py", line 1362, in get_result
    translated = self.translate(self.expr)
  File "C:\Users\m045517\AppData\Local\Google\Cloud SDK\professional-services-data-validator\venv\lib\site-packages\ibis\backends\base_sqlalchemy\compiler.py", line 1403, in translate
    raise com.OperationNotDefinedError(
ibis.common.exceptions.OperationNotDefinedError: No translation rule for <class 'third_party.ibis.ibis_addon.operations.RawSQL'>

**Comment by helensilva14** [comment]
@nehanene15 this issue is similar to the one solved by this commit https://github.com/GoogleCloudPlatform/professional-services-data-validator/commit/069378271fdab08af8bfe984590b63a45c199bbb, do you know what line could be added to support DB2?

**Comment by vc49as** [comment]
Unfortunately, no, I do not know. Started investigating but could not afford spending more time on this.
Thanks,
Nataliya

From: Helen Cristina ***@***.***>
Sent: Monday, March 13, 2023 3:46 PM
To: GoogleCloudPlatform/professional-services-data-validator ***@***.***>
Cc: Batrachenko, Nataliya V. ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [GoogleCloudPlatform/professional-services-data-validator] --filters feature not working on DB2 No translation rule for <class 'third_party.ibis.ibis_addon.operations.RawSQL'> (Issue #760)


@nehanene15<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnehanene15&data=05%7C01%7CBatrachenko.Nataliya%40mayo.edu%7C3eb14423e7704326479c08db2403fc44%7Ca25fff9c3f634fb29a8ad9bdd0321f9a%7C0%7C0%7C638143371767890810%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=w4MAJw9Gd2%2BziVC4%2BnIcBGlidVmrOLmML8wVQml7qjg%3D&reserved=0> this issue is similar to the one solved by this commit 0693782<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FGoogleCloudPlatform%2Fprofessional-services-data-validator%2Fcommit%2F069378271fdab08af8bfe984590b63a45c199bbb&data=05%7C01%7CBatrachenko.Nataliya%40mayo.edu%7C3eb14423e7704326479c08db2403fc44%7Ca25fff9c3f634fb29a8ad9bdd0321f9a%7C0%7C0%7C638143371767890810%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Hc2v%2FXylVcVVC8ydvLrEbLRLFIghXceegnxE39cLynM%3D&reserved=0>, do you know what line could be added to support DB2?

-

**Comment by nehanene15** [comment]
> @nehanene15 this issue is similar to the one solved by this commit [0693782](https://github.com/GoogleCloudPlatform/professional-services-data-validator/commit/069378271fdab08af8bfe984590b63a45c199bbb), do you know what line could be added to support DB2?

Yeah, we can add the same line to ibis_addon/operations.py to add this functionality... something like this:
```
DB2ExprTranslator_registry[RawSQL] = sa_format_raw_sql
```

**Comment by vc49as** [comment]
Hope this works.
I am new to this tool...

From: Neha Nene ***@***.***>
Sent: Monday, March 13, 2023 4:04 PM
To: GoogleCloudPlatform/professional-services-data-validator ***@***.***>
Cc: Batrachenko, Nataliya V. ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [GoogleCloudPlatform/professional-services-data-validator] --filters feature not working on DB2 No translation rule for <class 'third_party.ibis.ibis_addon.operations.RawSQL'> (Issue #760)


@nehanene15<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnehanene15&data=05%7C01%7CBatrachenko.Nataliya%40mayo.edu%7C6c2882d29cd541fe182408db240675f5%7Ca25fff9c3f634fb29a8ad9bdd0321f9a%7C0%7C0%7C638143382398089907%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=jZYgIkTkylRcCBFwBdRNXlK3KAzi9qezInP66CDMfkc%3D&reserved=0> this issue is similar to the one solved by this commit 0693782<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FGoogleCloudPlatform%2Fprofessional-services-data-validator%2Fcommit%2F069378271fdab08af8bfe984590b63a45c199bbb&data=05%7C01%7CBatrachenko.Nataliya%40mayo.edu%7C6c2882d29cd541fe182408db240675f5%7Ca25fff9c3f634fb29a8ad9bdd0321f9a%7C0%7C0%7C638143382398089907%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=WWXXqEGPOJECOkLu5kAEreFAWFkitwXhHVtl%2BnyjBYU%3D&reserved=0>, do you know what line could be added to support DB2?

Yeah, we can add the same line to ibis_addon/operations.py to add this functionality... something like this:

DB2ExprTranslator_registry[RawSQL] = sa_format_raw_sql

-

**Comment by helensilva14** [comment]
> Hope this works. I am new to this tool... 

@vc49as I'll add this line to our code in a new branch and notify you in this thread when I finish  so you can test it afterwards!

**Comment by vc49as** [comment]
Thanks much!

From: Helen Cristina ***@***.***>
Sent: Monday, March 13, 2023 4:13 PM
To: GoogleCloudPlatform/professional-services-data-validator ***@***.***>
Cc: Batrachenko, Nataliya V. ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [GoogleCloudPlatform/professional-services-data-validator] --filters feature not working on DB2 No translation rule for <class 'third_party.ibis.ibis_addon.operations.RawSQL'> (Issue #760)


Hope this works. I am new to this tool...

@vc49as<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvc49as&data=05%7C01%7CBatrachenko.Nataliya%40mayo.edu%7Cfd41d963b04842e41b6308db2407adcd%7Ca25fff9c3f634fb29a8ad9bdd0321f9a%7C0%7C0%7C638143387639113310%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=gIdlKr7VLK2g0e6oO2R%2BPnBOz0b7zq6CrYN%2BwdL99TQ%3D&reserved=0> I'll add this line to our code in a new branch and notify you in this thread when I finish so you can test it afterwards!

-

**Comment by helensilva14** [comment]
@vc49as Done! You can see the changes at #770, please check out to the specified branch  [issue760-db2-no-translation-rawsql](https://github.com/GoogleCloudPlatform/professional-services-data-validator/tree/issue760-db2-no-translation-rawsql) and install this version locally using `pip install .` . After that, please execute the same command you tried initially on this thread.

Let us know if it works, thanks!

**Comment by helensilva14** [comment]
Hi @vc49as! Have you been able to test the fix? If not, could you please try to do it within a week? Otherwise I'll consider the problem as fixed, merge the PR and close the issue. Thank you!

**Comment by vc49as** [comment]
Hi Cristina,

I do need to test this fix yet. My apologies for such a delay. Got pulled in different project.

Thanks Nataliya

From: Helen Cristina ***@***.***>
Sent: Thursday, March 30, 2023 1:30 PM
To: GoogleCloudPlatform/professional-services-data-validator ***@***.***>
Cc: Batrachenko, Nataliya V. ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [GoogleCloudPlatform/professional-services-data-validator] --filters feature not working on DB2 No translation rule for <class 'third_party.ibis.ibis_addon.operations.RawSQL'> (Issue #760)


Hi @vc49as<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvc49as&data=05%7C01%7CBatrachenko.Nataliya%40mayo.edu%7Ca9e687a2ca3048fe1c0708db314e4824%7Ca25fff9c3f634fb29a8ad9bdd0321f9a%7C0%7C0%7C638157984509220658%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=d9IYJsoQvysVUs%2FmxN39CzUsccv%2FM5DJyNv%2Br1tQQDU%3D&reserved=0>! Have you been able to test the fix? If not, could you please try to do it within a week? Otherwise I'll consider the problem as fixed, merge the PR and close the issue. Thank you!

-

**Comment by helensilva14** [comment]
No problem Nataliya, thanks for the quick response! I'll be waiting for your feedback on the test then!

**Comment by vc49as** [comment]
Hello Helen,

I have finally been able to install DVT from this branch  issue760-db2-no-translation-rawsql<https://github.com/GoogleCloudPlatform/professional-services-data-validator/tree/issue760-db2-no-translation-rawsql> and test. Did not see any change in behavior. Still getting the same error message 'No translation rule for <class 'third_party.ibis.ibis_addon.operations.RawSQL'>'

Thanks,
Nataliya


From: Helen Cristina ***@***.***>
Sent: Thursday, March 30, 2023 2:30 PM
To: GoogleCloudPlatform/professional-services-data-validator ***@***.***>
Cc: Batrachenko, Nataliya V. ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [GoogleCloudPlatform/professional-services-data-validator] --filters feature not working on DB2 No translation rule for <class 'third_party.ibis.ibis_addon.operations.RawSQL'> (Issue #760)


No problem Nataliya, thanks for the quick response! I'll be waiting for your feedback on the test then!

-

**Comment by helensilva14** [comment]
> Hello Helen, I have finally been able to install DVT from this branch issue760-db2-no-translation-rawsql<https://github.com/GoogleCloudPlatform/professional-services-data-validator/tree/issue760-db2-no-translation-rawsql> and test. Did not see any change in behavior. Still getting the same error message 'No translation rule for <class 'third_party.ibis.ibis_addon.operations.RawSQL'>' Thanks, Nataliya

Hi @vc49as, thank you for testing it! I see it, we need to review the fix then. Is it possible for your to share the validation command/SQL query you are trying to execute? Please be sure to remove any private information on it. This way we can be more assertive to work on this bug by simulating your use case!

**Comment by vc49as** [comment]
1.  data-validation validate row -sc db2_conn_test -tc bq_conn_stage -pk RECORD_ID -rr -rbs 3000 --filters "RECORD_ID<1000000" -comp-fields PATIENT_CLINIC_NUMBER,PROJECT_ID,DOC_TYPE -tbls cdr_nlp.annotation=ml-mps-adl-nlp-ingest-s-d6bd.phi_clinical_nlp_us_s.annotation_mv

2.  also created partitioning config files by RECORD_ID and ran this: data-validation configs run -c 'partitions_dir/cdr_nlp.annotation/0000.yaml'


Both commands failed with the same Exception: ibis.common.exceptions.OperationNotDefinedError: No translation rule for <class 'third_party.ibis.ibis_addon.operations.RawSQL'>





Thanks,

Nataliya

From: Helen Cristina ***@***.***>
Sent: Thursday, May 4, 2023 10:28 AM
To: GoogleCloudPlatform/professional-services-data-validator ***@***.***>
Cc: Batrachenko, Nataliya V. ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [GoogleCloudPlatform/professional-services-data-validator] --filters feature not working on DB2 No translation rule for <class 'third_party.ibis.ibis_addon.operations.RawSQL'> (Issue #760)


Hello Helen, I have finally been able to install DVT from this branch issue760-db2-no-translation-rawsqlhttps://github.com/GoogleCloudPlatform/professional-services-data-validator/tree/issue760-db2-no-translation-rawsql and test. Did not see any change in behavior. Still getting the same error message 'No translation rule for <class 'third_party.ibis.ibis_addon.operations.RawSQL'>' Thanks, Nataliya

Hi @vc49as<https://github.com/vc49as>, thank you for testing it! I see it, we need to review the fix then. Is it possible for your to share the validation command/SQL query you are trying to execute? Please be sure to remove any private information on it. This way we can be more assertive to work on this bug by simulating your use case!

-

**Comment by helensilva14** [comment]
Main changes have already been implemented by https://github.com/GoogleCloudPlatform/professional-services-data-validator/pull/894, ToChar not required at the moment.

Please, test your operation with the updated develop branch and if you find any problems, you can re-open this issue, thank you!

**Comment by vc49as** [comment]
Hello,

Unfortunately, I am skipping the testing. The project this fix was needed for has been completed, and I cannot spend time on this.
Thank you for the effort anyway!

Nataliya


From: Helen Cristina ***@***.***>
Sent: Tuesday, July 18, 2023 2:27 PM
To: GoogleCloudPlatform/professional-services-data-validator ***@***.***>
Cc: Batrachenko, Nataliya V. ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [GoogleCloudPlatform/professional-services-data-validator] --filters feature not working on DB2 No translation rule for <class 'third_party.ibis.ibis_addon.operations.RawSQL'> (Issue #760)


Main changes have already been implemented by #894<https://github.com/GoogleCloudPlatform/professional-services-data-validator/pull/894>, ToChar not required at the moment.

Please, test your operation with the updated develop branch and if you find any problems, you can re-open this issue, thank you!

-

**Comment by helensilva14** [comment]
No problem @vc49as, thanks a lot for your collaboration with us!
