### ISSUE TITLE
Issue with Hive connection from Data proc cluster Master VM

### ISSUE THREAD

**Issue by hbcvsuser** [GoogleCloudPlatform/professional-services-data-validator#769]
Im trying to connect hive onpremise 2.x version from the data proc cluster master VM where DVT is installed

data-validation connections add --connection-name HIVE_CONN Impala --host hivehost.com --port 2181 --database default

Im getting timed out error.
Could u pls let meknow about right process or steps?
The error now is 

    raise exceptions.DataClientConnectionFailure(msg)
data_validation.exceptions.DataClientConnectionFailure: Connection Type "Impala" could not connect: timed out
Thanks

**Comment by hbcvsuser** [comment]
Pls if anyonebody knows also try to comment the soln

**Comment by wt1309** [comment]
Is your on-premise Hive connection Kerberized? Also, have you checked with port # 10000? This is usually the default port for Hive.

**Comment by hbcvsuser** [comment]
@wt1309 Yes i changed the host and port modified to 10000 (HIVE) but still seeing some connection issues,
Working with cloudera to see how to enable connection because im seeing kerberos issues too

**Comment by nehanene15** [comment]
Closing as this was a connection issue unrelated to DVT
