### ISSUE TITLE
Incorrect Return code received while performing Count Validation- BQ vs BQ 

### ISSUE THREAD

**Issue by SwatiT17** [GoogleCloudPlatform/professional-services-data-validator#782]
Description: While running below YAML for Count validation, Source table wasn't existing because  of which validation failed but return code received was 0 for DVT ver 2.9.0.Whereas for version 2.6.0 for the same error return code was 0

YAML:
result_handler:
  project_id: rite-aid-pocs
  table_id: ra_data_validation.results
  type: BigQuery
source: BQ_CONN
target: BQ_CONN
validations:
- aggregates:
  - field_alias: count
    source_column: null
    target_column: null
    type: count
  custom_query_type: column
  filter_status: null
  filters: []
  format: table
  labels: 
  - !!python/tuple
    - table
    - generic_launch_date
  - !!python/tuple
    - date
    - '{{load_dt}}'
  random_row_batch_size: null
  schema_name: null
  source_query: select * from `rite-aid-pocs.ra_landing_ext.generic_launch_date_ext_tb`
    where ra_load_dte = '{{load_dt}}'
  table_name: null
  target_query: select * from `rite-aid-pocs.ra_landing.generic_launch_date` where
    ra_load_dte = '{{load_dt}}'
  target_schema_name: null
  target_table_name: null
  threshold: 0.0
  type: Custom-query
  use_random_rows: null

Return code screenshot for version 2.9.0:
https://user-images.githubusercontent.com/129146107/228141337-a51847db-e1a6-442e-9525-fb2a80ade30b.png

Return code screenshot for version 2.6.0: 
https://user-images.githubusercontent.com/129146107/228141219-d54a9261-6756-4c20-bc9a-07287931779c.png

**Comment by nehanene15** [comment]
Where in the code are you printing the return code for v2.9.0? Looks like both versions are throwing the same 404 table not found error

**Comment by SwatiT17** [comment]
Hi Neha,

Here is the code chunk where we are printing the returncode:
"""
result=subprocess.Popen(["data-validation", "run-config", "-c", file_path], stdout=subprocess.PIPE,stderr=subprocess.STDOUT)
                output, error = result.communicate()
                result.wait()
                print("DVT execution done",output.decode('utf-8') ,flush=True)
                print("returncode for DVT execution: ", result.returncode,flush=True)
"""

Code chunk:
https://user-images.githubusercontent.com/129146107/229042647-7864fa80-14d6-41fc-b79b-8fc6dc8fa6d8.png

Return code screenshot for version 2.9.0:
https://user-images.githubusercontent.com/129146107/228141337-a51847db-e1a6-442e-9525-fb2a80ade30b.png

**Comment by nehanene15** [comment]
We don't populate the return codes in DVT code, instead this is a result of the subprocess package and how it handles the calls. Please re-open if there is an issue with error handling with DVT. Thanks!
