### ISSUE TITLE
Requesting DVT Validation output in dictionary format instead of tabular

### ISSUE THREAD

**Issue by madhu-jain** [GoogleCloudPlatform/professional-services-data-validator#786]
Description : 

On running DVT Validations, stdout printed on console is in tabular format. In few cases where validation output needs to be analysed to perform few operations, it becomes difficult to parse output values.
e.g 
While running Validation task in DAG, if validation status is "fail", we need to fail the task to avoid next layer data load. For such operation, we need to check validation status from stdout.
Similarly if empty file is received from source and no data loaded in target, validation shows 0 on both source and target values and validation is success. In such cases we need to check multiple columns of stdout.

Parsing the tabular format output becomes difficult. Is it possible to get output in dictionary format on console.

**Comment by mokhahmed** [comment]
DVT uses bigquery or text result handler to return the result of the validation process. 

the default behavior is the text result handler which support the output in the following output formats (table, json , text  and csv)  you can specify the output format at the validation command 

for example:

data-validation validate column   -sc MY_BQ_CONN   -tc MY_BQ_CONN   -tbls bigquery-public-data.new_york_citibike.citibike_trips --format json

![image](https://user-images.githubusercontent.com/100784684/229652508-629dfaa9-d9ae-4acb-b09a-29745bc3c86c.png)

Also,  Using the bigquery handler you can write the validation output and using another step to query the output table and validate the results 

data-validation validate column \ 
  -sc my_bq_conn \
  -tc my_bq_conn \
  -tbls bigquery-public-data.new_york_citibike.citibike_trips \
  --count tripduration,start_station_name \
  -bqrh $YOUR_PROJECT_ID.pso_data_validator.results
