### ISSUE TITLE
test: Blob validation in Oracle DB

### ISSUE THREAD

**Issue by denizNakib** [GoogleCloudPlatform/professional-services-data-validator#787]
I want to validate a table with a BLOB column in Oracle, however when I run any kind of validation (schema, column count etc.), I get the following error message: "Error could not find signature for dtype: <OracleDialect_cx_oracle, BLOB> ....".
I saw that there is no signature for BLOB type in ibis_oracle client, is there a work around?

**Comment by nehanene15** [comment]
This will be resolved with the Ibis upgrade to version 5.0

**Comment by nehanene15** [comment]
Closed with PR #894
