### ISSUE TITLE
Could some one post validation commands working for Mysql and Teradata sources

### ISSUE THREAD

**Issue by hbcvsuser** [GoogleCloudPlatform/professional-services-data-validator#788]
Currently able to add connection using data-validation connections add --connection-name

and could anyone post the other commands how to compare my sources Mysql,teradata data to Bigquery data

Thanks

**Comment by piyushsarraf** [comment]
For Normal Validation: 

- Column
`data-validation validate column -sc TeradataConnectionName  -tc BQConnectionName -tbls TD_Database_Name.TableName=BQ_Database_Name.TableName`
- Row
`data-validation validate row -sc TeradataConnectionName  -tc BQConnectionName -tbls TD_Database_Name.TableName=BQ_Database_Name.TableName -pk primary_key_of_anyone --hash '*'`

For Custom Query Validation: 
- Column
`data-validation validate custom-query column -sc TeradataConnectionName  -tc BQConnectionName -tbls  --source-query-file td_query.sql --target-query-file bq_query.sql`

- Row
`data-validation validate custom-query row -sc TeradataConnectionName  -tc BQConnectionName -tbls  --source-query-file td_query.sql --target-query-file bq_query.sql -pk primary_key_of_anyone --hash '*'`

Here td_query.sql and bq_query will be the custom query for teradata or MSSQL and BigQuery respectively . 

Can also refer to [examples.md.](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/docs/examples.md)
