### ISSUE TITLE
Row Count compare for Source and Target table

### ISSUE THREAD

**Issue by hbcvsuser** [GoogleCloudPlatform/professional-services-data-validator#789]
Hi,

I have a question that can we compare the row count of source and target table in DVT?
I am not able to see that in the schema of the bq result handler so wondering if we can do that.

Thanks and Regards,

**Comment by hbcvsuser** [comment]
Any reply>

**Comment by nehanene15** [comment]
Yes, the default validation is a row count (COUNT *). [Here](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/docs/examples.md#simple-count-on-a-table) is an example for a row count with a BQ table against itself.
