### ISSUE TITLE
Segmentation Fault on M1/M2 Python 3.10

### ISSUE THREAD

**Issue by claudenm** [GoogleCloudPlatform/professional-services-data-validator#793]
Running data-validation in a clean virtualenv results in a segmentation fault.  Tested on both a MacBook M1 Pro and M2 Pro.

On the M1:
```
python 3.10.3
google-pso-data-validator version 3.0.0
```

```
data-validation              
usage: The Data Validation CLI tool is intended to help to build and execute
data validation runs with ease.

[omitted the rest of help message]
[1]    46481 segmentation fault  data-validation
```

On the M2 I used python 3.10.10 and had the same issue.

**Comment by kanhaPrayas** [comment]
@claudenm Are you able to get any results while running DVT or you are not getting anything except segmentation fault.

**Comment by prayas-purusottam-bakkt** [comment]
We can close it... as no more updates

**Comment by kanhaPrayas** [comment]
We can close it as there is no more update
