### ISSUE TITLE
Row validation comp fields: Validation failing for more than 140 columns 

### ISSUE THREAD

**Issue by bharattiwari9900** [GoogleCloudPlatform/professional-services-data-validator#795]
Hi Team, 

On running the below command for doing row validation for Bigquery external vs bigquery native table, Row validation was running fine for 140 columns but when we include more than 140 column it fails.

data-validation validate custom-query row \
-sc BQ_CONN \
-tc BQ_CONN \
--source-query-file stores_src.sql \
--target-query-file stores_tgt.sql \
-l category=source_to_landing_validation,source=stores_ext,target=stores,load_dt=2022-03-23 \
-comp-fields acquisition_code,acquisition_dte,ad_frequency,ad_market,address_line_1,address_line_2,address_line_3,fe_area_code,fe_phone_nbr,cash_register_count,city,close_dte,combined_dte,coop_mkt,corporation_nbr,country,county,dea_expiration_dte,dea_nbr,distribution_center,distribution_center_code,dmad,dmad_desc,drive_thru_pharmacy_ind,expansion_dte,fe_hrs_fri_from,fe_hrs_fri_to,fe_hrs_mon_from,fe_hrs_mon_to,fe_hrs_sat_from,fe_hrs_sat_to,fe_hrs_sun_from,fe_hrs_sun_to,fe_hrs_thu_from,fe_hrs_thu_to,fe_hrs_tue_from,fe_hrs_tue_to,fe_hrs_wed_from,fe_hrs_wed_to,location_desc,location_status,location_type,lottery_ind,admin_nbr,admin_desc,region,region_manager,district,district_manager,min_compound_price,min_prescription_price,one_hr_photo_ind,owning_subsidiary,pour_over_ind,rx_primary_price_zone,fe_primary_price_zone,rx_second_price_zone,fe_second_price_zone,rx_area_code,rx_phone_nbr,rx_square_feet,rx_transfer,primary_wholesale,professional_disc,division_desc,division_nbr,relocation_dte,remodel_dte,reopen_dte,reset_dte,rx_hrs_fri_from,rx_hrs_fri_to,rx_hrs_mon_from,rx_hrs_mon_to,rx_hrs_sat_from,rx_hrs_sat_to,rx_hrs_sun_from,rx_hrs_sun_to,rx_hrs_thu_from,rx_hrs_thu_to,rx_hrs_tue_from,rx_hrs_tue_to,rx_hrs_wed_from,rx_hrs_wed_to,secondary_wholesale,senior_discount,senior_dollar_disc,state,stockrooom_sq_feet,fe_sale_sq_feet,time_zone,vru,zip,total_store_sqft,effective_start_dte,effective_end_dte,creation_dte,last_update_dte,last_update_stp_id,last_update_by,active_ind,batch_id,current_location_nbr,open_dte,comp_effective_dte,non_comp_dte,liquidation_dte,market_region_nbr,market_region_desc,division_long_desc,division_long_desc_2,region_long_desc,region_long_desc_2,district_long_desc,district_long_desc_2,location_long_desc,pdm_user_id,pdm_name,pdm_nbr,pdm_long_desc,dmad_long_desc,be_ind,ra_store_nbr,scheduled_pos_conv_dte,deal_close_dte,latitude,longitude,paint_powder_type,nabp,state_medicaid,npi,medicare,division_geo_code,region_geo_code,district_geo_code,divested_dte,divested_company_name,divested_store_status,rebranded_dte,rebranded_company_name,retail_svp_nbr,retail_svp_name,retail_svp_user_id,retail_region_nbr \
-pk store \
--bq-result-handler rite-aid-pocs.ra_data_validation.results \
-c stores_row_validation.yaml

**Comment by rishabkhawad** [comment]
Hi, @bharattiwari9900 can you please also tell the failure message you received.
Thanks.

**Comment by rishabkhawad** [comment]
For the same dataset, the functionality seems to be working fine. The issue seems to be local and is currently being tested by @bharattiwari9900 for resolution.
