### ISSUE TITLE
Incorrect query generation for cast integer to string for DB2 row validation. 

### ISSUE THREAD

**Issue by piyushsarraf** [GoogleCloudPlatform/professional-services-data-validator#799]
There is incorrect query generation while doing row validation for DB. When casting to string we are casting to CLOB and query is: 
```
SELECT t6.guestname AS guestname, t6.content AS content, t6.entryid AS entryid, t6.guestname AS cast__guestname, t6.content AS cast__content, CAST(t6.entryid AS CLOB) AS cast__entryid 
FROM db2inst1.entries AS t6
```

But we are facing an error that: 
`A value with data type "SYSIBM.INTEGER" cannot be CAST to type "SYSIBM.CLOB".`

I think instead of casting to CLOB casting to VARCHAR(n) will be a solution. 

Some samples from DB2 terminal: 
<img width="830" alt="image" src="https://user-images.githubusercontent.com/47020544/230880404-eae797d3-732f-43d3-86c2-ebe50f3fb0ae.png">
<img width="1258" alt="image" src="https://user-images.githubusercontent.com/47020544/230880439-3fb84e06-5b86-421e-81e6-d6b41671376c.png">

**Comment by ngdav** [comment]
What's the exact DVT command/config you're using when getting this error?
