### ISSUE TITLE
--filters feature not working on MySQL.

### ISSUE THREAD

**Issue by claudenm** [GoogleCloudPlatform/professional-services-data-validator#810]
Similar to #760, when running a validation with a MySQL source we get:

```No translation rule for <class 'third_party.ibis.ibis_addon.operations.RawSQL'>```

The validation was:

```
data-validation -v validate row  --source-conn mysql -tc bq --tables-list mysql.redacted=bq.redacted --comparison-fields=field1,field2,field3 --primary-keys=id --filters='id>1'
```

A working validation, omitting the filter is:
```
data-validation -v validate row  --source-conn mysql -tc bq --tables-list mysql.redacted=bq.redacted --comparison-fields=field1,field2,field3 --primary-keys=id -rr
```

We'll need to validate billion row tables, so would appreciate this being patched.

**Comment by kanhaPrayas** [comment]
https://github.com/GoogleCloudPlatform/professional-services-data-validator/pull/812
