### ISSUE TITLE
Cannot install the package on MacOs

### ISSUE THREAD

**Issue by Pathi-rao** [GoogleCloudPlatform/professional-services-data-validator#818]
Hi,
I have started my installation from [this](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/docs/installation.md) step. I have created a venv which contains python 3.11.2. For gcc, i did `brew install gcc` and once it's done, I did `pip install google-pso-data-validator` which gave an error

`
Error: pg_config executable not found.

      pg_config is required to build psycopg2 from source.  Please add the directory
      containing pg_config to the $PATH or specify the full executable path with the
      option:

          python setup.py build_ext --pg-config /path/to/pg_config build ...

      or with the pg_config option in 'setup.cfg'.

      If you prefer to avoid building psycopg2 from source, please install the PyPI
      'psycopg2-binary' package instead.

      For further information please check the 'doc/src/install.rst' file (also at
      <https://www.psycopg.org/docs/install.html>).`

I figured there might be something wrong with psycopg2, so i did `pip install psycopg2` and this also gave me the same error as above. But I was not able to find any fix. I would appreciate your help in solving this

Thanks!

**Comment by helensilva14** [comment]
Hi @Pathi-rao! Thanks for bringing this issue to us. Unfortunately we currently do not support Python 3.11, it is in our backlog (#814). Could you please try to install it with Python 3.10 and check if you still have problems?

**Comment by Pathi-rao** [comment]
Hi @helensilva14 
The installation is a success with  python 3.10.10

Thanks again

**Comment by helensilva14** [comment]
Great, no problem, glad to know! We hope DVT helps you, if you've other problems please open a new issue.
