### ISSUE TITLE
DB2 row validation using custom query causing issue.

### ISSUE THREAD

**Issue by arjitshu** [GoogleCloudPlatform/professional-services-data-validator#821]
Running below yaml for DB2 row validation using Custom query is throwing error.

**Error** - 

AM-ERROR: Error list index out of range occured while running config file itiap_row_validation_latest.yaml. Skipping it for now.

**YAML** -

result_handler:
  project_id: rite-aid-pocs
  table_id: ra_data_validation.results
  type: BigQuery
source: DB2_CONN1
target: BQ_CONN
validations:
- calculated_fields: []
  comparison_fields:
  - cast: null
    field_alias: corporation
    source_column: itiap_corp
    target_column: corporation
  - cast: null
    field_alias: item_nbr
    source_column: itiap_itm_nbr
    target_column: item_nbr
  - cast: null
    field_alias: alternate_key_type
    source_column: itiap_alt_key_type
    target_column: alternate_key_type
  - cast: null
    field_alias: delete_ind
    source_column: itiap_dlt_ind
    target_column: delete_ind
  - cast: null
    field_alias: last_maintenance_dte
    source_column: itiap_lst_mnt_dte
    target_column: last_maintenance_dte
  - cast: null
    field_alias: last_operator_id
    source_column: itiap_lst_opr_id
    target_column: last_operator_id
  - cast: null
    field_alias: last_transaction_code
    source_column: itiap_lst_trn_cde
    target_column: last_transaction_code
  - cast: null
    field_alias: item_uom_qty
    source_column: itiap_itm_uom_qty
    target_column: item_uom_qty
  - cast: null
    field_alias: upc_type
    source_column: itiap_upc_type
    target_column: upc_type
  - cast: null
    field_alias: alternate_key_ndc
    source_column: itiap_alt_key_ndc
    target_column: alternate_key_ndc
  - cast: null
    field_alias: preferred_upc_inc
    source_column: itiap_prfd_upc_inc
    target_column: preferred_upc_inc
  - cast: null
    field_alias: preferred_upc_ind
    source_column: itiap_prfd_upc_ind
    target_column: preferred_upc_ind
  - cast: null
    field_alias: group_code_1
    source_column: itiap_grp_cde_1
    target_column: group_code_1
  - cast: null
    field_alias: group_code_2
    source_column: itiap_grp_cde_2
    target_column: group_code_2
  - cast: null
    field_alias: group_original_ind
    source_column: itiap_grp_orig_ind
    target_column: group_original_ind
  - cast: null
    field_alias: tier_id
    source_column: itiap_tier_id
    target_column: tier_id
  filter_status: null
  filters: []
  format: table
  labels: []
  primary_keys:
  - cast: null
    field_alias: alternate_key_value
    source_column: itiap_alt_key_valu
    target_column: alternate_key_value
  random_row_batch_size: null
  schema_name: null
  source_query: **SELECT itiap_corp,itiap_itm_nbr,itiap_alt_key_type,itiap_alt_key_valu,itiap_dlt_ind,itiap_lst_mnt_dte,itiap_lst_opr_id,itiap_lst_trn_cde,itiap_itm_uom_qty,itiap_upc_type,itiap_alt_key_ndc,itiap_prfd_upc_inc,itiap_prfd_upc_ind,itiap_grp_cde_1,itiap_grp_cde_2,itiap_grp_orig_ind,itiap_tier_id FROM DB2INST1.ITIAP_ITMACCS_TBL**
  table_name: null
  target_query: **SELECT corporation,item_nbr,alternate_key_type,alternate_key_value,delete_ind,last_maintenance_dte,last_operator_id,last_transaction_code,item_uom_qty,upc_type,alternate_key_ndc,preferred_upc_inc,preferred_upc_ind,group_code_1,group_code_2,group_original_ind,tier_id FROM rite-aid-pocs.ra_landing.itiap_item_access_path WHERE ra_load_dte = '2023-04-13'**
  target_schema_name: null
  target_table_name: null
  threshold: 0.0
  type: Custom-query
  use_random_rows: null

**Comment by nehanene15** [comment]
This seems to be specific to selecting a comparison field on the last column in the SELECT of a custom query. One workaround here is to add an extra column in the custom query (that is not being used in the comparison fields)

i.e `SELECT itiap_corp,itiap_itm_nbr,itiap_alt_key_type,itiap_alt_key_valu,itiap_dlt_ind,itiap_lst_mnt_dte,itiap_lst_opr_id,itiap_lst_trn_cde,itiap_itm_uom_qty,itiap_upc_type,itiap_alt_key_ndc,itiap_prfd_upc_inc,itiap_prfd_upc_ind,itiap_grp_cde_1,itiap_grp_cde_2,itiap_grp_orig_ind,itiap_tier_id, extra_column FROM DB2INST1.ITIAP_ITMACCS_TBL`

This seems to be an issue with the Ibis schema inference on top of a SQL query result in the older Ibis version - this should be fixed with the Ibis upgrade in a few weeks 

cc @Raniksingh
