### ISSUE TITLE
Try to run custom query in pycharm local it is not give any output

### ISSUE THREAD

**Issue by shivanshusoni185** [GoogleCloudPlatform/professional-services-data-validator#822]
Try to run custom query in pycharm local it is not give any output

data-validation validate custom-query
--custom-query-type column
--source-query-file source.sql
--target-query-file target.sql
-sc test
-tc BQ_CONN
--max NumberOfConnections

**Comment by nehanene15** [comment]
Are you using the latest version? If so, the command is `data-validate custom-query column ...` 
Is `data-validation -h` working? If not the tool may not be installed properly

**Comment by nehanene15** [comment]
Just following up - is this still an issue?
