### ISSUE TITLE
Is it possible to run validations on tables from different BigQuery projects?

### ISSUE THREAD

**Issue by Pathi-rao** [GoogleCloudPlatform/professional-services-data-validator#830]
Hi,

I am trying to validate the data in tables (of same schema) from two different projects. I've followed [this](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/docs/connections.md#create-a-sample-bigquery-connection) and created *TWO* connections (one for source project and one for destination project). But when I run the validation command and write the result to BigQuery table, the columns `source_table_name` and `target_table_name` contains the same value. 

Following is a replication of my example which validates two tables using a shell script,

`dummy_table_names=("my_table1"
"my_table2"
)

--source project and dataset name
src_prjt="my_src_prjt.my_src_dtst"
dest_prjt="my_dst_prjt.my_dst_dtst"

--Loop through each pair of tables and compare them
for table_name in "${dummy_table_names[@]}";
do
    source_table=$src_prjt.$table_name
    desti_table=$dest_prjt.$table_name
    echo $source_table
    echo $desti_table
    data-validation validate column \
    -sc src_project_conn \
    -tc dest_project_conn \
    -tbls $desti_table\
    --count '*' \
    -bqrh my_dst_prjt.pso_data_validator.results
done`

When I run this script in terminal as `bash my_validation_script.sh`, the results are successfully written to BigQuery but in the results table, the columns `source_table_name` and `target_table_name` contain same value (specifically it contains the value `desti_table`. 
My expected output is that the column `source_table_name` contains the value `source_table` and `target_table_name` contains the value `desti_table` or did I misunderstood the documentation?

Thanks in advance

**Comment by piyushsarraf** [comment]
Hi, 
I think, there is a typo in -tbls flag, it should be `-tbls $source_table=$desti_table`. 
If we give a single arg with -tbls flag, it compares the values with itself.

**Comment by Pathi-rao** [comment]
Hey @piyushsarraf ,

Thanks a lot, I just tested it and it works like a charm. Could you please point me to the documentation as I either seemed to miss this part and failed to understand it or it just doesn't exist. If it's the later case, maybe I could contribute by creating some examples.

**Comment by piyushsarraf** [comment]
Can you check the [README](https://github.com/GoogleCloudPlatform/professional-services-data-validator#:~:text=writing%20any%20queries.-,Row%20Validations,-(Note%3A%20Row%20hash))

I this we have added the reference for -tbls 
```
--tables-list or -tbls SOURCE_SCHEMA.SOURCE_TABLE=TARGET_SCHEMA.TARGET_TABLE
                        Comma separated list of tables in the form schema.table=target_schema.target_table
```
                        
I know schema.table=target_schema.target_table is kind of wague, it should be source_schema.source_table=target_schema.target_table. 

This will be fixed in next PR.

**Comment by Pathi-rao** [comment]
Thanks. 
Would it also be possible to add it in [Examples](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/docs/examples.md). I think it would greatly benefit new people who are trying it for the first time. please let me know if there is anything related to this that I can contribute.

**Comment by piyushsarraf** [comment]
Sure
