### ISSUE TITLE
SQL Server connection

### ISSUE THREAD

**Issue by bnb012008** [GoogleCloudPlatform/professional-services-data-validator#835]
On my W10 workstation I cannot connect to MSSQL with the DVT connection.  I have the MS 17 ODBC driver and can connect with a System DSN I setup but trying to use:

data-validation connections add --connection-name xxxxx MSSQL --host=xxx.xxx.xxx.xxx --port=xxxx --user=xxxxxxx --password xxxxxxxx --database xxxxxxxx

I fill-in the xxxx's with the same values and can connect when using the system DSN.  Is the only way to connect is using GCP secret stuff?  I have tried several different combinations.  Am I missing something in the documentation?

**Comment by bnb012008** [comment]
I thought this worked earlier but lost my notes.  Can anyone help?

**Comment by nehanene15** [comment]
The docs [here](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/docs/connections.md#mssql-server) will outline the flags needed when making a connection. You don't need Secret Manager integration to connect.

You will need to install pyodbc as the driver as well. Please re-open if this is still an issue. Thanks!
