### ISSUE TITLE
Match Source and target table name 

### ISSUE THREAD

**Issue by shivanshusoni185** [GoogleCloudPlatform/professional-services-data-validator#836]
I have a two dataset one is in sql server another one is an bq . I want to match both the dataset have same table name or not but when i trying to do this thing . In some case it gives correct match and in some case it give  "nan " source and target table  

 data-validation validate custom-query row -sc MY_MS_CONN -tc MY_BQ_CONN --source-query-file source.sql --target-query-file target.sql -pk name --concat '*'

![Screenshot (2)](https://user-images.githubusercontent.com/48975340/237004365-1e3e22f2-a230-4c7c-b177-9929d4eb7c49.png)

**Comment by nehanene15** [comment]
Are you sure the columns are present on both source and target tables and that the PK is unique per row? Usually you will see 'nan' when a row doesn't exist on either the source or target systems.

**Comment by shivanshusoni185** [comment]
Yes I am sure  source and target have same name tables are present 
source sql:- select 'dbo_'+name as name , 1 as id from xyz.sys.tables
target sql:- select table_name as name, 1 as id  from project_id.dataset.INFORMATION_SCHEMA.TABLES;

**Comment by nehanene15** [comment]
Based on the source/target SQL provided, you are specifying "1 as id" fore every row. This will result in a non-unique PK for each row.
