### ISSUE TITLE
schema validation: BigQuery BIGNUMERIC

### ISSUE THREAD

**Issue by nj1973** [GoogleCloudPlatform/professional-services-data-validator#839]
BigQuery BIGNUMERIC columns are being read by schema validation as `decimal(38, 9)`. Possibly this is because BIGNUMERIC precision and scale exceeds that supported by Ibis but I thought it should be logged anyway.

Example BigQuery column:
```
,   col_dec_38      BIGNUMERIC(38)
```

Shows in DVT schema validation as `decimal(38, 9)`.

@nehanene15 , do you think this would be resolved by the Ibis upgrade?

If we change the input type then the following integrations tests will need to be updated (search for "issue-839" in the files):

- test_hive.py
- test_oracle.py
- test_sql_server.py
- test_teradata.py

**Comment by nehanene15** [comment]
Seems like the issue will persist in the Ibis upgrade due to this: https://github.com/ibis-project/ibis/blob/master/ibis/backends/bigquery/client.py#L29 

We'll need to add BIGNUMERIC support to resolve this.

**Comment by nj1973** [comment]
It might be that Ibis has moved on again, BIGNUMERIC is mentioned here:

https://github.com/ibis-project/ibis/blob/845f7abf75fe2bd42901f7cf230a0527f99f0bf1/ibis/backends/bigquery/datatypes.py#L23

**Comment by SwatiT17** [comment]
BigQuery NUMERIC columns are also being read by schema validation as decimal(38, 9)

**Comment by nj1973** [comment]
> BigQuery NUMERIC columns are also being read by schema validation as decimal(38, 9)

That is correct, BigQuery NUMERIC is fixed at precision 38, scale 9.

**Comment by nehanene15** [comment]
This will be resolved with the Ibis upgrade - BIGNUMERIC will map to `decimal(76, 38)`
