### ISSUE TITLE
For-loop in ConfigManager.build_config_calculated_fields() does nothing

### ISSUE THREAD

**Issue by steve-ahlswede** [GoogleCloudPlatform/professional-services-data-validator#862]
Not really a bug, but I noticed that the following function has a for-loop which, aside from printing out some logs, does nothing that has any effect. Would be curious if this is just something that was accidentally left this way, or if there is some explanation for it.

https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/54403e3014ff5dbcc50ca540eb786dfc33759f0b/data_validation/config_manager.py#L703-L748

**Comment by nehanene15** [comment]
Thanks for pointing this out - this is intended for validations over all columns i.e `-sum '*'` so we can log when columns are skipped (for non-numeric types) or missing from the target table. It's useful to log so the user can know which columns aren't included in the validation.
