### ISSUE TITLE
DVT should support large unsorted files as source and target without running into OOM

### ISSUE THREAD

**Issue by hm98765** [GoogleCloudPlatform/professional-services-data-validator#877]
FR to have DVT take  unsorted files in currently supported formats ( JSON & CSV) and sort them in DVT before comparing them.
The files will have the keys on which to sort.

**Comment by hm98765** [comment]
more context: this is for larges files that will not fit into memory

**Comment by sundar-mudupalli-work** [comment]
Specifically, what size of file are we talking about?

For context, BigQuery CSV gzip files can be max 4 GB and in some cases cannot be larger than 1 GB (for some character sets). Many systems don't create files larger than a few GB as they are difficult to use and you lose lot of data when there is corruption.

Python will allow us to use as much memory as available. GCP has some machine shapes that allow for over 1TB of memory. If DVT on files fails with a OOM error, a straightforward workaround is to run DVT on a larger VM and see if the validation can be succeed. It most likely will. 

If there is a specific use case with file sizes that is failing with OOM which does not go away with a larger VM, we can investigate.

**Comment by hm98765** [comment]
LGTM . This ticket can be closed . Thanks

**Comment by helensilva14** [comment]
Thank you @hm-distro!
