### ISSUE TITLE
Support column 'except' list for aggregations and hash

### ISSUE THREAD

**Issue by nehanene15** [GoogleCloudPlatform/professional-services-data-validator#880]
Currently DVT only supports specifying columns to _include_ for aggregations or hashes i.e
`data-validation validate column ... -sum 'col_a,col_b,col_c,col_d'`

At times it is easier to provide an exclusion list instead to sum all columns _except_ col_e for example. 
DVT should support a flag that signals the column list is an exclusion list rather than an inclusion list (default).

For example,
`data-validation validate column ... -sum col_e --exclude-columns`

`--exclude-columns or -ec` can be a [store_false argument](https://docs.python.org/3/library/argparse.html#action). If the flag is present, we take all columns except the ones specified.

**Comment by sudheersingampalli** [comment]
Hi @nehanene15 , I would like to work on this feature..

**Comment by nehanene15** [comment]
@sudheersingampalli Is this still something you would like to work on? If not, I will reassign

**Comment by sundar-mudupalli-work** [comment]
Hi,

I reviewed @mloeberc's code changes for this and this feature request requires more clarification

Two issues I see:
1. what if I specify `--sum '*' --exclude-columns` - this should raise ValueError
2. what if I specify `--sum num_bikes_available --exclude-columns --avg num_bikes_available,num_docks_disabled` - does the `--exclude-columns` apply to the `sum`, `avg` or both ? OR should we disallow --exclude-columns when there is more than one aggregation ?

On the second one, I don't have a strong opinion.

Thanks.

**Comment by mloeberc** [comment]
Sundar, I'll wait for someone to answer to the first issue, and test what is the actual behavior.
As for the second issue, we discussed this in one meeting and the conclusion was when the --exclude-columns is present it will apply to all the aggregations mentioned in the command, since providing a list to include an another one to exclude would add complexity to the instructions given in a command, so it would be an apply to all flag.

**Comment by sundar-mudupalli-work** [comment]
Hi,

Ok, I thought about what I said above  - if I specify `--sum '*' --exclude-columns` - this should raise ValueError.

I am reversing myself on the statement that `--sum '*' --exclude-columns` should not raise ValueError - instead `--exclude-columns` must be ignored for this aggregation. Here is why I think so:
1.  The `validate column` command always includes a `--count '*'` as an aggregation. Therefore, if we raised ValueError, every use of `--exclude-columns` would raise a ValueError.
2. When someone uses `--sum '*' --exclude-columns`, we can assume that the `--exclude-columns` refers to all the other aggregations that may be present. Users are likely not tricking data-validation to do something unusual.
3. If a table has only the following columns `a, b, c, d` and a user says `--sum a,b,c,d --exclude-columns` it is reasonable that data-validation would raise an error - not sure if it is possible to check this in the code.
4. All these situations should be documented.

Sorry about the change in approach, I understand the feature a lot better now. Of course, I am happy to be shown a better approach to address this.

Thanks.

Sundar Mudupalli

**Comment by nehanene15** [comment]
I agree that when the `--exclude-columns` flag is present, it should apply to _all_ the aggregations mentioned. Therefore, if a `"*"` aggregation is present (like `--sum '*'`) we should raise an error stating "Exclude columns flag cannot be present with '*' column aggregation"

**Comment by mloeberc** [comment]
@nehanene15, @sundar-mudupalli-work I already took into account your comments and made the changes in the code. PR is ready for reviewing.

**Comment by nehanene15** [comment]
Re-opening to extend `--exclude-columns` flag for row hash + custom query row validation as well.
