### ISSUE TITLE
Schema mapping : schema mapping are different

### ISSUE THREAD

**Issue by warunk9** [GoogleCloudPlatform/professional-services-data-validator#884]
As I observe, 
- schema data types for BQ table created by Data Transfer Service from teradata to bigquery migration are different and more accurate,  
- but data validator using Bigquery Translation api to translate schema from teradata table schema .
-  both schema are different and schema validation is failing due to this.
- Also some teradata schema datatype and bq datatype mapping is wrong, like int16(td) not match with int64(bq)
-  e.g :
- from dts decimal(8,0) converted to Numeric(8) , but from BQ translation api it converted to DECIMAL(38,9) 
- in teradata we have int16 ,int32 but in BQ we have int64 
![Screenshot 2023-06-13 at 9 58 26 PM](https://github.com/GoogleCloudPlatform/professional-services-data-validator/assets/123057617/12f944c1-f583-4f49-8266-71dc5ee6d584)
- this is impacting the schema validation

**Comment by helensilva14** [comment]
Issue with BigQuery's DECIMAL similar to #883

**Comment by nj1973** [comment]
I'm not sure if this is helpful but, earlier this week we added support for an allow list config file via option `--allow-list-file`. We also included two sample files:
```
$ ls -l samples/allow_list/
total 8
-rw-r----- 1 526 Jun 20 09:39 oracle_to_bigquery.yaml
-rw-r----- 1 372 Jun 20 09:39 oracle_to_postgres.yaml
```

The customer could create a Teradata to BigQuery file containing safe mappings, for example:
```
# Small Teradata integrals are valid in INT64
"int8": "int64"
"int16": "int64"
"int32": "int64"
# Integral NUMBERS with precision < 29 are valid in NUMERIC
"decimal(1-29,0)": "decimal(38,9)"
```

And then use that config repeatedly using:

```
--allow-list-file=/path/teradata_to_bigquery.yaml
```

**Comment by nehanene15** [comment]
@warunk9 Is this still an issue after the allow list file feature? If not, I will go ahead and close this issue.
