### ISSUE TITLE
Can this Utility be used to compare, on-prem Oracle Database to Azure Sql Database ? 

### ISSUE THREAD

**Issue by Malathi-Bellam-Accenture** [GoogleCloudPlatform/professional-services-data-validator#892]
Hi,
  Not reporting an issue. Trying find a solution for data & schema validation for Azure migration project while Oracle DB being the source at on-prem.  In terms of validation rules, DVT meets the requirement. 

Pls. clarify the below aspects,  
1. is it a viable option for Comparison between on-prem Source Oracle data & Target Azure SQL DB ?
2. Can it be Installed on Azure VM ( Windows) ? 
3. Validation output redirected to CSV format in local directory in the VM ? 

 This is the only open source utility that covers most of our validation requirement. 
Fingers crossed!

Regards
Malathi

**Comment by nehanene15** [comment]
Hi,

1. Yes, we use cx_Oralce and sqlalchemy to connect to Oracle and MySQL respectively
2. We recommend installing on Linux; we can't guarantee successful installation on Windows
3. Yes it can - you can use the `--format csv` flag to pipe the output to a CSV file 

Hope this helps!

**Comment by Malathi-Bellam-Accenture** [comment]
That saved my day!
Thank you Neha!
