### ISSUE TITLE
BQ-BQ Comparison : Issue in running DVT Validation using custom query with random rows and composite pk

### ISSUE THREAD

**Issue by madhu-jain** [GoogleCloudPlatform/professional-services-data-validator#893]
I was trying to run dvt validation where source is bigquery external table and target is bigquery native table. I have used custom query with random rows as 500.
Primary key used in query was composite primary key. Below is the yaml used : 

result_handler:
  project_id: <project_id>
  table_id: <dataset>.results
  type: BigQuery
source: BQ_CONN
target: BQ_CONN
validations:
- calculated_fields: []
  comparison_fields:
  - cast: null
    field_alias: attribute_value
    source_column: attribute_value
    target_column: attribute_value
  - cast: null
    field_alias: attribute_subvalue
    source_column: attribute_subvalue
    target_column: attribute_subvalue
  - cast: null
    field_alias: preferred_upc_ind
    source_column: preferred_upc_ind
    target_column: preferred_upc_ind
  - cast: null
    field_alias: create_dte
    source_column: create_dte
    target_column: create_dte
  - cast: null
    field_alias: create_operator_id
    source_column: create_operator_id
    target_column: create_operator_id
  - cast: null
    field_alias: last_maintenance_dte
    source_column: last_maintenance_dte
    target_column: last_maintenance_dte
  - cast: null
    field_alias: last_operator_id
    source_column: last_operator_id
    target_column: last_operator_id
  custom_query_type: row
  filter_status: null
  filters: []
  format: table
  labels:
  - !!python/tuple
    - validation_type
    - row
  - !!python/tuple
    - category
    - source_to_landing_validation
  - !!python/tuple
    - source
    - product_attributes_fw_ext
  - !!python/tuple
    - target
    - product_attributes
  - !!python/tuple
    - load_dt
    - '2023-06-23'
  primary_keys:
  - cast: null
    field_alias: item_nbr
    source_column: item_nbr
    target_column: item_nbr
  - cast: null
    field_alias: upc_nbr
    source_column: upc_nbr
    target_column: upc_nbr
  - cast: null
    field_alias: attribute_name
    source_column: attribute_name
    target_column: attribute_name
  random_row_batch_size: '500'
  schema_name: null
  source_query: select NULLIF(TRIM(SUBSTR(column1,1,7)),'') as item_nbr,NULLIF(TRIM(SUBSTR(column1,8,40)),'')
    as attribute_name,NULLIF(TRIM(SUBSTR(column1,48,60)),'') as attribute_value,NULLIF(TRIM(SUBSTR(column1,108,60)),'')
    as attribute_subvalue,NULLIF(TRIM(SUBSTR(column1,168,12)),'') as upc_nbr,NULLIF(TRIM(SUBSTR(column1,180,1)),'')
    as preferred_upc_ind,NULLIF(TRIM(SUBSTR(column1,181,10)),'') as create_dte,NULLIF(TRIM(SUBSTR(column1,191,8)),'')
    as create_operator_id,NULLIF(TRIM(SUBSTR(column1,199,10)),'') as last_maintenance_dte,NULLIF(TRIM(SUBSTR(column1,209,8)),'')
    as last_operator_id from `<project_id>.<dataset>.products_attributes_fw_ext`
    where ra_load_dte='2023-06-23'
  table_name: null
  target_query: select item_nbr, attribute_name, NULLIF(TRIM(attribute_value),'')
    as attribute_value, attribute_subvalue, upc_nbr,preferred_upc_ind,create_dte,create_operator_id,last_maintenance_dte,last_operator_id
    FROM `<project_id>.<dataset>.products_attributes`
    where ra_load_dte = '2023-06-23'
  target_schema_name: null
  target_table_name: null
  threshold: 0.0
  type: Custom-query
  use_random_rows: true

While analysing the results, below query is executed to verify success count of each column. Count present was 5783 for every column.

select
run_id,
validation_name,
source_column_name,
target_column_name,
start_time,
end_time,
count(*) as count
from `<project_id>.<dataset>.results`
where
run_id = '0d549773-2a32-4101-a043-5b4be002b4a4'
and
validation_status = 'success'
group by
run_id,
validation_name,
source_column_name,
Target_column_name,
start_time,
end_time

<img width="643" alt="Screenshot 2023-06-30 at 3 12 13 PM" src="https://github.com/GoogleCloudPlatform/professional-services-data-validator/assets/124554976/e4e26c74-7e5e-4b35-bbc7-8bb8603a0f52">

**Comment by nehanene15** [comment]
Random row only applies to the first primary key 'item_nbr'. The query to generate random rows is 
`SELECT item_nbr FROM table WHERE ra_load_dte='2023-06-23' ORDER BY RAND() LIMIT 500`.

Then the final query for validation will take the above results and add it to the filter `WHERE item_nbr IN (1,2,3,...500) AND ra_load_dte='2023-06-23'`. Since this is a composite PK, there are probably 5783 rows for which the above filter applies.

**Comment by madhu-jain** [comment]
Hi Neha,

This seems the current capability of providing multiple comma separated primary keys in DVT command is not supported. Even though we provide multiple columns as primary key, it would pick only first column and treat it as pk.
As it's a very likely case for tables to have composite primary keys, is there any plan of including composite primary key support in DVT?

**Comment by nehanene15** [comment]
@madhu-jain We do support composite PKs when doing validation and comparison of source and target tables - we only do not support it for random row. 
We have an Issue #774 open for addressing this. As described there, a composite PK can become very complex due to the complexity it will add when specifying a batch size. 

For example, if you have 3 PKs with batch size 5, the filter would need to be WHERE id in (1,2) and first in (1,2) and last in (1).
