### ISSUE TITLE
Error maximum recursion depth exceeded in comparison occurred while running config file <table>_row_validation.yaml. Skipping it for now.

### ISSUE THREAD

**Issue by paraschavda2411** [GoogleCloudPlatform/professional-services-data-validator#897]
Row validation for more than 140 columns is failing with the error 

`Error maximum recursion depth exceeded in comparison occurred while running config file products_row_validation.yaml. Skipping it for now.`

**Details**  - 
**Source** : BigQuery External Table
**Target** : BigQuery Native Partitioned Table 
**Primary Key :** Concatenated primary key using custom query ( as multiple primary key was not working ) 
**Category** : Random records and Filtered records validations 

Please refer the below details more information 
<google-sheets-html-origin><style type="text/css"></style>

column count | record count | category | status | time taken | id | comments
-- | -- | -- | -- | -- | -- | --
140 | 1000 | Random | success | ~7 mins | 452e8c66-cff5-4948-ad1a-090bb4ed89cc |  
28 | 1000 | Random | success | ~1 mins | 2ec15483-18ce-40dc-ae86-0685599df82d |  
150 | 1000 | Random | failure | nA | nA | Error maximum recursion depth exceeded in comparison occurred while running config file products_row_validation.yaml. Skipping it for now
145 | 1000 | Random | failure | nA | nA | Error maximum recursion depth exceeded in comparison occurred while running config file products_row_validation.yaml. Skipping it for now
141 | 1000 | Random | failure | nA | nA | Error maximum recursion depth exceeded in comparison occurred while running config file products_row_validation.yaml. Skipping it for now
168 | 4740 | Filtered | failure | nA | nA | Filter - <Query filter on few records>Error - Error maximum recursion depth exceeded in comparison occurred while running config file products_row_validation.yaml. Skipping it for now
168 | 1 | Filtered | failure | nA | nA | Filter - <Query filter on few records>Error - Error maximum recursion depth exceeded in comparison occurred while running config file products_row_validation.yaml. Skipping it for now

Please refer the YAML : 
`result_handler:
  project_id: <project>
  table_id: <dataset.table>
  type: BigQuery
source: BQ_CONN
target: BQ_CONN
validations:
- calculated_fields: []
  comparison_fields:
  - cast: null
    field_alias: col1
    source_column: col1
    target_column: col1
  - <OTHER 168 COLUMNS >
  custom_query_type: row
  filter_status: null
  filters: []
  format: table
  labels:
  - !!python/tuple
    - validation_type
    - row
  primary_keys:
  - cast: null
    field_alias: pk
    source_column: pk
    target_column: pk
  random_row_batch_size: '1000'
  schema_name: null
  source_query: "select pk1 || pk2 || pk3 || pk4 as pk, <other 169 columns>\
    \ \nfrom `<dataset.external_table>`\
    \ \nwhere date = \"2023-07-01\""
  table_name: null
  target_query: "select pk1 || pk2 || pk3 || pk4 as pk, <other 169 columns>\
    \  \nfrom `<dataset.table>` \nwhere\
    \ date = \"2023-07-01\""
  target_schema_name: null
  target_table_name: null
  threshold: 0.0
  type: Custom-query
  use_random_rows: true`

Kindly let me know if you need more details on this.
Thanks

**Comment by madhu-jain** [comment]
Same error received for another feed while running validation between BQ External table and BQ Native table.
Validation type : row validation
No. of columns for validation : 158 columns
random rows : 10

yaml : 

result_handler:
  project_id: <project>
  table_id: <dataset>.results
  type: BigQuery
source: BQ_CONN
target: BQ_CONN
validations:
- calculated_fields: []
  comparison_fields:
  - cast: null
    field_alias: col1
    source_column: col1
    target_column: col1
  - cast: null
    field_alias: col2
    source_column: col2
    target_column: col2
  - cast: null
    field_alias: col158
    source_column: col158
    target_column: col158
  custom_query_type: row
  filter_status: null
  filters: []
  format: table
  labels:
  - !!python/tuple
    - validation_type
    - row
  - !!python/tuple
    - category
    - source_to_landing_validation
    - load_dt
    - '2023-06-27'
  primary_keys:
  - cast: null
    field_alias: pk
    source_column: pk
    target_column: pk
  random_row_batch_size: '10'
  schema_name: null
  source_query: SELECT col1, col2......col158 FROM `<project>.<dataset>.<table>` where ra_load_dte = '2023-06-27'
  table_name: null
  target_query: SELECT col1, col2......col158 FROM `<project>.<dataset>.<table>` where ra_load_dte = '2023-06-27'
  target_schema_name: null
  target_table_name: null
  threshold: 0.0
  type: Custom-query
  use_random_rows: true

PM-ERROR: Error maximum recursion depth exceeded occurred while running config file stores_row_validation.yaml. Skipping it for now.

**Comment by nehanene15** [comment]
There will be some upper limit for # of columns that can be validated. PR #1090 contains a fix that should increase the limit. We'll need to test this further and document the limit in the docs.

**Comment by nehanene15** [comment]
I suspect the upper limit may differ based on machine type/size of the columns. I hit the recursion error with ~98 columns. After the fix in the branch, I can validate up to ~140 columns. The fix here will increase the upper limit, but not completely remove it. 

The workaround here is to split the validation into two commands - one for the first 70 columns, another for the second 70 columns for example.

Once it's merged, would be curious to see how many columns you can validate with the same YAML.
