### ISSUE TITLE
custom query validation: Oracle non-deterministic numeric columns don't handle scale of None

### ISSUE THREAD

**Issue by nehanene15** [GoogleCloudPlatform/professional-services-data-validator#902]
When doing a custom query validation like so:
`
data-validation validate custom-query column \
  -sc MyOracleConnection \
  -tc MyBigQueryConnection \
  --source-query 'select product_id, warehouse_id, quantity*warehouse_id AS test from OT.inventories' \
  --target-query 'select product_id, warehouse_id, quantity*warehouse_id AS test from OT.inventories' \
  --count test
`

We see a TypeError for '>' not supported for NoneType and Int columns due to[ this line](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/third_party/ibis/ibis_oracle/client.py#L287). We need to handle the case that scale and precision can be None.

**Comment by piyushsarraf** [comment]
Hi @nehanene15 
Can you please explain on what are non-deterministic numeric datatype columns and if the scale is set to None, it will default to an integer right?

**Comment by nehanene15** [comment]
@piyushsarraf Yeah - for example in the custom query the user is generating a column `quantity*warehouse_id AS test`. The 'test' column doesn't have a specified precision/scale since it's computed in the query itself. In this case, Ibis sets the precision & scale to None and we get the error above.

**Comment by nehanene15** [comment]
I was able to reproduce this error in version 3.2.0, but it has been fixed with the latest version on the develop branch
