### ISSUE TITLE
Extreme memory consumption on random row hash validation

### ISSUE THREAD

**Issue by florisvink** [GoogleCloudPlatform/professional-services-data-validator#912]
Running the validation tool locally can lead to situations where extreme amounts of memory (90Gb) are used by the tool and will eventually crash. 

Example:
```
data-validation validate row -sc rs -tc bq -tbls some_redshift_schema.some_table=some_bigquery_dataset.some_bigquery_table --primary-keys _hash_key --comparison-fields avg_serp_position -rr -rbs 10
```

In this example the source data is a RedShift table (`rs` connection in example above) and compared against a BigQuery table (`bq` connection in example above).  The hashkey (`_hash_key` in example) is a fairly unique key. The table has not any weird properties like huge amount of columns or extreme cell payloads.

We've been playing around with different batch sizes and tried on different machines with different architectures. 

What's the best approach to find the cause of this issue?

**Comment by nehanene15** [comment]
You can see the SQL commands being run on RS and BQ with the `data-validation --verbose validate row...` flag. The query to generate random rows is [here](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/data_validation/query_builder/random_row_builder.py#L95) where we run something similar to `SELECT pk FROM table ORDER BY RAND() LIMIT 10` if your batch size is 10.

We then use the results of the above query in the WHERE clause of the validation query, so it should only be pulling 10 rows if the PK is unique.

There can be an explosion of rows with a non-unique PK when matching the source and target data frames in [combiner.py](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/data_validation/combiner.py) which may be the culprit.

**Comment by florisvink** [comment]
Thanks @nehanene15, after some query investigation using the `--verbose` flag it indeed seemed our unique key is not that unique after all :) We will try to create a composite key based on more fields.
