### ISSUE TITLE
Data validation b/w FileSystem (GCS bucket) and BigQuery?

### ISSUE THREAD

**Issue by cah-mahesh-kumar01** [GoogleCloudPlatform/professional-services-data-validator#920]
Is it possible to perform Data Validation for a CSV data in GCS bucket and BigQuery table?
IMHO data validation b/w two CSV files in a GCS is possible. Data validation b/w GCS and BigQuery is not possible.

**Comment by helensilva14** [comment]
Hello! Yes, it is possible to perform this validation using DVT. Please take a look at the following examples:

- To add a GCS connection for a file:

`data-validation connections add --connection-name GCS_CITIBIKE_CONN FileSystem --table-name gcs_citibike --file-path gs://<BUCKET_NAME>/citibike_stations.csv --file-type csv`

- To perform a validation between GCS and BQ:

`data-validation validate column -sc GCS_CITIBIKE_CONN -tc MY_BQ_CONN -tbls gcs_citibike=bigquery-public-data.new_york_citibike.citibike_stations`

**Comment by cah-mahesh-kumar01** [comment]
Hi @helensilva14, thanks for the valuable information. I am able to validate b/w GCS and BQ now.
TypeError: Unable to infer type of column 'TCN'. Try instantiating your table from the client with client.table('my_table', schema={'COLUMN_NAME': <explicit type>})
I am now getting this above error? Is there any flag which can be passed to data-validation to explicitly mention the data type

**Comment by nehanene15** [comment]
There isn't a way to pass in the schema currently. 

Our FileSystem connection is pretty limited in support since we use pandas to infer schema and we don't support row validation since pandas doesn't support a sha256 hash. We recommend using a [BigQuery external table](https://cloud.google.com/bigquery/docs/external-data-cloud-storage) and use that as a source table.

**Comment by cah-mahesh-kumar01** [comment]
Thanks @nehanene15

**Comment by helensilva14** [comment]
@cah-mahesh-kumar01 we will close this issue for now, but feel free to reopen if needed or open a new issue if you get something else. Thank you!
