### ISSUE TITLE
how to translate a custom-query column validation in json (which type?)

### ISSUE THREAD

**Issue by elena-gottardi-nttdata** [GoogleCloudPlatform/professional-services-data-validator#924]

**Comment by elena-gottardi-nttdata** [comment]
"data-validation (--verbose or -v) (--log-level or -ll) column" in cli ->"type: Column" in json configuration 
"data-validation (--verbose or -v) (--log-level or -ll) schema" in cli -> "type: Schema"  in json configuration 
"data-validation (--verbose or -v) (--log-level or -ll) row" in cli -> "type: Row"  in json configuration 
_**"data-validation (--verbose or -v) (--log-level or -ll) custom-query column" in cli -> "type: ??"  in json configuration**_

**Comment by helensilva14** [comment]
Hi @elena-gottardi-nttdata! It follows the same pattern with the first letter capitalized:

`data-validation custom-query column` in CLI is equivalent to `"type": "Custom-query"` in JSON with the additional parameter `"custom_query_type": "column"`.

Hope it helps! Reopen if needed or please open a new issue, thanks!
