### ISSUE TITLE
how to add --primary-key for row validation in json? 

### ISSUE THREAD

**Issue by elena-gottardi-nttdata** [GoogleCloudPlatform/professional-services-data-validator#925]
how can I implement the "primary key" statement in json for the row validation?
I tried the following code:
`{
   "configs":[
   {
      "type":"Row",
      "source_conn":{
         "source_type":"BigQuery",
         "project_id":"{{config.SOURCE_PROJECT|default('BQ_PROJECT', true)}}",
         "google_service_account_key_path":null
      },
      "target_conn":{
         "source_type":"BigQuery",
         "project_id":"{{config.TARGET_PROJECT|default('BQ_PROJECT', true)}}",
         "google_service_account_key_path":null
      },
      "schema_name":"{{tableInfo.SOURCE_SCHEMA|default('BQ_PROJECT.TERADATA_TABLE', true)}}",
      "table_name":"{{tableInfo.SOURCE_TABLE|default('BQ_TABLE', true)}}",
      "target_schema_name":"{{tableInfo.TARGET_SCHEMA|default('TERADATA_SCHEMA', true)}}",
      "target_table_name":"{{tableInfo.TARGET_TABLE|default('TERADATA_TABLE', true)}}",
      "result_handler":{
         "type":"BigQuery",
         "project_id":"{{config.RESULT_PROJECT|default('BQ_PROJECT', true)}}",
         "table_id":"{{config.RESULT_TABLE_ID|default('DVT_RESULTS_TABLE', true)}}"
      },
      "filters":[{
         "source": "{{tableInfo.WHERE_CONDITION_SOURCE|default('')}}",
         "target": "{{tableInfo.WHERE_CONDITION_TARGET|default('')}}",
         "type": "custom"
      }],
      "primary_keys":[{
         "cast": null,
         "field_alias": "id",
         "source_column": "id",
         "target_column": "id"
      }]
   }
   ]
}`

**Comment by helensilva14** [comment]
Python doesn't have an attribute with the term `null`, it uses `None` in place of `null`. So it's the following:

```python
    "primary_keys": [
        {
            "source_column": "id",
            "target_column": "id",
            "field_alias": "id",
            "cast": None
        }
    ]
```
