### ISSUE TITLE
Custom query is not supporting order by clause

### ISSUE THREAD

**Issue by prayas-purusottam-bakkt** [GoogleCloudPlatform/professional-services-data-validator#928]
Custom query is not supporting order by clause

**Comment by nehanene15** [comment]
Not sure if we can fix this since it's a Teradata limitation as described here: https://support.teradata.com/community?id=community_question&sys_id=3689c76b1b97fb00682ca8233a4bcba3

**Comment by piyushsarraf** [comment]
Yes, I think the same
We cannot have the nested query with order by in [teradata](https://knowledge.informatica.com/s/article/179572?language=en_US#:~:text=This%20issue%20occurs,is%20not%20known.).

**Comment by Raniksingh** [comment]
For row validation DVT generates nested SQL with the input queries as the base. Hence its failing as teradata doesn't allow order by in nested query.
To solve this we can rewrite the input query in following ways:

Option 1 : select top 100 PERCENT * from dvt.DEPARTMENT order by dept_no desc; 

Option 2: SELECT *  FROM dvt.DEPARTMENT QUALIFY ROW_NUMBER() OVER (ORDER BY dept_no DESC) <=10;

Both the above queries provide same results.
