### ISSUE TITLE
Multiple Tables in Request

### ISSUE THREAD

**Issue by ghost** [GoogleCloudPlatform/professional-services-data-validator#932]
Using the CLI, it is possible to run multiple validations spanning a set of tables. Is it possible to achieve the same result using the Flask endpoint?

Thank you in advance.

**Comment by nehanene15** [comment]
No, the Flask endpoint takes a ConfigManager.config JSON value which can correspond to one table only. When running multiple table validations using the CLI, we generate multiple ConfigManagers and run those serially. Hope this helps!

**Comment by ghost** [comment]
Thank you! I opened a draft PR for a new docker version. I should have it sorted out in a day or so. I hope your'e well.
Tom
