### ISSUE TITLE
row validation for all fields in json configuration

### ISSUE THREAD

**Issue by elena-gottardi-nttdata** [GoogleCloudPlatform/professional-services-data-validator#940]
I've tried to use row validation passing a json configuration.
The only way to have a run without errors is passing the following:
`{
   "configs":[
   {
      "type":"Row",
      "source_conn":{
         "source_type":"BigQuery",
         "project_id":"{{config.SOURCE_PROJECT|default('BQ_PROJECT', true)}}",
         "google_service_account_key_path":null
      },
      "target_conn":{
         "source_type":"BigQuery",
         "project_id":"{{config.TARGET_PROJECT|default('BQ_PROJECT', true)}}",
         "google_service_account_key_path":null
      },
      "schema_name":"{{tableInfo.SOURCE_SCHEMA|default('BQ_PROJECT.TERADATA_TABLE', true)}}",
      "table_name":"{{tableInfo.SOURCE_TABLE|default('BQ_TABLE', true)}}",
      "target_schema_name":"{{tableInfo.TARGET_SCHEMA|default('TERADATA_SCHEMA', true)}}",
      "target_table_name":"{{tableInfo.TARGET_TABLE|default('TERADATA_TABLE', true)}}",
      "result_handler":{
         "type":"BigQuery",
         "project_id":"{{config.RESULT_PROJECT|default('BQ_PROJECT', true)}}",
         "table_id":"{{config.RESULT_TABLE_ID|default('DVT_RESULTS_TABLE', true)}}"
      },
      "filters":[{
         "source": "{{tableInfo.WHERE_CONDITION_SOURCE|default('')}}",
         "target": "{{tableInfo.WHERE_CONDITION_TARGET|default('')}}",
         "type": "custom"
      }],
      "primary_keys": [
        {
            "source_column": "id",
            "target_column": "id",
            "field_alias": "id",
            "cast": null
        }
      ],
      "comparison_fields": [
         {
            "source_column": "field1",
            "target_column": "field1",
            "field_alias": "field1",
            "cast": null
         },
         {
            "source_column": "field2",
            "target_column": "field2",
            "field_alias": "field2",
            "cast": null
         },
         {
            "source_column": "field3",
            "target_column": "field3",
            "field_alias": "field3",
            "cast": null
         },
         {
            "source_column": "field4",
            "target_column": "field4",
            "field_alias": "field4",
            "cast": null
         }
      ]
   }
   ]
}`
So passing "comparison_fields" key is working.
Actually I just want to have a row validation on all fields without specifying them.
If I pass the json configuration without "comparison_fields" key the tool is not taking automatically all the fields, but it is actually returning the error: 
`TypeError: reduce() of empty sequence with no initial value`
Is there a way to perform a row validation without being forced to list the comparison fields?
By the way, the same issue is with the custom-query validation using the "custom_query_type": "row".
Thank you very much.

**Comment by nehanene15** [comment]
We don't support the '*' flag for comparison fields, only -concat and -hash. The easiest way to generate the JSON for concat/hash without manually adding column names is to add a line `print (config_manager.config)` after [this line](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/data_validation/__main__.py#L465) to output the JSON config. Hope this helps!

**Comment by elena-gottardi-nttdata** [comment]
Thanks for answering me. 
So, what is the key name to add in the json configuration to enable hashing?

**Comment by nehanene15** [comment]
You will need a primary key for all row validations. When you run the validation you can specify a single column or '*' for all columns in the `--hash column` or `--concat column` flag. 

Once you add the line `print (config_manager.config)` after [this line](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/data_validation/__main__.py#L465) and run `pip install .` to re-package the changes, you can run `data-validation --dry-run validate row ... -hash column` to see the printed JSON config manager you can use
