### ISSUE TITLE
Support for python-oracledb

### ISSUE THREAD

**Issue by kangshung** [GoogleCloudPlatform/professional-services-data-validator#942]
Hello, [from what I see](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/docs/connections.md#oracle), DVT connects to Oracle using [cx_Oracle package which is no longer maintained](https://github.com/oracle/python-cx_Oracle/releases).

Are there any plans to support its successor [python-oracledb](https://python-oracledb.readthedocs.io/en/latest/index.html)?

**Comment by nehanene15** [comment]
Yeah, the newer Ibis upgrade which we use to connect to our databases uses the new python-oracledb: https://ibis-project.org/backends/oracle/#connecting-to-older-oracle-databases

Once we upgrade our Ibis version from 5.1.0 to 6.1.0 in Issue #931 we will look into this.

**Comment by helensilva14** [comment]
Hi @kangshung!

I hope Neha's answer addressed your question, I'll be closing this issue, but please feel free to reopen it if needed! 

Thanks for your interest in DVT!

**Comment by kangshung** [comment]
Hi @nehanene15, thanks for the info.

Do you know if there's gonna be an option to use the THICK client mode? https://python-oracledb.readthedocs.io/en/latest/user_guide/initialization.html#enabling-python-oracledb-thick-mode

Also, do you have any time frame for the #931 issue to be completed and released?

**Comment by nehanene15** [comment]
It doesn't look like Ibis supports the THICK client mode natively: https://ibis-project.org/backends/oracle/#connection-parameters

It probably won't be a priority until next year - the switch to python-oracledb will most likely introduce some changes in the SQL generation that we'll have to refactor.

**Comment by kangshung** [comment]
FYI, @nehanene15  THICK client mode [connects successfully](https://github.com/ibis-project/ibis/issues/6913) in the latest version of ibis, however its Oracle support is currently at the experimental stage at best.

**Comment by helensilva14** [comment]
Thanks a lot for the update @kangshung!
