### ISSUE TITLE
Allow-list argument for Schema Validation not mapping datatypes accurately

### ISSUE THREAD

**Issue by SwatiT17** [GoogleCloudPlatform/professional-services-data-validator#943]
Teradata Table schema:
CREATE MULTISET TABLE DVT.EMPLOYEE ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      emp_no INTEGER,
      emp_name VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      job_title VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC,
      manager_id INTEGER,
      hire_date DATE FORMAT 'YY/MM/DD',
      salary DECIMAL(18,2),
      commission DECIMAL(18,2),
      dept_no INTEGER,
      create_ts TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP(0))
PRIMARY INDEX ( emp_no );

BQ Table schema:
CREATE TABLE dvt.employee
(
  emp_no INT64,
  emp_name STRING,
  job_title STRING,
  manager_id INT64,
  hire_date DATE,
  salary NUMERIC(31, 2),
  commission NUMERIC(31, 2),
  dept_no INT64,
  create_ts TIMESTAMP
)

Considering Datatype in Teradata for 2 columns is DECIMAL(18,2) it should be mapped to NUMERIC(31, 2) as per BQ table schema

Expected DVT command:(which doesn't do datatype mapping accurately & results in Validation Fail status)
data-validation validate schema --source-conn TD_CONN --target-conn BQ_CONN --tables-list dvt.EMPLOYEE=dvt.employee --allow-list "DECIMAL(18,2):decimal(38,9)"

Accurately running DVT command:
data-validation validate schema --source-conn TD_CONN --target-conn BQ_CONN --tables-list dvt.EMPLOYEE=dvt.employee --allow-list "float64:decimal(38,9)"

<img width="1469" alt="Screenshot 2023-08-14 at 6 11 48 PM" src="https://github.com/GoogleCloudPlatform/professional-services-data-validator/assets/129146107/59bb1d4e-d94e-45e0-b4d8-00224b836d66">

**Comment by nehanene15** [comment]
Can you try with lowercase mapping `--allow-list "decimal(18,2):decimal(38,9)"`?
Or is the issue here that the DECIMAL(18,2) is being interpreted as a float64 type? If so, are you running the latest version of the tool? All numbers in TD map to decimals.

**Comment by SwatiT17** [comment]
Yes the issue is DECIMAL(18,2) is being interpreted as a float64 type instead of decimal(18,2).Does that imply in allow-list we should not map source datatypes & instead map ibis interpreted datatypes to target datatypes

**Comment by nehanene15** [comment]
Yes, allowlist applies to the Ibis data type mappings. But Teradata DECIMAL(18,2) should be treated as "decimal(18,2)" in schema validations as tested in our integration tests: https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/tests/system/data_sources/test_teradata.py#L249

We only convert Teradata 'F' or 'Float' types to float64
