### ISSUE TITLE
Custom Query Row Validation Fails for Char Datatype in Teradata

### ISSUE THREAD

**Issue by SwatiT17** [GoogleCloudPlatform/professional-services-data-validator#952]
Custom Query Validation Fails between Teradata & Bigquery for Char type column  while the data actually matches- CHAR(32) in TD & String in Bigquery

Compared column: emp_name

Teradata table schema:
CREATE MULTISET TABLE DVT.EMPLOYEE_TEST ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      emp_no INTEGER,
      emp_name CHAR(32) CHARACTER SET LATIN NOT CASESPECIFIC,
      job_title VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC,
      manager_id INTEGER,
      hire_date DATE FORMAT 'YY/MM/DD',
      salary DECIMAL(18,2),
      commission DECIMAL(18,2),
      dept_no INTEGER)
PRIMARY INDEX ( emp_no );

DVT Command:
data-validation validate custom-query row --source-conn TD_CONN --target-conn BQ_CONN -sqf td_sql.sql -tqf bq_sql.sql -pk=emp_no -comp-fields=emp_name 

td_sql.sql:
select top 5 * from dvt.EMPLOYEE_TEST order by emp_no;
bq_sql.sql:
select * FROM my-test-world-ts.dvt.employee order by emp_no limit 5;

<img width="1496" alt="Screenshot 2023-08-22 at 7 34 21 PM" src="https://github.com/GoogleCloudPlatform/professional-services-data-validator/assets/129146107/18819162-1d4c-4425-b1f5-88e907f37392">

**Comment by nehanene15** [comment]
This seems similar to Issue #927 - have you tried with the latest release and after casting the CHAR columns to VARCHAR?

**Comment by nehanene15** [comment]
The teradatasql package used by DVT automatically adds padding to CHAR columns which leads to mismatching data between TD and BQ.

You will need to cast to 'string' to avoid this. You can either do that in the query itself: 
`select top 5 CAST(emp_name AS VARCHAR) from dvt.EMPLOYEE_TEST order by emp_no;`

or within the YAML file like so:
```yaml
comparison_fields:
  - cast: null
    field_alias: emp_name
    source_column: emp_name
    target_column: emp_name
```
