### ISSUE TITLE
Snowflake and BINARY datatype

### ISSUE THREAD

**Issue by henrihem** [GoogleCloudPlatform/professional-services-data-validator#958]
Trying to run data validation to Snowflake. Target table has fields with datatype BINARY and the following error occurs:
`Error Could not find signature for dtype: <SnowflakeDialect, BINARY> occurred while running config file example.yaml. Skipping it for now.`

Or without yaml-file:
`NotImplementedError: Could not find signature for dtype: <SnowflakeDialect, BINARY>`

**Comment by helensilva14** [comment]
Hi @henrihem! Are you performing a Snowflake to Snowflake validation? If not, what are your source and target databases?

**Comment by henrihem** [comment]
@helensilva14 The validation is from Snowflake to BigQuery.

**Comment by helensilva14** [comment]
Thanks! I did the fix for BINARY and now just making sure other data types don't have the same problem. PR is under progress.

**Comment by helensilva14** [comment]
Hi @henrihem, PR is merged! You can already make use of our fix if you're able to use the code from our develop branch ( checkout to it and run pip install . ), if you need to have it on PyPi, you'll need to wait for our next patch release soon.
