### ISSUE TITLE
Filter Status flag not working

### ISSUE THREAD

**Issue by mayanksroy01** [GoogleCloudPlatform/professional-services-data-validator#967]
data-validation validate schema \
--source-conn BQ_CONN \
--target-conn BQ_CONN \
--tables-list $PROJECT_ID.$DB.Employees1=$PROJECT_ID.$DB.Salary \
-fs fail

Getting this error : unrecognized arguments: -fs fail

**Comment by helensilva14** [comment]
Hello! You need to use either all commands in the long version or all of them with the short version to be able to run it.

In your case, by changing -fs to --filter-status it will work or you can change the other ones to -sc, -tc, -tbls that it will also work as well.

Let me know if you need further help!

**Comment by helensilva14** [comment]
Closing it for now, please reopen if needed, thanks!

**Comment by mayanksroy01** [comment]
I tried with long version also. It still fails.
Here is the screenshot : 
<img width="956" alt="image" src="https://github.com/GoogleCloudPlatform/professional-services-data-validator/assets/143734426/b6ccdf3c-9d53-4bbf-9ca0-6d07fb922398">

**Comment by helensilva14** [comment]
Hmmm I see it, which DVT version do you have installed in your Cloud Shell?

**Comment by helensilva14** [comment]
Also have you tried putting the whole command in a single line? Maybe there's some formatting/line break doing something, just for us to at least eliminate this possibility.

**Comment by mayanksroy01** [comment]
Yes, I've tried one line command as well. Didn't work.
How do I know my DVT version. ? Is there any specific command for that?

**Comment by mayanksroy01** [comment]
I think I'm using 1.7.2. Is there any newer version?

**Comment by helensilva14** [comment]
You can use `pip show google-pso-data-validator` to see your current version.

At the moment, our latest release is the 4.1.0 version, you can take a look here: https://pypi.org/project/google-pso-data-validator/#history

**Comment by mayanksroy01** [comment]
I updated the version, but seeing this error now : 
<img width="959" alt="image" src="https://github.com/GoogleCloudPlatform/professional-services-data-validator/assets/143734426/1de81b0e-8b8e-4e90-9357-2cad8dcebca8">

what should be my next step.

**Comment by helensilva14** [comment]
We did lots of dependency updates in this mean time, so please create a brand new virtual env with `python -m venv <new-env-name>`, activate it and then install and use the latest DVT version there. Let me know if it works!

**Comment by mayanksroy01** [comment]
Okay, I'll try this.

**Comment by mayanksroy01** [comment]
Yes, it is working now.

**Comment by helensilva14** [comment]
Glad to hear it is working! If you find a new problem, please feel free to open a new issue, thanks for using DVT!
