### ISSUE TITLE
Need to add an option to provide lock types (e.g: access lock) to be provided in queries to Teradata

### ISSUE THREAD

**Issue by kanhaPrayas** [GoogleCloudPlatform/professional-services-data-validator#969]
Need to add an option to provide lock types (e.g: access lock) to be provided in queries to Teradata. Right now if we are running any dvt command while query execution its taking default locking set in DB. Issue is if let say read lock is there in Teradata, the dvt will block any other incoming critical sessions from read and write.

**Comment by nehanene15** [comment]
This will involve making the no_lock_sql flag available when creating TD connections: https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/third_party/ibis/ibis_teradata/__init__.py#L33
