### ISSUE TITLE
NullColumn error during column validation

### ISSUE THREAD

**Issue by kanhaPrayas** [GoogleCloudPlatform/professional-services-data-validator#970]
We are getting following error while running column validation :

`09/04/2023 05:07:04 AM-ERROR: Error unsupported operand type(s) for -: 'NullColumn' and 'NullColumn' occurred while running config file f86910a6-1335-4b9d-841b-1d7b7b195fa4.yaml. Skipping it for now.`

**Comment by kanhaPrayas** [comment]
This happens when there is no data in the table. Instead of throwing exception we should raise proper error.

**Comment by nehanene15** [comment]
If the first row is NULL for numeric fields, the pandas schema is inferred as 'string'.
The above 'Unsupported operand type' error is if all rows are NULL.

**Comment by nehanene15** [comment]
I'm having a hard time reproducing this. 

When running a sum validation on a table with all NULLs for an INT column:

```
│ validation_name   │ validation_type   │ source_table_name   │ source_column_name   │   source_agg_value │   target_agg_value │   pct_difference │ validation_status   │ run_id                               │
╞═══════════════════╪═══════════════════╪═════════════════════╪══════════════════════╪════════════════════╪════════════════════╪══════════════════╪═════════════════════╪══════════════════════════════════════╡
│ count             │ Custom-query      │                     │                      │                  7 │                  7 │                0 │ success             │ 214d66dc-4137-449e-b4d0-ea23c7bc8f95 │
├───────────────────┼───────────────────┼─────────────────────┼──────────────────────┼────────────────────┼────────────────────┼──────────────────┼─────────────────────┼──────────────────────────────────────┤
│ sum__age          │ Custom-query      │                     │ age                  │                nan │                nan │              nan │ success             │ 214d66dc-4137-449e-b4d0-ea23c7bc8f95 │
```

Also, doing a validation on a column like so:
![image](https://github.com/GoogleCloudPlatform/professional-services-data-validator/assets/25696756/69a86fb1-ae52-4110-94ce-e1128afc9eca)

I get the proper validation results (tested with custom query and regular column validation):
```
│ validation_name   │ validation_type   │ source_table_name   │ source_column_name   │   source_agg_value │   target_agg_value │   pct_difference │ validation_status   │ run_id                               │
╞═══════════════════╪═══════════════════╪═════════════════════╪══════════════════════╪════════════════════╪════════════════════╪══════════════════╪═════════════════════╪══════════════════════════════════════╡
│ sum__age          │ Custom-query      │                     │ age                  │                  5 │                  5 │                0 │ success             │ 7fcf956c-9b24-426d-b57e-fd2a6a847e9a │
├───────────────────┼───────────────────┼─────────────────────┼──────────────────────┼────────────────────┼────────────────────┼──────────────────┼─────────────────────┼──────────────────────────────────────┤
│ count             │ Custom-query      │                     │                      │                  5 │                  5 │                0 │ success             │ 7fcf956c-9b24-426d-b57e-fd2a6a847e9a
```

**Comment by nehanene15** [comment]
For reference,

This is typically where Ibis infers the schemas of the pandas source and target dataframe: https://github.com/ibis-project/ibis/blob/5.1.0/ibis/backends/pandas/client.py#L91

The source_df and target_df here are treated as Ibis pandas tables: https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/data_validation/data_validation.py#L310

**Comment by rishabkhawad** [comment]
**Try it with column datatype as bignumeric, not int.**

_Table and schema in BQ:_

<img width="1082" alt="Screenshot 2023-09-07 at 1 07 55 PM" src="https://github.com/GoogleCloudPlatform/professional-services-data-validator/assets/118872983/8e8c2532-78b2-47ea-b216-33d201cf4406">

DVT Command - 
`data-validation validate column   -sc ppbq   -tc ppbq   -tbls my-test-world-ts.dvt.nulltable2 --sum 'id'`


Error ss:
<img width="1189" alt="Screenshot 2023-09-07 at 1 10 12 PM" 
src="https://github.com/GoogleCloudPlatform/professional-services-data-validator/assets/118872983/1492ddf1-e02e-4fab-8b10-0dd97730ed74">


Also, for easy debug, ss for the column type picked by pandas in this case for sum__id : 

<img width="652" alt="Screenshot 2023-09-07 at 1 12 34 PM" src="https://github.com/GoogleCloudPlatform/professional-services-data-validator/assets/118872983/453fb98b-3169-44a4-8a2d-8dd75ca2a644">


We need a way for pandas to infer it as float64, which it does in case of the null integer column test-case you commented.

<img width="726" alt="image" src="https://github.com/GoogleCloudPlatform/professional-services-data-validator/assets/118872983/b509e10c-7113-4bb4-8e25-13fc337bc18a">
