### ISSUE TITLE
YAML validation directories supported in GCS, but not validation files in GCS

### ISSUE THREAD

**Issue by sundar-mudupalli-work** [GoogleCloudPlatform/professional-services-data-validator#972]
Hi,

When we have YAML directories in GCS, they are supported - so the command `data-validation configs run -cdir gs://mudu-plex-pri-myb/db6rows/public.iowa_27rows` works when you have yaml files in that directory.

However specifying `data-validation configs run -c gs://mudu-plex-pri-myb/db6rows/public.iowa_27rows/0001.yaml` throws the following error
```
  File "/home/mudupalli/professional-services-data-validator/env/lib/python3.9/site-packages/data_validation/state_manager.py", line 190, in _read_file
    with open(file_path, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: './gs://mudu-plex-pri-myb/db6rows/public.iowa_27rows/0001.yaml'
```

This is a bug.

Thanks.

Sundar Mudupalli

**Comment by afleisc** [comment]
+1 This is something we are trying to do for another customer
