### ISSUE TITLE
Grouped Column Validation does not accept (nor need) primary keys

### ISSUE THREAD

**Issue by sundar-mudupalli-work** [GoogleCloudPlatform/professional-services-data-validator#982]
Hi,

The documentation under `validate column` says `--primary-keys or -pk PRIMARY_KEYS` `Comma separated list of columns to use as primary keys`. However the command does not take (nor does it need) primary keys. The `--grouped-columns` flag alone is suffficient. I also took a look at the code - [cli_tools.py](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/data_validation/cli_tools.py) and the function `_configure_column_parser` does not have primary key as an optional argument, while `--grouped-columns` is an optional argument.

```
data-validation validate column -sc=my_postgres -tc=my_postgres -tbls public.group_test_1=public.group_test_2 -pk=store_id,rev_month -gc=store_id,rev_month --sum revenue  --filter-status=fail
data-validation: error: unrecognized arguments: -pk=store_id,rev_month
data-validation validate column -sc=my_postgres -tc=my_postgres -tbls public.group_test_1=public.group_test_2  -gc=store_id,rev_month --sum revenue  --filter-status=fail
09/12/2023 02:10:12 AM-WARNING: Unknown cast types can cause memory errors
09/12/2023 02:10:12 AM-WARNING: Unknown cast types can cause memory errors
09/12/2023 02:10:12 AM-WARNING: Unknown cast types can cause memory errors
09/12/2023 02:10:12 AM-WARNING: Unknown cast types can cause memory errors
╒═══════════════════╤═══════════════════╤═════════════════════╤══════════════════════╤════════════════════╤════════════════════╤══════════════════╤═════════════════════╤══════════╕
│ validation_name   │ validation_type   │ source_table_name   │ source_column_name   │ source_agg_value   │ target_agg_value   │ pct_difference   │ validation_status   │ run_id   │
╞═══════════════════╪═══════════════════╪═════════════════════╪══════════════════════╪════════════════════╪════════════════════╪══════════════════╪═════════════════════╪══════════╡
╘═══════════════════╧═══════════════════╧═════════════════════╧══════════════════════╧════════════════════╧════════════════════╧══════════════════╧═════════════════════╧══════════╛

**Comment by piyushsarraf** [comment]
Hi @sundar-mudupalli-work , 

In my testing, I was getting an explicit error stating that `error: unrecognized arguments: -pk=dept_no,loc_name` and DVT stopped execution, is the bug fixed? 
![image](https://github.com/GoogleCloudPlatform/professional-services-data-validator/assets/47020544/1fc7e203-8fe9-47a0-af8e-2f227597db67)


If so, can we just edit the doc?

**Comment by sundar-mudupalli-work** [comment]
Piyush,

Yes it still has to go through a pull request (I believe). Do you need this immediately ? - is this impacting a customer ?

I put it in the system and was planning to include both of the doc issues I found (982 and 983) on a upcoming PR.

Thanks.

Sundar Mudupalli

**Comment by piyushsarraf** [comment]
@sundar-mudupalli-work 

No, I was just looking on some open issues and wanted to contribute, so thought of asking for update. 

Thank you.
