### ISSUE TITLE
Default Results Table Location

### ISSUE THREAD

**Issue by mayanksroy01** [GoogleCloudPlatform/professional-services-data-validator#995]
As per this example, 
https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/samples/airflow/dvt_airflow_dag.py

it pushes the results table to 'project.pso_data_validator.results' table.
How can I change the destination for results table to a desired location. 
For e.x to a location like 'project.database.data_validation_results.

**Comment by nehanene15** [comment]
You can do so by updating [this line](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/samples/airflow/dvt_airflow_dag.py#L79) to 
`handler = bqhandler.BigQueryResultHandler.get_handler_for_project(project, table_id="database.data_validation_results")`
